### ISSUE TITLE
legacy (1.8) release matrix and testing

### ISSUE THREAD

**Issue by judovana** [AdoptOpenJDK/IcedTea-Web#10]
The matrix of ITW is pretty big, maybe in time we will agree on some reduce. I dont know if it have
still reason to keep jsobject and plugin jars - they are only for javaws --html usage.
Currently you should be building following:

All with  --disable-native-plugin; the removal of native plugin should be major goal for next release.
for all native builds you can include --with-kcov, and also run make rust-code-coverage.
For unittests you can include jacoco fo junit codecoverage[another make calla fter make check] (it
is working also for integration suite, but not sure if it is worthy of second N hours run)

windows (native):
 - machine with cygwin, and preinstalled jdk, tagsoup, mslinks, wixgen, wstools, wix, rust, cargo.
For testing junit,+ possibly asm and hamcrest. For plugin jar rhino.
   - restult will be:
    - results of make check - html + xml files withjunit results
    - icedtea-web-x.y.win.bin.zip (result of make win-bin-dist)
    - itw-installer.msi  (result of make win-installer)

One job will do those.
Those are portable builds, and should be built with  --with-itw-libs=BUNDLED

linux (native):
 - machine with any linux, as rust have currently only static linking. Preinstalled jdk, tagsoup,
rust, cargo. For testing junit,+ possibly asm and hamcrest. For plugin jar - rhino.
   - restult will be:
    - results of make check - html + xml files with junit results
    - icedtea-web-x.y.linux.bin.zip (result of make win-bin-dist)

This job can not be combined with multipaltform shell build
this is portable builds, and should be built with  --with-itw-libs=BUNDLED

linux+win (portable):
 - any linux machine, with preinstalled jdk, tagsoup, mslinks, wixgen, wstools, wix. For testing
junit,+ possibly asm and hamcrest. For plugin jar rhino. with *removed*  rust and cargo.
   - restult will be:
    - results of make check - html + xml files with junit results
    - icedtea-web-x.y.linux.bin.zip, where ti should eb renamed to icedtea-web-x.y.portable.bin.zip
 (this slipped from makefiles)

This job can not be combined with native linux build
this is portable builds, and should be built with  --with-itw-libs=BUNDLED

In both linux bulds you can stumble over bashcompdir variable, which should point to $PREFFIX value.
The inclusion of the bashcomplition into portbale build on linux is disputable.

Integration test suite
Itw have pretty good integration suite, which was designed mostly for plugin. So 50% of it si
candidate for removal. Even now, with --with-browser-tests=no it runs few hours (with plugin, if it
goes wrong, and on all browsers, you will get to some 20hours). Neverthe less,with
--with-browser-tests=no, this testsuite should be run - three times. it always run on top of make
install fresh image.
It should be run once for windows BUNDLED mode, one for linux BUNDLED mode, and once for linux
DISTRIBUTION mode (--with-itw-libs).

Output of integration testsuit (make -j1 run-netx-dist-tests) is same as foj unittests - html+xml files.

I would like to higholight, that all those 6 jobs currentoy have sense.

**Comment by karianna** [comment]
To add to this we need to actually import the 1.8 branch, somehow!

**Comment by karianna** [comment]
And we want to move over 1.7 as well.

**Comment by sclassen** [comment]
I was able to create the branches in my clone of the repo.
But I need to create new branches first before I can open a pull request.
Can someone create the following branches
* 1.7 at icedtea-web-1.7-branchpoint
* 1.8 at icedtea-web-1.8-branchpoint

Once this is done I can open the pull requests

**Comment by karianna** [comment]
@sclassen I think you have the rights to do that yourself?

**Comment by AndreasEhret** [comment]
> I was able to create the branches in my clone of the repo.
> But I need to create new branches first before I can open a pull request.
> Can someone create the following branches
> 
>     * 1.7 at icedtea-web-1.7-branchpoint
> 
>     * 1.8 at icedtea-web-1.8-branchpoint
> 
> 
> Once this is done I can open the pull requests

the new branches are created, you can go on with the pull requests

**Comment by hendrikebbers** [comment]
You should have the access to the repo to create such branches. Will ping you later.

Von meinem iPhone gesendet

**Comment by hendrikebbers** [comment]
PRs for 1.8 and 1.7 branches: #18 #19

**Comment by Jamila891** [comment]
Can we close this issue @charliegracie ?

**Comment by charliegracie** [comment]
Yes
