### ISSUE TITLE
Downloads all jars even though they are already in cache - no If-Modified-Since support either
        

### ISSUE THREAD

**Issue by AndreasEhret** [AdoptOpenJDK/IcedTea-Web#101]
This issue was imported from bugzilla with bugzilla2github
# Bugzilla Bug Referenze: [2031](https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=2031)
Date: 2014-10-14 15:20:00 +0000
From: Will Tatam &lt;<will.tatam>&gt;
To:   Unassigned &lt;<unassigned>&gt;
CC:   unassigned

Last updated: 2014-12-03 21:44:19 +0000

## Comment 9018
Date: 2014-10-14 15:20:15 +0000
From: Will Tatam &lt;<will.tatam>&gt;

IceTea webstart appear to be trying to download the same files every time we launch the application
                from the JnlpDownloadServlet

                It does not send the If-Modified-Since header so the servlet can't send a No Modified response

                It also tries to download the files even though the jnlp file states that we are using versioned JARs,
                so should therefore only be attempting to download in the first place if it has no such jar with that
                version

**Comment by lherschi** [comment]
I think the ticket can be closed. Due to the changes in b826faf and 662c701, only HEAD requests are sent first and the results are correctly compared to the cache.
