### ISSUE TITLE
IcedTea-Web always redownloads web start application if they are packed

### ISSUE THREAD

**Issue by AndreasEhret** [AdoptOpenJDK/icedtea-web#102]
This issue was imported from bugzilla with bugzilla2github
# Bugzilla Bug Referenze: [1777](https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=1777)
Date: 2014-05-19 14:25:00 +0000
From: Lars Herschke &lt;<lhersch>&gt;
To:   Omair Majid &lt;<omajid>&gt;
CC:   aazores, unassigned

Last updated: 2019-04-02 09:07:04 +0000

## Comment 8145
Date: 2014-05-19 14:25:50 +0000
From: Lars Herschke &lt;<lhersch>&gt;

When you start an webstart-application that have packed resources, the resources are downloaded
                even if they are cached. The Problem is in net.sourceforge.jnlp.cache.CacheEntry.isCached(). Here is the
                length of the uncompressed local file compared with the length of the compressed download-resource.
                That's not equal of course and so isCached() return false.

                For testing you can use following application.
                http://portal.incore.de/dss-portal.jnlp
            

## Comment 8392
Date: 2014-06-17 20:19:45 +0000
From: Andrew Azores &lt;<aazores>&gt;

I believe Omair fixed this fairly recently. Lars, can you try again with IcedTea-Web HEAD? I just
                tested it with the URL you provided and it seems to have used the cached resources, judging by how
                quickly the progress indicator jumped directly to 100% on the second run.
            

## Comment 8400
Date: 2014-06-18 14:23:41 +0000
From: Lars Herschke &lt;<lhersch>&gt;

The Issue is solved in HEAD (changeset 1001:d150e4453b0b).
                Many thanks.
            

## Comment 17478
Date: 2019-03-28 10:31:14 +0000
From: Lars Herschke &lt;<lhersch>&gt;

Created attachment 1728
                described patch
            

> Attached file: src_726d53216a2621706543644c479b48cad847b651.patch (text/plain, 7143 bytes)
> Description:   described patch

## Comment 17479
Date: 2019-03-28 10:31:43 +0000
From: Lars Herschke &lt;<lhersch>&gt;

The problem is present again since mercurial revison 1120 or since git revision 602791e. Here is a
                patch that fixes the problem. The pure fix is the patch for ResourceDownloader.java. The patches for
                CacheEntry.java and CacheEntryTest.java only remove the code that has been obsolete since revision 1120.
            

## Comment 17480
Date: 2019-03-28 11:16:32 +0000
From: Lars Herschke &lt;<lhersch>&gt;

pull request:
                https://github.com/AdoptOpenJDK/icedtea-web/pull/4
            

## Comment 17498
Date: 2019-04-02 09:07:04 +0000
From: Lars Herschke &lt;<lhersch>&gt;

new pull request, with desired commit-message:
                https://github.com/AdoptOpenJDK/icedtea-web/pull/11

**Comment by lherschi** [comment]
Can be closed. Pull request was merged into master
