### ISSUE TITLE
Windows desktop shortcut contains wrong target if javaws.exe is accessible via the path

### ISSUE THREAD

**Issue by AndreasEhret** [AdoptOpenJDK/icedtea-web#111]
This issue was imported from bugzilla with bugzilla2github
# Bugzilla Bug Referenze: [3709](https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3709)
Date: 2019-03-19 17:27:00 +0000
From: Lars Herschke &lt;<lhersch>&gt;
To:   JiriVanek &lt;<jvanek>&gt;
CC:   unassigned

Last updated: 2019-04-01 10:16:00 +0000

## Comment 17467
Date: 2019-03-19 17:27:06 +0000
From: Lars Herschke &lt;<lhersch>&gt;

Created attachment 1726
                described patch

                When javaws.exe comes out of the path, it does not contain any directory part. When passed it so to the
                createLink method, the current working directory is set before that.

                Here is a patch that fixes this and a few more things.

                - findOnPath returns the full path including directory part
                - getJavaWsBin now prefers KEY_JAVAWS_LOCATION before the path (important if you also have Oracle Java
                installed)
                - on windows, the icon from the jnlp file is also used now for desktop and menu entry
                - the icon is converted to bmp if it is in a format unsupported by windows
                - the patch fixes a npe in createWindowsMenu
                - Windows menu items can now also be created if it is not intended by the application
            

> Attached file: src_1590_47c7a6a49d0e.patch (text/plain, 7158 bytes)
> Description:   described patch

## Comment 17468
Date: 2019-03-20 12:58:12 +0000
From: JiriVanek &lt;<jvanek>&gt;

Hi!

                Thank you very much! Do you mind to post this as pull request to ITW's new home of
                https://github.com/AdoptOpenJDK/icedtea-web ? Form is on you, but should follow used github flow.

                If you have issue, I will take that from here.
            

## Comment 17472
Date: 2019-03-21 12:45:51 +0000
From: Lars Herschke &lt;<lhersch>&gt;

I have now generated a pull request. I've made a few changes to the patch. If necessary, the icon
                will now be converted to the ico format, as bmp does not support transparency.
            

## Comment 17496
Date: 2019-04-01 10:16:00 +0000
From: Lars Herschke &lt;<lhersch>&gt;

pull request:
                https://github.com/AdoptOpenJDK/icedtea-web/pull/1

**Comment by lherschi** [comment]
Can be closed. Pull request was merged into master.
