### ISSUE TITLE
Better exception handling

### ISSUE THREAD

**Issue by hendrikebbers** [AdoptOpenJDK/IcedTea-Web#135]
There are a lot of places in the code that look like this:

```
try {
...
} catch(Exception e) {
   LOG.error("......", e);
}

```
This should be refactored by throwing more concrete exceptions in the catch instead of just doing logging. In most places it makes more sense to throw an exception.

**Comment by Budlee** [comment]
Not sure that this is a good first contrib but I would be keen to help with this one. 
What do you mean by the automation label?
