### ISSUE TITLE
No translation in log & exception messages

### ISSUE THREAD

**Issue by hendrikebbers** [AdoptOpenJDK/IcedTea-Web#136]
**🆕🐥🐶 First Timers Only**
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

**👾 Description of the issue**
At several places the translator is used to get a translation for a message that should be logged or used as a message for an exception. This should be removed and plain Strings should be used for logging and exceptions.

Example:
 `LOG.debug(R("RFileReadOnly"));` or `LOG.debug(Translator.R("RFileReadOnly"));` should be refactored to  `LOG.debug("File is read only");`

**📋 Step by Step**
🙋 Claim this issue: Comment below.
🍴 fork the repository in github by simply clicking the 'fork' button.
⤵️ check out the forked repository
🔀 create a feature branch for the issue. We do not have any naming definition for branches.
💾 Commit your changes.
🔀 Start a Pull Request.
🏁 Done 👍 Ask in comments for a review :)
🔬 If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
💥 you did it! We will merge the fix in the master of the IcedTeaWeb project.
💐 Thanks, thanks, thanks for being part as an open source contributor for IcedTeaWeb
🤔❓ Questions

You can join our community [chat at Slack](http://adoptopenjdk.slack.com)

**Comment by aboyne** [comment]
I am interested in completing this task. I am new to open-source and am keen to get started.

**Comment by hendrikebbers** [comment]
Cool! Just ask if you need help :)

**Comment by aboyne** [comment]
I've forked the repository and will complete over the next few days. However I unable to add the label "In Progress" as requested by the "Step by Step" procedure. Is there something specific I need to do first?

**Comment by hendrikebbers** [comment]
My fault :) Will add the label later

**Comment by karianna** [comment]
I've moved it to the right stage.  @aboyne do you want to be added to the icedtea-web team?

**Comment by aboyne** [comment]
Thank you @karianna. Sure, I will not be super active, but I will try to contribute where I can.

**Comment by medoror** [comment]
@hendrikebbers Made a PR for this chanage
