### ISSUE TITLE
Windows shortcut don't handle properly filename with space

### ISSUE THREAD

**Issue by douph1** [AdoptOpenJDK/icedtea-web#165]
CacheUtil.clearCache(..)
look for jnlp path from args wich is broken down to two args when jnlp file name is:
test (1).jnlp
We must probably quote arg0 (jnlp file name) inside shortcut 
WindowsDesktopEntry.createWindowsMenu()
for two lines ShellLink.createLink ( run and clearcache )
with "test (1).jnlp" and strip double quote for compare inside CacheUtil.clearCache(..)

**Comment by douph1** [comment]
Run shortcut:
"C:\Program Files\IcedTeaWeb\WebStart\bin\javaws.exe" file:/C:/Users/adminup/Downloads/myjnlp (2).jnlp

Uninstall shortcut sample: 
"C:\Program Files\IcedTeaWeb\WebStart\bin\javaws.exe" -Xclearcache file:/C:/Users/adminup/Downloads/myjnlp (2).jnlp

**Comment by sclassen** [comment]
resolved with #180
