### ISSUE TITLE
future of javaws.jar

### ISSUE THREAD

**Issue by judovana** [AdoptOpenJDK/icedtea-web#168]
With the ITW now being split into into several modules, I'm wondering if assembled javaws.jar will be  part of the build. If so, then I would like to suggest optionally to no assembling external dependencies (like tagsoup or slf* or mslinks) 

I'm currently adapting the rust launchers (very slowly, time is again the enemy) to new structure, and had stumbled over the many jars from mvn  install being not convenient, and  in same, with wish to keep distributin build to use system jars of dependencies.

**Comment by hendrikebbers** [comment]
I think it is a good idea to have the modules and create separate jars out of it but I‘m fine with providing an assembled jar in addition. Does this has a high priority or can we wait until the big refactoring is done?

**Comment by judovana** [comment]
This have absolutely no priority, but will become important in time of your /our first release, as final jars will be hard to change yesterday. And itw should ship the same jars on all platforms/releases.
javaws.jar means comaptibility with oracle javaws. And as bugs "worsk with oracel, not on iTW" are most stupid ones, I would like to avid that. (except that fact, I 100% agree with having jar per module!!!)
I vote for javaws.jar being the single jar of ITW, but I will follow Yours release schema in linux  distributons  and "my" upstream release (if there will be some).  So it would be definitely good to agree on the approach.

The side effect of this issue is that assembly plugin do  not like to to not include external dependencies, so to maintain that, can be some unnecessary burden.  Thus openig this for discussion and other expereince:) TY!

**Comment by judovana** [comment]
> I think it is a good idea to have the modules and create separate jars out of it but I‘m fine with providing an assembled jar in addition. Does this has a high priority or can we wait until the big refactoring is done?

@hendrikebbers  According to this, karakun have no intentions to provide javaws.jar.  I had adapted the default launchers to not expect that.  Thanx! (please reopen if this change)
