### ISSUE TITLE
PolicyFileModel uses OS dependent character set for reading/writing files

### ISSUE THREAD

**Issue by sclassen** [AdoptOpenJDK/icedtea-web#191]
This can cause issues if policy files are shared between different OS with different default character sets.

It was first encountered by @ebourg with PR #189

**Comment by sclassen** [comment]
@judovana any thoughts on this issue?
My first approach would be to enforce using UTF-8 for both reading and writing.
But this might break compatibility with existing files written in a different charset.

**Comment by ebourg** [comment]
It looks like the reference implementation expects UTF-8 encoded files :

https://docs.oracle.com/javase/8/docs/technotes/guides/security/PolicyFiles.html

> In the Policy reference implementation, the policy can be specified within one or more policy configuration files. The configuration file(s) specify what permissions are allowed for code from a specified code source, and executed by a specified principal. Each configuration file must be encoded in UTF-8. 

I'll update my PR accordingly.
