### ISSUE TITLE
provide EMBEDDED implementation of ITW_LIBS

### ISSUE THREAD

**Issue by judovana** [AdoptOpenJDK/IcedTea-Web#196]
It will behave same as BUNDLED, but will slightly affect also JDK search path.
For rust launchers,  for both 1.8 and head

**Comment by karianna** [comment]
Set to 1.8.x milestone but needs to go on HEAD as well.

**Comment by karianna** [comment]
This is not a blocker for 1.8.1

**Comment by judovana** [comment]
@akashche @karianna  Where do you expect javaws will be placed in jre?

**Comment by judovana** [comment]
RH win installer have javaws in spearate folder JAVA_HOME/webstart...

**Comment by karianna** [comment]
> @akashche @karianna Where do you expect javaws will be placed in jre?

I'm really not sure.

**Comment by judovana** [comment]
Ok. We have to settle on this (feel free to bring it to wider adopOJDK - around jdk image distribution - audience)

I vote for {jre,jdk}/webstart and I will be searching for java via ../bin/java. Where symlink from bin/javaws to ../webstart. That will keep us aligned with RH windows images, which are already used and proved themselves. Thoughts?

**Comment by karianna** [comment]
> Ok. We have to settle on this (feel free to bring it to wider adopOJDK - around jdk image distribution - audience)
> 
> I vote for {jre,jdk}/webstart and I will be searching for java via ../bin/java. Where symlink from bin/javaws to ../webstart. That will keep us aligned with RH windows images, which are already used and proved themselves. Thoughts?

I think it working as it has under RH ITW is what users would expect.

**Comment by judovana** [comment]
Ok. Second question - how the adopt's jdk will handle the inclusion? It will download some ITW release, and unpack it into its image after the jdk build is done, or it will be building itw and including some snapshot? Will it be building it by itself or by boot jdk?

**Comment by douph1** [comment]
I can say how it works actually in beta/pre release stage : 

>It will download some ITW release, and unpack it into its image after the jdk build is done

no

> it will be building itw and including some snapshot

Actually we checkout a specified branch at HEAD.
Test job are configured to checkout branch "1.8".
We build it and create a zip wich is then integreted into AdoptOpenJdk installer ( unzip into JRE/JKD folder )
Then the AdoptOpenJdk installer is created (not publicy at this time)

>Will it be building it by itself or by boot jdk?

It seems we use bootk jdk as I see --with-jdk-home= in build job

**Comment by douph1** [comment]
and we are just waiting for this last issue https://github.com/AdoptOpenJDK/icedtea-web/issues/184 (tagged as 1.8 ) to be fixed/closed and your GO to build new installer with ITW bundled

**Comment by judovana** [comment]
I see. Thanx.  Then I will go with  ../bin/java search and you will have to go with (will be new) EMBEDDED configure switch, I'm currently sick, but will do a pathc once  I'm able to focus to programming.

**Comment by douph1** [comment]
Acutally after unpacking itw zip file into installer workspace there seems to be copy task.
Bin from zip files are copied into "bin" folder from JRE/JDK on final install ( as Oracle )

See what is installed in the final computer users:

javaws.exe
itweb-settings.exe
itw-modularjdk.args
policyeditor.exe
are put into C:\Program Files\AdoptOpenJDK\jre-8.0.202.08-hotspot\bin\

So if you search for ../bin/java from javaws.exe it will work for actual build
jre-8.0.202.08-hotspot\bin\..\bin\java.exe
and
new one if we change to "webstart" folder
jre-8.0.202.08-hotspot\webstart\..\bin\java.exe


See other files locations:
C:\Program Files\AdoptOpenJDK\jre-8.0.202.08-hotspot\icedtea-web-docs
C:\Program Files\AdoptOpenJDK\jre-8.0.202.08-hotspot\share\pixmaps
C:\Program Files\AdoptOpenJDK\jre-8.0.202.08-hotspot\share\icedtea-web\javaws.jar
...
C:\Program Files\AdoptOpenJDK\jre-8.0.202.08-hotspot\share\doc\icedtea-web\netx
..

C:\Program Files\AdoptOpenJDK\jre-8.0.202.08-hotspot\win-deps-runtime\js.jar
C:\Program Files\AdoptOpenJDK\jre-8.0.202.08-hotspot\win-deps-runtime\mslinks.jar
C:\Program Files\AdoptOpenJDK\jre-8.0.202.08-hotspot\win-deps-runtime\tagsoup.jar
C:\Program Files\AdoptOpenJDK\jre-8.0.202.08-hotspot\netx.src.zip
C:\Program Files\AdoptOpenJDK\jre-8.0.202.08-hotspot\plugin.src.zip

**Comment by judovana** [comment]
Hm. So you really wish to put javaws along side with java.exe? hmhmh. 
In 2.0 the libraries are no longer share nor itw-modularjdk.args are in bin (you cen set the path to them in configure already in 1.8, and I would advice you to do so, it do not belong to bin), they are all in "libs" (it cans till be changed)

Maybe we can go with 1.8 in this way, but for 2.0 to move itw to separate directory?
In linux, both cna coexist, as you can simply simlink the javaws from bin to its destined folder. On windows..:(

**Comment by judovana** [comment]
please see (and review and test):
1.8: https://github.com/AdoptOpenJDK/IcedTea-Web/pull/252
2.0: https://github.com/AdoptOpenJDK/IcedTea-Web/pull/253

**Comment by judovana** [comment]
It will work in both  jre/bin/javaws and jre/itw-image/bin/javaws

**Comment by judovana** [comment]
This is for native launchers only. I have no intentions to put this behaviour to shell launchers. Any opinion  on this intention?

**Comment by judovana** [comment]
pushed.
