### ISSUE TITLE
Setting cache folder in Windows failed

### ISSUE THREAD

**Issue by douph1** [AdoptOpenJDK/icedtea-web#198]
version 1.8

Graphical UI itweb-settings
"Debugging"  -> "File logs directory"

set
`D:/test/icedtea-web-image.1.8/log`
itweb-settings write:
`deployment.user.logdir=D\:/test/icedtea-web-image.1.8/log`

**then itweb-settings don't start** with exception:

D:\test\icedtea-web-image.1.8\bin>itw-rust-debug: checking deployment.log.file in: C:\Users\philippe doussot\.config\icedtea-web\deployment.properties
itw-rust-debug: located true in file C:\Users\philippe doussot\.config\icedtea-web\deployment.properties
itw-rust-debug: checking deployment.log.stdstreams in: C:\Users\philippe doussot\.config\icedtea-web\deployment.properties
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.log.stdstreams in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.log.stdstreams in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.log.stdstreams in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.log.system in: C:\Users\philippe doussot\.config\icedtea-web\deployment.properties
itw-rust-debug: located false in file C:\Users\philippe doussot\.config\icedtea-web\deployment.properties
itw-rust-debug: checking deployment.user.logdir in: C:\Users\philippe doussot\.config\icedtea-web\deployment.properties
itw-rust-debug: located D\:/test/icedtea-web-image.1.8/log in file C:\Users\philippe doussot\.config\icedtea-web\deployment.properties
D:\test\icedtea-web-image.1.8\bin\itweb-settings.exe
thread 'main' panicked at 'failed to create file log: Os { code: 123, kind: Other, message: "La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte." }', src\libcore\result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

If set with Windows separator :

`D:\test\icedtea-web-image.1.8\log`
get
`deployment.user.logdir=D\:\\test\\icedtea-web-image.1.8\\log`
and get same error

It seems the bug is to protect colon : \:

**Comment by douph1** [comment]
dont affect futur release (1.8.x) branch 1.8 build at commit 77e8d3cf39c4e72c8ae492307c0b10076431f61f

**Comment by douph1** [comment]
1.8.1pre OK:
itw-rust-debug: checking deployment.user.logdir in: C:\Users\philippe doussot\.config\icedtea-web\deployment.properties
itw-rust-debug: located D:\\test\\icedtea-web-image.1.8\\log in file C:\Users\philippe doussot\.config\icedtea-web\deployment.properties

**Comment by jagadeesanvol** [comment]
I am facing same issue as setting log folder for application.
deployment.user.logdir=C\:\\Users\\<sysname>\\Downloads\\icedtea-web-1.8.3.win.bin\\icedtea-web-image\\log
application is launching perfectly.I am not able to see my client log.
version:icedtea-web-1.8.3.win.bin
please help me this.

**Comment by sclassen** [comment]
Make sure to correctly escape special chars:

`deployment.user.logdir=c:\\temp\\logs` or `deployment.user.logdir=c\:/temp/logs`
