### ISSUE TITLE
Feature Request for Configurability of STDOUT Handling

### ISSUE THREAD

**Issue by martinhickson** [AdoptOpenJDK/IcedTea-Web#217]
IcedTea-Web version: 1.8
Java version:  AdoptOpenJDK 11.0.3.7-hotspot on Windows 10

Between versions 1.8pre2 and 1.8, there was a change in the STDOUT handling of the Rust code relating to the parent process.  This has caused problems for our application as it writes to STDOUT and the buffer size when launching javaws from either the browser or Windows Explorer appears to be limited which causes the app to freeze (thread writing to STDOUT waits forever).  It works fine when javaws is launched from the command line.  Could you please add a checkbox to the IcedTea-Web settings app that would provide the 1.8pre2 behaviour?  The following commit is the relevant one:

[Commit 642aea9f140d7c14ce874e5bd9dfc99bcf14e073](https://github.com/AdoptOpenJDK/icedtea-web/commit/642aea9f140d7c14ce874e5bd9dfc99bcf14e073)

**Comment by judovana** [comment]
hi! Icedtea-web controlpanel - the itweb-settings, have checkbox for log into stdouts. which is by default checked.
It results to deployment.log.stdstreams=false in deployment.properties.   Rus launchers understands that. Do yoiu mind to try? Is that an option for you?

**Comment by judovana** [comment]
once unchecked,..It results to deployment.log.stdstreams=false in deployment.properties. Rust native  launchers (default in 1.8)  understands that. Do yoiu mind to try? Is that an option for you?

**Comment by martinhickson** [comment]
Thank you for pointing that option out.  I have tried it and it helps with the IcedTea-Web console window in that the buttons no longer become unresponsive, however it doesn't help with our application itself since internally it is still writing to STDOUT, which I think is filling up the buffer of the parent process, whereas for 1.8pre2, it was working fine.  Perhaps the Rust launcher could redirect STDOUT to the Windows equivalent of /dev/null and this could be configurable as an additional checkbox in the settings app.

**Comment by judovana** [comment]
I see.   Yes. in terminal-less output itw really should do this.  However, I'm wondering, that ITW  - on java side -  is using all streams (its own and application's ) in controlled way. s the "garbage"  is flowing from your java app, then the switch which is disbaling stdouts/err in java is not doing its job fully - it is obviously only sillenting ITW. I will double check this.

**Comment by martinhickson** [comment]
Excellent, thank you.  Let me know your findings.

**Comment by martinhickson** [comment]
I have noticed that the 1.8.1 release seems to be imminent.  Would it be possible to please have the 1.8pre2 STDOUT behaviour back temporarily for the 1.8.1 release?  (i.e. temporary reversal of commit ID mentioned in the first comment).   This would make it possible for us to upgrade rather than remain on 1.8pre2.

**Comment by martinhickson** [comment]
Perhaps something like this would do the trick in os_access.rs:

```rust
fn spawn_java_process(os: &Os, jre_dir: &std::path::PathBuf, args: &Vec<String>) -> std::process::Child {
    let mut cmd = create_java_cmd(os, jre_dir, args);
    cmd.stdin(std::process::Stdio::inherit());
    if os.inside_console() {
        cmd.stdout(std::process::Stdio::inherit());
        cmd.stderr(std::process::Stdio::inherit());
    } else {
        cmd.stdout(std::process::Stdio::null());
        cmd.stderr(std::process::Stdio::null());
    }
    let res = cmd.spawn();
    match res {
        Ok(child) => child,
        Err(_) => panic!("Error spawning JVM process, \
                 java executable: [{}], arguments: [{:?}]", jre_dir.clone().into_os_string().to_str().expect("path should unwrap"), args)
    }
}
```

**Comment by judovana** [comment]
https://github.com/AdoptOpenJDK/IcedTea-Web/pull/276 should make this rare issue to be opted out - by disabling logging into streams (when console is enabled[default is yes]) thoughts?

**Comment by karianna** [comment]
@judovana Do you think this is this a critical fix for 1.8.x or OK just for master (2.0.x)?

**Comment by judovana** [comment]
nope, that must go to1.8. It is causing a set of aplications on windows die. Will preapre backport asap

**Comment by judovana** [comment]
@martinhickson  are you willing to test it, if it really fixed your issue?

**Comment by douph1** [comment]
@judovana You say "on windows"
This bug don't affecter other OS ?
I use itw 1.8 (rust exe) on linux and have similar effect : freeze when console is enable and when I launche javaws two times

**Comment by karianna** [comment]
> nope, that must go to1.8. It is causing a set of aplications on windows die. Will preapre backport asap

great thanks

**Comment by judovana** [comment]
hm. @douph1  it do not sound like the same issue..

Your issue is broken awt  thread, which is known issue of jdk11. It should be ok in jdk8 and 12. To fix it in ITW itself is possible security hole. See This thread :mail.openjdk.java.net/pipermail/distro-pkg-dev/2018-September/040098.html   Is very long, spawn over several months.

**Comment by judovana** [comment]
http://mail.openjdk.java.net/pipermail/distro-pkg-dev/2018-September/040098.html

**Comment by douph1** [comment]
Ok thanks, I knowing it is already fix and backported in java 11  : https://bugs.openjdk.java.net/browse/JDK-8204142
-> 
JDK-8221678 | 11.0.2 | Martin Balao | P3 | Closed | Fixed | b32 -> https://bugs.openjdk.java.net/browse/JDK-8221678

(Maybe you can add this info (this is fixed in new build) into https://icedtea.classpath.org/wiki/IcedTea-Web -> EDT on JDK 11 is broken)

My fault, sorry, I have used a older build : 11.0.2+9 and if 9 is the build number it is less than b32

Upgrading to latest ubuntu 11.0.3+7-1ubuntu2~18.04.1 fix the issue on linux.
Thanks

**Comment by judovana** [comment]
Great to hear! LAst time I checked the jdk11 backport, it was no go for 11 and older!

**Comment by judovana** [comment]
@martinhickson  https://github.com/AdoptOpenJDK/IcedTea-Web/pull/281 here we have 1.8 backport

**Comment by martinhickson** [comment]
Thank you all.
