### ISSUE TITLE
Properties are not correctly set from jnlp (e.g. file.encoding)

### ISSUE THREAD

**Issue by AlBundy33** [AdoptOpenJDK/IcedTea-Web#222]
In our application we need utf-8 as file-encoding.
Therefore our jnlp contains `<property name="file.encoding" value="UTF-8" />`

This works as expectd with oracles javaws.

With IcedTea-Web on windows (downloaded latest version from http://icedtea.wildebeest.org/download/icedtea-web-binaries/) it seems that the file.encoding is not set because our german special characters (ä, ö, ü, ...) are not displayed correctly.

Tested with openjdk https://github.com/ojdkbuild/ojdkbuild/releases/tag/1.8.0.212-1

**Comment by judovana** [comment]
I'm afraid all readers in ITW must be revisited and used encodings verified

**Comment by AlBundy33** [comment]
For me it seems that the file.encoding property is not passed correctly to the application start of our app.

As far as I know oracles javaws starts a new jvm on some circumstances.
Afaik a restart is done if the jnlp is signed - maybe this was done for such global properties.

**Comment by judovana** [comment]
hmm. This is interesting idea. ITW does spawn new jvm if its needs (eg xmx or similar in jnlp). To spawn it because encoding is IMHO not there. Worthy to try.
https://github.com/AdoptOpenJDK/icedtea-web/blob/master/core/src/main/java/net/sourceforge/jnlp/JNLPFile.java#L907
https://github.com/AdoptOpenJDK/icedtea-web/blob/master/core/src/main/java/net/sourceforge/jnlp/Launcher.java#L531

**Comment by AlBundy33** [comment]
According to the linked files I would assume that a relaunch is done because our j2se-tags looks like this
```
  <resources os="Windows" arch="x86_64">
    <j2se version="1.6+" java-vm-args="-XX:MaxPermSize=256m -Xms40m -Xmx512m" />
    <jar href="plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.200.v20120913-144807.jar" size="30111" />
    <jar href="plugins/org.eclipse.swt.win32.win32.x86_64_3.8.1.v3836b.jar" size="2721123" />
  </resources>
```
So jre.getVMArgs() should not be empty.

Can you describe how to build ITW from git?
Then I could add some debug output and see what is done and passed to our application.

**Comment by AlBundy33** [comment]
Build seems to be easy
clone git repo and just run mvn package
On windows I have to set -DskipTests because some tests are failing

**Comment by sclassen** [comment]
windows tests should all be fixed on master now

**Comment by AlBundy33** [comment]
Is there any nightly-download to test this?

**Comment by sclassen** [comment]
No, there are currently no nightly builds.
