### ISSUE TITLE
please fix or remove 1.7 branch

### ISSUE THREAD

**Issue by judovana** [AdoptOpenJDK/IcedTea-Web#259]
1.7 branch is still broken (I had pinged the originator of repo several times). It is few haundrets commits behind http://icedtea.classpath.org/hg/release/icedtea-web-1.7/ (it shoudl be on http://icedtea.classpath.org/hg/release/icedtea-web-1.7/rev/cf64d3bb2917 , is on http://icedtea.classpath.org/hg/release/icedtea-web-1.7/rev/e543b472fd2c (22monhts ago))
I doubt there will be any release of 1.7 ever in future, so please remove the branch or fix it.

**Comment by sclassen** [comment]
@judovana you have enough rights to delete the branch yourself

**Comment by judovana** [comment]
Sclassen, yes. But I would rather make it correct. And The guy wha was porting that did great job when ported master and 1.8, so I would rather let him to fix it, or to delet it, and to to touch his work unless it is necessary.

**Comment by judovana** [comment]
That was Adopt's gyu, Martinj, can you ping him please?

**Comment by sclassen** [comment]
I did some of the porting from mercurial to git.
Do you mean that there is content missing from http://icedtea.classpath.org/hg/release/icedtea-web-1.7/
Initially there was a PR open for this content, but it was never merged (#18)

**Comment by judovana** [comment]
Ok. So it looks like I'm the guilty one here. Can you please revive this pr and merge it?

**Comment by judovana** [comment]
thank you.
