### ISSUE TITLE
Can you provide a portable JAR file to execute JNLP file?

### ISSUE THREAD

**Issue by PredragBoksic** [AdoptOpenJDK/IcedTea-Web#261]
Example:

`java -jar portable-runner.jar  my.jnlp`

Perhaps someone can suggest an adequate class/method in the source code where to begin the work on the portable version.  Thanks.

**Comment by sclassen** [comment]
I think you are looking for the class `Boot`.
If you checkout the project you can run your jnlp from within an IDE
`Boot -jnlp my.jnlp -nosecurity -Xnofork`

**Comment by PredragBoksic** [comment]
Thank you very much. I was able to build the project in IntelliJIdea and run a JNLP file by using the main method in net.sourceforge.jnlp.runtime.Boot class, with parameters you've given me -jnlp my.jnlp -nosecurity -Xnofork. 

Interestingly, the Boot class method of execution runs well with AdoptOpenJDK 8, 11, and 12 (but not 13). This method probably bypasses the bug in JDK 11 that otherwise freezes the Swing windows of ITW during the conventional loading with javaws.bat.
