### ISSUE TITLE
Unnecessary check of JNLP file sourceLocation

### ISSUE THREAD

**Issue by SchwingSK** [AdoptOpenJDK/IcedTea-Web#265]
During launch, the JNLP file sourceLocation is added to the URLs to be checked against the codebase URL. If it isn't relative to the codebase (provided issue #256 is resolved), then a warning dialog is displayed:
![image](https://user-images.githubusercontent.com/2040238/58387256-29289880-800c-11e9-8f12-012c70c356da.png)

In particular, this happens (as shown above) when the jnlp file is downloaded via the browser then passed to the javaws client.
This behavior is not the same as in Oracle Web Start, which did not show any warning.
This looks like a bug, as the JNLP specification, section 6.6 goes like this:
"Application descriptors, i.e., JNLP files, are handled specially, since they are not necessarily downloaded by the JNLPClient itself. Often, they will be downloaded by a Web browser or by other means."

**Comment by SchwingSK** [comment]
Finally got some time to investigate further:
this only happens when:

1. the jnlp tag does not have the (facultative) href attribute. 
2. the jnlp file is loaded from a file (as is the case when using a web browser)

 This leads to JNLPFile setting the sourceLocation to the location of the file on disk, and not the actual source location of the jnlp file (as this can only be inferred if we have both the codebase **and** href attributes).
Created a pull request (#294) that fixes the issue.

**Comment by karianna** [comment]
@SchwingSK FYI - If you want this fixed for the 1.8.x line you'll also have to create a backport PR to the 1.8.x branch.

**Comment by SchwingSK** [comment]
@karianna it's in the works, should appear tomorrow if all goes well.

**Comment by SchwingSK** [comment]
Finally got the time to create the PR for the 1.8 branch. Sorry for the delay.

**Comment by SchwingSK** [comment]
Hi, sorry about the enormous delay, but priorities got in the way at work. I've seen that my original fix created more problems than it solved and commits were reverted (see #372), sorry about that.
So I went with a different approach this time. Don't know if I should open a new issue, tell me if I should. 

The idea for the new patch (#777) is that The JNLP file URL should not be added to the list of URLs to be checked against the codebase if the JNLP File URL is local (i.e. uses the file protocol). It doesn't change the behavior for location/sourceLocation as this was most likely the source of unwanted side effects.

I also tested the patch with a JNLP that doesn't have a codebase and had no problems with this new patch. Let me know if you detect problems, I'll try to address them.

**Comment by SchwingSK** [comment]
@sclassen Sorry to bother you, but as you seem to monitor new issues, do you think I should open a new issue rather than comment on this one?

**Comment by sclassen** [comment]
There is a flag in the ITW settings (for the 2.0.0 alphas) which allows to set "Assume local files belong to codebase"

Does this solve your issue?
You can try this in OpenWebStart which is based on the 2.0.0 alpha releases.

**Comment by SchwingSK** [comment]
I saw this flag, however I think that IcedTeaWeb should behave like JavaWebStart in this regard, especially given the specification:
The JNLP specification, section 6.6 goes like this:
"Application descriptors, i.e., JNLP files, are handled specially, since they are not necessarily downloaded by the JNLPClient itself. Often, they will be downloaded by a Web browser or by other means."
So I think this warning should not exist for JNLP files.

**Comment by SchwingSK** [comment]
@sclassen have you had time to look into this ?

**Comment by sclassen** [comment]
sorry very busy today. But we will give it our best effort to get this in before the next release

**Comment by SchwingSK** [comment]
No problem, glad it's being considered for the next release!
