### ISSUE TITLE
Saving of config without pressing "Apply" or "OK"

### ISSUE THREAD

**Issue by sclassen** [AdoptOpenJDK/IcedTea-Web#270]
I noticed that sometimes the config is saved to the file system without me pressing any of the "OK" or "Apply" buttons in the control panel.

Digging into the code I found the following in the class `UnsignedAppletsTrustingListPanel`:
```
    private void mainPolicyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            conf.setProperty(ConfigurationConstants.KEY_SECURITY_LEVEL, ((AppletSecurityLevel) mainPolicyComboBox.getSelectedItem()).toChars());
            conf.save();
        } catch (Exception ex) {
            LOG.error(IcedTeaWebConstants.DEFAULT_ERROR_MESSAGE, ex);
            JOptionPane.showMessageDialog(this, ex);
        }
    }
```
When changing the value of the combo box the entire configuration is saved to the file system.

Is this intended behavior or not?

**Comment by AndreasEhret** [comment]
as the rest of the dialog's comboboxes do follow the ok/apply/cancel pattern this looks like a bug to me. Saving the entire config when main policy changes makes "cancel" not work any longer, therefore we should remove save on selection changed as proposed.
