### ISSUE TITLE
Validate config before saving

### ISSUE THREAD

**Issue by sclassen** [AdoptOpenJDK/IcedTea-Web#272]
Currently the config is saved even with invalid values.
Add a validation step before the actual saving to allow the user to correct the config.

See TODOs in class `ControlPanel`

**Comment by judovana** [comment]
Can invalid confix be saved via current control panel? The gui is validating a lot. On contrary, some abilty to work with incorrect values may stay desired

**Comment by sclassen** [comment]
Current master has the validation on save disabled. Therefore settings can be saved at any time.
This issue is for clarifying how the correct behavior should be.
