### ISSUE TITLE
installer-desc   of jnlp specification is not implemented

### ISSUE THREAD

**Issue by judovana** [AdoptOpenJDK/IcedTea-Web#283]
Thanks for the reply. Our JNLP looks like this:

main.jnlp

    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <jnlp codebase="http://falcon:8888/" href="jnlp/test.jnlp" spec="1.0+" version="">
        <information>
            <title>default</title>
            <vendor>default</vendor>
            <description kind="short">default</description>
            <shortcut online="true">
                <desktop/>
            </shortcut>
        </information>
        <security>
            <all-permissions/>
        </security>
        <update check="always"/>
        <resources>
        ... a bunch of jars ...
        </resources>
        <resources>
            <extension href="jnlp/installer.jnlp" name="Certificate Authority Installer">
                <ext-download download="lazy" ext-part="main"/>
            </extension>
        </resources>
        <application-desc main-class="com.wibble.WSLauncher">
        </application-desc>
    </jnlp>

installer.jnlp

    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <jnlp codebase="http://falcon:8888/" href="http://falcon:8888/test/installer.jnlp" spec="1.0+" version="">
        <information>
            <title>Install Certificate Authority</title>
            <vendor>Me</vendor>
            <description>Installs the certificate authority</description>
            <description kind="tooltip">Install CA</description>
            <description kind="short">Installs the certificate authority</description>
            <description kind="one-line">Installs the certificate authority</description>
            <offline-allowed/>
        </information>
        <resources>
            <j2se href="http://java.sun.com/products/autodl/j2se" version="1.7.0+"/>
            <jar download="lazy" href="test/Installer.jar" part="bootstrap"/>
        </resources>
        <security>
            <all-permissions/>
        </security>
        <installer-desc main-class="com.wibble.Installer"/>
        <update check="always" policy="always"/>
    </jnlp>

    If I remove the extension from main.jnlp then the application runs up to a point but we receive application errors due to the missing certificate (specifically javax.net.ssl.SSLException: java.lang.NullPointerException: Code source security was null).

    As an experiment I tried to run the installer.jar and this is where I saw the error message:

    Fatal: Unsupported Feature: Installers are not supported. JNLP installer files are not yet supported.

    Any assistance will be greatly appreciated.
Best regards,

Richard Stollar
On 01/10/18 12:03, Jiri Vanek wrote:
> Hello!
>
> adding distro-pkg-dev meioing list as main discussions about ITW happens here.
>
> On 9/28/18 11:48 AM, Richard Stollar wrote:
>> Hello Jiri,
>>
>>      I am involved in a project that has until now relied upon WebStart which as you will know has been removed in Java 11. To solve our problems we are testing with IcedTea-Web as it looks quite promising.
>
> Should be. We had tried hard.
>>
>>      Our problem lies in the fact that we use an extension JNLP embedded in our main JNLP(s) and that is not currently supported in ITW-1.7. Is there a roadmap for 1.8 which, according to the WIKI page, should include shared launchers.  Is this functionality in a development release?
>
>
> I doubt. 1.8 should bring new native launchers, to avoid duplicated codebase for MS and Linux. Also to fix many persiting issues we have with shell (well, mostly bat) lunchers.
>
> Unless what you descibe, works on linux, but not on Win, than it is not on roadmap. Still I have nothing against implementing it for both 1.8. and 1.7 (unless it have some side effects).
>
> Do you mind to elaborate more what you need? If you can add support, even better. If somebody else should, can you prepare minimalistic reproducer?
>
> However.. I think extensions are in some ways already supported.  So maybe issue si somewhere else?
>
> HTH
>  J.

**Comment by sclassen** [comment]
There are currently no plans to support installer-desc in 2.0.0
