### ISSUE TITLE
This is correct behavior. You use one VM to load jnlp, and here you find that xmx is desired. So you invoke new VM, where xmx is passed in, and that one is launching the final app.

### ISSUE THREAD

**Issue by maru-sama** [AdoptOpenJDK/IcedTea-Web#284]
This is most likely the same as ticket #273. The jnlp file I that is used in my case requires the start of a second VM. According to the console the second VM hangs at the following stage right after start.

java.io.IOException: Cant create file C:\Users\<username>\.config\icedtea-web\security\trusted.certs.temp
............................

If I then kill the first process the second one continues to load just fine.

According to the comment in the original ticket starting a second VM is intended behaviour but in my case it hangs.

__________________________
This is correct behavior. You use one VM to load jnlp, and here you find that xmx is desired. So you invoke new VM, where xmx is passed in, and that one is launching the final app.

_Originally posted by @judovana in https://github.com/AdoptOpenJDK/IcedTea-Web/issues/273#issuecomment-499493061_

**Comment by judovana** [comment]
lets continue in original thread.
