### ISSUE TITLE
Web-integration-tests fails on windows

### ISSUE THREAD

**Issue by lherschi** [AdoptOpenJDK/IcedTea-Web#286]
ManagedApplicationStartedTest.testSuccessfullyLaunchSimpleJavaApplication(),
ManagedApplicationSystemEnvironmentTest.testReadingSystemEnvironment(),
JvmArgumentsPassedTest.testLaunchWithProgramArguments(),
SplashScreenIconTest.testSplashIcon() and
SystemPropertiesSetTest.testLaunchWithSystemProperty()

fails all with the same exception:
com.github.tomakehurst.wiremock.client.VerificationException: 
45 requests were unmatched by any stub mapping

By calling Boot.main(args) in Windows an instance of class WindowsDesktopEntry is created. WindowsDesktopEntry calls XDesktopEntry(file).cacheAndGetIconLocation() in the constructor. This in turn causes the call to XDesktopEntry.cacheIcon(). In cacheIcon() we try to get favicon.ico via http GET. This GET ensures that the test fails.

**Comment by sclassen** [comment]
You are right, windows behaves differently than linux and causes the tests to faile
