### ISSUE TITLE
rust launchers for mac

### ISSUE THREAD

**Issue by judovana** [AdoptOpenJDK/IcedTea-Web#289]
hi adopt!  Are you able to create native itw bits for mac?

**Comment by karianna** [comment]
@judovana for which branch...?

**Comment by judovana** [comment]
both 2.0 and 1.8 if possiible?

**Comment by gdams** [comment]
if the source code for ITW compiles on mac then we can deffo build it.

**Comment by judovana** [comment]
Java does for sure, and rust exists for Mac. So it should work.

**Comment by gdams** [comment]
@judovana I'm looping back round to this to try and get ITW 1.8 compiling on macOS. Do you know what dependencies are required? Have you ever successfully compiled on macOS yourself?

**Comment by gdams** [comment]
When I try to configure I just reach this:

```bash
checking where to place file with modular switches... ${exec_prefix}/bin
checking whether build legacy shell launchers... no
checking for rustc... /usr/local/bin/rustc
checking for cargo... /usr/local/bin/cargo
configure: error: "OS darwin20.3.0 is not supported"
```
