### ISSUE TITLE
Proxy auto config is broken

### ISSUE THREAD

**Issue by AndreasEhret** [AdoptOpenJDK/IcedTea-Web#303]
in 2.0 proxy auto config is broken as build.properties including rhino.available property setting is missing but looked up in PacEvaluatorFactory. Therefore we end up in FakePacEvaluator instead of RhinoBasedPacEvaluator with "Using Proxy Auto Config (PAC) files is not supported." on the console.

**Comment by AndreasEhret** [comment]
We have to ensure that build.properties exists and rhino.available is set properly. need to provide a substitute what has been done in 1.8 by Makefile.am, configure.ac and acinclude.m4 to check rhino jar existence/dependency and copy to build.properties. In 2.0 rhino maven dependency is checked in maven build.

**Comment by unbekannt3DE** [comment]
For me PAC is also broken with RedHat OpenJDK build 1.8.0_212-3-redhat on both Win 7 x64 and 10 x64 platforms (included prebuilt IcedTea):

![grafik](https://user-images.githubusercontent.com/10979501/60869177-c3e0dd80-a22e-11e9-9833-9fe84b7fe08c.png)

When i start a jnlp file it also says that the PAC provider is broken or don't exists:
![grafik](https://user-images.githubusercontent.com/10979501/60869677-b11ad880-a22f-11e9-945b-76ff62726f51.png)
