### ISSUE TITLE
Building launchers on Windows

### ISSUE THREAD

**Issue by daddyaddy** [AdoptOpenJDK/IcedTea-Web#313]
We can not build the build.sh file by Linux bash (installed on Windows 10) because we have a Java version for Windows.

How to build launchers for Windows?

**Comment by Sam1970** [comment]
Hi,

you can using Alex Kashchenko Dev-Kit and uninstall java on Windows 10:
https://github.com/akashche/itw_win_devkit

regards

**Comment by lherschi** [comment]
This Dev-Kit uses the old mercurial repository and is therefore obsolete. You net to set the environment variable JRE to your Java runtime (your Windows drives should be automatically be mounted under /mnt) an then run mvn -Plaunchers install. But in the current master the build does not work. See https://github.com/AdoptOpenJDK/IcedTea-Web/pull/306

**Comment by hendrikebbers** [comment]
@daddyaddy you can download a preview here www.openwebstart.com

**Comment by judovana** [comment]
The build environment for launchers - both rust and shell - are build in cygwin. I was never trying other apporaches.

**Comment by judovana** [comment]
@daddyaddy  @lherschi  is the current build working for you?  I had revisited it, and fixed few bugs. However, it is still depndent on cygwin. I belive, it will require only small chages to make it alive under linux subsystem for windows. Morover only get rid of cygoath, which is use donly on two places. Thoughts?

**Comment by lherschi** [comment]
Yes, the current build works for me.
