### ISSUE TITLE
 Problem with executing javaws command with url parameter

### ISSUE THREAD

**Issue by daddyaddy** [AdoptOpenJDK/IcedTea-Web#314]
We want to run a file with the .jnlp extension in two ways:
1) **The .jnlp file saved on the disk** (downloaded from our website and inserted into the OpenWebStart folder) we want to start with the command:
`javaws --nosecurity file.jnlp`

And our application is running properly.

2) **We want to run the same file directly from the URL**:
```
javaws -nosecurity 'jnlps://localhost/adminDEV/applet/webstartBrowser.jnlp?codeBase=https%3A%2F%2Flocalhost%2FadminDEV%2Fapplet&url=https%3A%2F%2Flocalhost%2Fcgi-bin%2FCliniNET.prd%2FStart.pl%3Fsession%3Dad7
dd07f18e6a7890f612f61569c6b37f38de215%26Module%3DAdmin%26Sub%3D%26auth_windowName%3DAdmin_CliniNETdev_localhost_443%26ComputerPostID%3D%26ComputerPostName%3D%26auth_orgunit%3D%26auth_orgunit_name%3D%26ComputerLocationID%3D%26ComputerLoca
tionMappedID%3D%26ComputerLocationCode%3D%26ComputerLocationName%3D%26skinName%3Dsimple&hideAddressBar=true' -console
```

And we get the following error:

> 'url' is not recognized as an internal or external command,
> operable program or batch file.
> 'hideAddressBar' is not recognized as an internal or external command,
> operable program or batch file.

**Comment by rafik777** [comment]
I think, the problem is with wrong quoted argument for javaws.
& should by quoted as ^&
according to https://stackoverflow.com/questions/1327431/how-do-i-escape-ampersands-in-batch-files

**Comment by daddyaddy** [comment]
Thanks man! ;)
