### ISSUE TITLE
ICW 1.8.2 Policy Editor creates empty policy file

### ISSUE THREAD

**Issue by fishon-dev** [AdoptOpenJDK/IcedTea-Web#329]
Hello, When I open policy editor by right clicking and selecting "Run as Administrator" in Windows 10 Pro, select all permissions for "all applets", click Apply, and save the policy file a blank file is created with the name I gave it. When I then want to open the file by going to File->Open I get an error "Unable to open policy file". I tried creating the file right in path where policyeditor.exe is and on desktop with same result.

**Comment by worryboy** [comment]
Hi hwo ist teh status of this bug ? It blocks our current ussage.

**Comment by sclassen** [comment]
Sorry no progress. There is currently nobody fixing 1.8 issues

**Comment by worryboy** [comment]
hi .. thx and bad news.. 

sugestions ? workaround ?

**Comment by sclassen** [comment]
Is your applet run in a browser or do you start it from an jnlp file?

If the later is the case you can simply give all-permissions in the jnlp file
