### ISSUE TITLE
Build icedtea-web nightlies 

### ISSUE THREAD

**Issue by maru-sama** [AdoptOpenJDK/IcedTea-Web#330]
Hello,

To be able to test fixes with icedtea-web I kindly ask to create nightly builds there as well. As far as I understand right now only release builds are configured. 

Thank you very much in advance,
Michael

**Comment by judovana** [comment]
+1 would be awesome.

**Comment by SchwingSK** [comment]
+1 Indeed it would be nice, especially for the 1.8 branch which is quite a pain to build.

**Comment by sclassen** [comment]
There is now a Github action build for the 1.8 branch
https://github.com/AdoptOpenJDK/IcedTea-Web/blob/1.8/.github/workflows/build.yml

**Comment by SchwingSK** [comment]
@sclassen is there a plan for providing a GitHub action, but for the Windows builds?

**Comment by sclassen** [comment]
https://github.com/AdoptOpenJDK/IcedTea-Web/blob/master/.github/workflows/maven.yml

**Comment by sclassen** [comment]
or do you mean a build for windows?
And if so for master or for 1.8.x?

**Comment by SchwingSK** [comment]
Ideally, I mean all: give people an easy way to test the latest snapshots for both Linux & Windows, on 2.0 & 1.8 branches.

**Comment by sclassen** [comment]
for 1.8 we are working on this.
Checkout the latest build in https://github.com/AdoptOpenJDK/IcedTea-Web/actions/workflows/build.yml

**Comment by SchwingSK** [comment]
That's exactly what I meant, great work! This has the added bonus of giving clear instructions on how to build 1.8 branch on Windows, thanks a lot for this.
