### ISSUE TITLE
Make generated docs accessible

### ISSUE THREAD

**Issue by judovana** [AdoptOpenJDK/IcedTea-Web#332]
...at least for releases. I can upload them to classpath if you wish.
The docs, when uplaoded, looks eg like:
http://icedtea.wildebeest.org/download/icedtea-web-docs/1.8/html/
and are in:
http://icedtea.wildebeest.org/download/icedtea-web-docs/

**Comment by judovana** [comment]
Its a bug. It was accessible for last thre years.   Unless the docs should be accessible from https://adoptopenjdk.net/ ; I  probably need agreement with adopt's build infra to  provide docs during build, and publish them as another release artifact, and I can publish them on classpath org.

**Comment by karianna** [comment]
> Its a bug. It was accessible for last thre years. Unless the docs should be accessible from https://adoptopenjdk.net/ ; I probably need agreement with adopt's build infra to provide docs during build, and publish them as another release artifact, and I can publish them on classpath org.

Can't see that being an issue - let us know in this ticket what you need.

**Comment by Jamila891** [comment]
@judovana should we add the static part as a MarkDown file to this repo?
