### ISSUE TITLE
provide back changelog into about dialog

### ISSUE THREAD

**Issue by judovana** [AdoptOpenJDK/IcedTea-Web#337]
only now will be  generated from git
The changelog, as part of about dialog had its charm. It would be nice to provide same functionality via git log.

**Comment by Jamila891** [comment]
@judovana we plan to provide release notes for icedTea-Web starting with the next release in Github. Today we only do it for OpenWebStart, but with the next release we will add all changes that are related to icedTea-Web to the Github Release of icedTea-Web.
