### ISSUE TITLE
JNLP application can't be launched if default cache path contains a space

### ISSUE THREAD

**Issue by garciarg** [AdoptOpenJDK/IcedTea-Web#339]
If the default path for the cache contains a space like below, application can't be launched and an error is displayed as shown in the second image.

<img width="392" alt="image" src="https://user-images.githubusercontent.com/53474312/62123452-8ab1ff80-b2fa-11e9-98d7-b7a335f79017.png">

![image](https://user-images.githubusercontent.com/53474312/62123534-b6cd8080-b2fa-11e9-9bc2-cb35a5b64bfc.png)

I have verified the issue multiple times. When I don't include a space in the path, it works fine but when a space is included, application can't be launched. This is a major issue for users that include their first and last names as usernames in their machines.

**Comment by douph1** [comment]
Hi, we probably need the same kind of fix that for #290 #197

**Comment by Sam1970** [comment]
Hi @garciarg,
open deployment.properties file and set "deployment.user.cachedir" path so:

`deployment.user.cachedir=C\:\\Romarr\\u0020Gracia`

The Problem is Java uses `\\u0020` for space.

Have fun

**Comment by lherschi** [comment]
Can be closed.
https://github.com/AdoptOpenJDK/IcedTea-Web/pull/508
