### ISSUE TITLE
Jar file can't be downloaded to cache folder

### ISSUE THREAD

**Issue by garciarg** [AdoptOpenJDK/IcedTea-Web#342]
Hi, we are getting error below when executing the application. It seems IcedTea-Web can't download the jar file to the cache folder (even without space in the path). The jar can be downloaded using the browser, it is just when executed using the JNLP file and IcedTea-Web that we are getting the error. 

(Fatal: Initialization Error: A fatal error occurred while trying to verify jars. An exception has been thrown in class JarCertVerifier. Being unable to read the cacerts or trusted.certs files could be a possible cause for this exception.: C:\cache\1\https\*****\**.jar (The system cannot find the file specified))

**Comment by douph1** [comment]
Can you try to set the acl/right to the specific user you are trying and not to a group on folder C:\cache ?
see :
https://github.com/AdoptOpenJDK/IcedTea-Web/issues/184#issuecomment-493107043

Also can you confirm the presence of many empty folder into c:\cache named 1, 2, 3, until 10 (retry) ?

**Comment by garciarg** [comment]
Yes those many empty folders are created in C:\cache, it's just the jar file that can't be saved there

**Comment by douph1** [comment]
Ok, I have see that the code who created this sub-folder in c:\cache copy/change acl.
Can you add ntfs full access to your current running Windows user ( not to a group like Administrators )  and see if it fix ther error ?

**Comment by douph1** [comment]
see https://github.com/AdoptOpenJDK/IcedTea-Web/blob/master/core/src/main/java/net/sourceforge/jnlp/util/FileUtils.java
Can you list/show us the ACL from C:\Cache and C:\Cache\1\ folder ?
The sub directory are probably missing owner acl because owner ( you ) have no acl on C:\Cache level

**Comment by garciarg** [comment]
Thanks for the suggestion! You are correct, when we added the specific user and set the permissions manually, we got the application to work. So this will be fixed in the 2.0 release, right?

**Comment by judovana** [comment]
Maybe you can fix it? I have no way to test any ACL fixes, as  I do not have windows around. Sorry.

How did even cache appeared on c:/cache? You haad to set it on your own, have't you? Then maybe the ACL is creators responsibility?

**Comment by martinhickson** [comment]
If you have time for a question about this, in a multi-user scenario, with multiple users sharing a centralized cache location (i.e. a scenario like Citrix), does that mean that all users who will use the JNLP application have to appear in the ACL list of C:/cache?

**Comment by sclassen** [comment]
sharing the cache may lead to some corner-cases and race conditions.
If you are interested in such scenario please contact us at openwebstart@karakun.com
