### ISSUE TITLE
"fix(JNLPFile): location/sourceLocation confusion" is causing defautl codebase not to be found

### ISSUE THREAD

**Issue by judovana** [AdoptOpenJDK/IcedTea-Web#372]
Hello! 
 Merge pull request #294 from SchwingSK/issue-265  fix(JNLPFile): location/sourceLocation confusion
https://github.com/AdoptOpenJDK/IcedTea-Web/commit/b6384b0907799572b8f78883d00c128f39673fd4

Caused that  codebase="." is enforced top make app running. if codebase element is missing,  then the default codebase is no longer used. Oracle javaws is not enforcing "." so ITW hsould also not enforce it. Thoughts?

**Comment by judovana** [comment]
@sclassen  Hi! Any idea on this? I'm inclining to direct revert. Codebase sometime is misleading, however is necessary and oralce javaws keeps fallbacking where possible.

**Comment by judovana** [comment]
@sclassen  ping please? Are you ok with me to PR revert?

**Comment by sclassen** [comment]
I look into it tomorrow

**Comment by sclassen** [comment]
I'm giving up to understand why the changes break the code.
Go ahead and revert. Maybe you can save the tests...

**Comment by judovana** [comment]
ok. Will add the testcase and do PR with revert. TY!

**Comment by sclassen** [comment]
We just hit the same spot with a JNLP having a codebase defined. Looks like this causes more trouble than I assumed.
