### ISSUE TITLE
Fix for Packed resources are stored in cache with double file extension (#12)  had broken phetsims

### ISSUE THREAD

**Issue by judovana** [AdoptOpenJDK/IcedTea-Web#374]
commit of https://github.com/AdoptOpenJDK/IcedTea-Web/commit/3f08fb429347209a8d7d8f2dde (from #12) had broken  http://phetsims.colorado.edu/sims/circuit-construction-kit/circuit-construction-kit-dc_en.jnlp

**Comment by judovana** [comment]
@lherschi  thoughts?

**Comment by sclassen** [comment]
link to #12

**Comment by judovana** [comment]
My suspicion is,  that the pack.gz can be used without proper suffix.  Then the file is saved as  simple jar, although is not. As it have now missing suffix, itw no longer recognize it as pack.gz and do not ucompress

**Comment by judovana** [comment]
or even do not download it.

**Comment by judovana** [comment]
Ore better, rewrite itself:

Thu Aug 22 14:55:16 CEST 2019 [DEBUG  ] net.sourceforge.jnlp.cache.ResourceDownloader: Extracting packgz: https://phet.colorado.edu/sims/circuit-construction-kit/circuit-construction-kit_all.jar to https://phet.colorado.edu/sims/circuit-construction-kit/circuit-construction-kit_all.jar

Thuis owerwriting itself during unpacking.

**Comment by sclassen** [comment]
should work on unix system, but will kill the file on windows :rofl:

**Comment by judovana** [comment]
Do not work even on linux. It ends with file of zero bytes.

My suggestion on fix is bad, once the downloadMAnager finds it is same file, it renames an original. And then unpack. This approach should keep CP intact. /me hopes to hear better one
