### ISSUE TITLE
Is IcedTea Web included in openjdk 11?

### ISSUE THREAD

**Issue by AlBundy33** [AdoptOpenJDK/IcedTea-Web#379]
According to https://adoptopenjdk.net/migration.html IcedTea Web is only included in OpenJDK 8.
Will this be added to OpenJDK 11 to?

**Comment by hendrikebbers** [comment]
As far as I know it is not planned to include ITW in Adopt 11. OpenWebStart (https://openwebstart.com) that is build on top of ITW will support Java 11 in near future.

**Comment by judovana** [comment]
ITW is already supporting jdk11 (jdk 13 is the one with probelms now)
Adopt do not include it, and I would say it is jsutified. Jdk11+javaws,... well, not exactl tested
@AdoptOpenJDK  are you planning to include it?

@AlBundy33  you can already now try ITW with jdk11. Just poinnt jaav_home or jre proeprty to it, and itw will run with that. Any feedback on it welcommed

**Comment by AlBundy33** [comment]
IMHO it would be better for endusers to have ITW or OpenWebstart integrated (like in the Oracles older versions). 

At least at now it seems that ITW and OpenWebstart are the only alternatives for webstart. 
Btw. what are the differences between ITW an OpenWebstart?

**Comment by douph1** [comment]
AdoptOpenJDK has actually choose to not bundled IcedTeaWeb after jdk8 to not slow down release process.
see slack thread here : https://adoptopenjdk.slack.com/archives/CGZQHJ8MB/p1558445503208500

>https://github.com/AdoptOpenJDK/openjdk-installer/issues/120
>https://github.com/AdoptOpenJDK/openjdk-installer/pull/121

>I think that as this is holding up a release we should remove it from 11 for now and we can put it back in if the community comes to that conclusion afterwards

Alternatively you can use IcedTeaWeb installer for later jdk from here https://adoptopenjdk.net/icedtea-web.html

**Comment by douph1** [comment]
>what are the differences between ITW an OpenWebstart?

See what OpenWebStart want to add in front of IcedTeaWeb : 
https://openwebstart.com/feature-table/

**Comment by sclassen** [comment]
OpenWebStart contributes as much as possible to ITW. Some features would break the current behavior of ITW and are therefore only available in OWS

So far the main differences are the following:
- different installer (OWS uses install4j, ITW has a custom written)
- installer for macOS (as far as I remember ITW is currently lacking an installer for macOS)
- JVM Manager to download and cache multiple JVMs (will come with the OWS release 0.3.0)

**Comment by AlBundy33** [comment]
Thanks @all for clarification.

According to your answers and the feature-table it seems (at least for now) that ITW should be enough and that there is no need to use OWS.

**Comment by sclassen** [comment]
> IMHO it would be better for endusers to have ITW or OpenWebstart integrated (like in the Oracles older versions).

With OWS you do not have to install any Java on your machine.
- OWS brings its own Java (bundled)
- OWS will download and Cache JVMs for the JNLP files you start

**Comment by sclassen** [comment]
> IMHO it would be better for endusers to have ITW or OpenWebstart integrated (like in the Oracles older versions).

With OWS you do not have to install any Java on your machine.
- OWS brings its own Java (bundled)
- OWS will download and Cache JVMs for the JNLP files you start
