### ISSUE TITLE
JDK 11: provider cannot be found

### ISSUE THREAD

**Issue by nigredo-tori** [AdoptOpenJDK/IcedTea-Web#382]
An application running via `javaws` can't properly instantiate `javax.xml.datatype.DatatypeFactory` provider if there is a non-standard implementation of it in the bootstrap classpath.

Steps to reproduce:
1. Start with Ubuntu 19.04.
1. Install `openjdk-11-jdk` 11.0.4 and `icedtea-netx` 1.8.0.
1. Install `libxerces2-java` 2.12.0 `libxalan2-java` 2.7.2.
1. Extract the provided archive to some folder.
1. Start a server for the codebase (`./run-server`).
1. Build the application (`./build`).
1. Run the JNLP (`./run`).

This results in the following output:
```
selected jre: /usr/lib/jvm/java-8-oracle/jre/
Gtk-Message: 18:04:56.689: Failed to load module "canberra-gtk-module"
selected jre: /usr/lib/jvm/java-11-openjdk-amd64/
WARNING: package javax.jnlp not in java.desktop
Gtk-Message: 18:04:58.859: Failed to load module "canberra-gtk-module"
This application does not specify a Codebase in its manifest. Please verify with the applet's vendor. Continuing. See: http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/security/no_redeploy.html for details.
This application does not specify a Codebase in its manifest. Please verify with the applet's vendor. Continuing. See: http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/security/no_redeploy.html for details.
Application title was not found in manifest. Check with application vendor
Application title was not found in manifest. Check with application vendor
Application title was not found in manifest. Check with application vendor
Application title was not found in manifest. Check with application vendor
Application title was not found in manifest. Check with application vendor
Application title was not found in manifest. Check with application vendor
Application title was not found in manifest. Check with application vendor
Application title was not found in manifest. Check with application vendor
Application title was not found in manifest. Check with application vendor
Application title was not found in manifest. Check with application vendor
Starting application [Main] ...
javax.xml.datatype.DatatypeConfigurationException: Provider for class javax.xml.datatype.DatatypeFactory cannot be found
	at java.xml/javax.xml.datatype.FactoryFinder.findServiceProvider(FactoryFinder.java:299)
	at java.xml/javax.xml.datatype.FactoryFinder.find(FactoryFinder.java:263)
	at java.xml/javax.xml.datatype.DatatypeFactory.newInstance(DatatypeFactory.java:169)
	at Main.main(Main.java:8)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:576)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:945)
Caused by: java.util.ServiceConfigurationError: javax.xml.datatype.DatatypeFactory: Provider org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:588)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1211)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
	at java.xml/javax.xml.datatype.FactoryFinder$1.run(FactoryFinder.java:291)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.xml/javax.xml.datatype.FactoryFinder.findServiceProvider(FactoryFinder.java:287)
	... 9 more
```
(the Oracle JVM in the beginning is not mentioned above, but it shouldn't influence anything).

What's happening here:
1. There is a standard provider for the `DatatypeFactory`:  `com.sun.org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl `.
1. `org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl ` is a non-standard jaxp provider, provided by the `libxerces2-java` package.
1. The JAR in question (`/usr/share/java/xercesImpl.jar`) winds up in the classpath due to `Class-Path` attributes in the xalan2 and tagsoup JARs nearby. The tagsoup JAR is a part of the command that `javaws` launches.
1. (Conjecture) The provider name in `/service/javax.xml.datatype.DatatypeFactory` resource is cached somehow.
1. (Conjecture) The application is run in a fresh sandboxed classloader, and doesn't have access to the original classpath. However, it has access to the cached provider name.Thus the conflict.

As a workaround, removing `libxalan2-java` worked - and removing `libxerces2-java` should also work. However, arriving to that was not easy.

[jnlp-loader-bug.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3540933/jnlp-loader-bug.zip)

**Comment by judovana** [comment]
hi!

This looks like packaging issue.  
I'm betting to two causes - ITW in ubuntu have wrongly declare depndencies, so the jxp have really only apis on CP and not the impelmentation; or the jaxp is wrongly build for jdk11, which needs to declare services in  special file in module.  Still I'm only guessing.

**Comment by judovana** [comment]
On emore thought. is jaxp still part of jdk11? it was part of jdk8, but afaik it went out. if not completely, then from initial module path.

**Comment by nigredo-tori** [comment]
> is jaxp still part of jdk11?

At least the API is still there: https://docs.oracle.com/en/java/javase/11/docs/api/java.xml/javax/xml/datatype/DatatypeFactory.html
And the example (and a more involved application before it) worked fine without shipping a separate implementation (at least I think... the application has a lot of bloat).

> jaxp is wrongly build for jdk11, which needs to declare services in special file in module

The `META-INF/services/javax.xml.datatype.DatatypeFactory` is properly defined (`org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl`), and Java finds the definition, which is evident by it switching from a `com.sun.*` version to the defined one. A file `org/apache/xerces/jaxp/datatype/DatatypeFactoryImpl.class` is present in the JAR. I've checked, and it seems that running the example directly (not via `javaws`) doesn't produce this error, both with and without the xerces and xalan JARs in the classpath. Also, with xerces the example does properly instantiate xerces' service implementation when run directly.

**Comment by lherschi** [comment]
Have a look at the MANIFEST-File of the tagsoup.jar. Under Debian e.g. is there as Class-Path /usr/share/java/xalan2.jar registered. If that's the case for you too, that could be the cause, since javaws has the tagsoup.jar in the bootclasspath.

**Comment by nigredo-tori** [comment]
@lherschi, this is indeed the case, as I mentioned above:
> The JAR in question (/usr/share/java/xercesImpl.jar) winds up in the classpath due to Class-Path attributes in the xalan2 and tagsoup JARs nearby. The tagsoup JAR is a part of the command that javaws launches.

The problem is that a valid service implementation, which winds up in the bootstrapper's classpath, breaks this service's resolution for the application itself. That probably shouldn't happen.

**Comment by lherschi** [comment]
For me, the question arises, why is xalan2 in the classpath of the manifest file of the tagsoup.jar. That's what the package maintainer of the Linux distribution does. This is not the case in the original tagsoup.jar. Either you clean up the manifest file or you also provide the runtime with Xerces (for example via the endorsed directory).

**Comment by Jamila891** [comment]
@hendrikebbers please check if we still depend on these libraries.
