### ISSUE TITLE
Could not read or parse the JNLP file

### ISSUE THREAD

**Issue by joaomax2005** [AdoptOpenJDK/IcedTea-Web#390]
Hello IcedTea-Web Team,

Following guidance from warning "You can try to download this file manually and send it as a bug report to IcedTea-Web team." I am attaching the jnlp (emissorNFe-4_0_1.txt) file for evaluation.

Thank you very much.

[emissorNFe-4_0_1.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3555849/emissorNFe-4_0_1.txt
[trace.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3555861/trace.txt)
)

**Comment by judovana** [comment]
From your log:
net.sourceforge.jnlp.cache.ResourceDownloader$RedirectionException: The resource https://emissores.sebrae.com.br/nfe/v401/producao/emissorNFe-4_0_1.jnlp is being redirected (302) to http://conteudo.sebrae.com.br/nfe/v401/producao/emissorNFe-4_0_1.jnlp. This is disabled by default. If you wont to allow it, run javaws with -allowredirect parameter.     at net.sourceforge.jnlp.cache.ResourceDownloader.findBestUrl(ResourceDownloader.java:312)     at 
...
Resource location=http://emissores.sebrae.com.br/nfe/v401/producao/emissorNFe-4_0_1.jnlp state=PRECONNECT CONNECTING PREDOWNLOAD PROCESSING got redirect 302 code for HEAD request for https://emissores.sebrae.com.br/nfe/v401/producao/emissorNFe-4_0_1.jnlp adding http://conteudo.sebrae.com.br/nfe/v401/producao/emissorNFe-4_0_1.jnlp to list of possible urls

So 302 redirection. Maybe fix the server? Or allow the redirection via javaws -allowredirect ...

Let me know if it helped.

**Comment by judovana** [comment]
btw, with the switch, the app worked for me on both head and 1.8

**Comment by joaomax2005** [comment]
Thanks for the quick return.

It worked perfectly with "javaws.itweb issuerNFe-4_0_1.jnlp -allowredirect"

Thank you!
