### ISSUE TITLE
Update INSTALL guide for new version

### ISSUE THREAD

**Issue by Pawlost** [AdoptOpenJDK/IcedTea-Web#395]
It would be good to update documentation for newcomers like me.

**Comment by sclassen** [comment]
Install guide should list the different options of installing ITW:
- As part of a JDK (e.g. Adopt JDK 8)
- Standalone from the 1.8 release
- Use other tools which include ITW (e.g. https://github.com/karakun/openwebstart)

**Comment by hendrikebbers** [comment]
I created https://github.com/AdoptOpenJDK/IcedTea-Web/issues/706 and https://github.com/AdoptOpenJDK/IcedTea-Web/issues/705 as "Good first issue" issues.
