### ISSUE TITLE
Starting Webapplet via HTTPS fails

### ISSUE THREAD

**Issue by AlexDeep6** [AdoptOpenJDK/IcedTea-Web#397]
Hello Guys.

I have an issue to open a Webstart Applet from a third party vendor via HTTPS. They provide the same app (for development purposes) via HTTP. This app opens correctly.

I've tried several things like ALLOW_UNSIGNED, check Certificates twice, check if it work with Oracle Webstart (it does), set Browser Security Restrictions to a minimum possible in our Environment. 

I think there is an issue while creating and downloading the Applet.jar into .\cache\.
The Applet.jar stays 0 KB. The Applet.jar will be "filled" correctly when starting via HTTP.

**Comment by sclassen** [comment]
can you give a link to the JNLP file so we can try to reproduce

**Comment by judovana** [comment]
@AlexDeep6  hi, we will be happy to fix it or helpo you to make t work. but the jnlp is  necessary.  If you can nto provide it,. then verbose log may also help. It may bve some simple redirection issue or similarly. If you will not provid the info, we wil be sadly forced to close this issue.

**Comment by AlexDeep6** [comment]
Hello judovana: Sorry for my late response - I was out of office due to an accident. I still investigate AdoptopenJDK + Webstart in our Environment and still have the same issues. Ive opened another issue (#566) today, which more explains what Errors I get and what I already done for troubleshooting.
