### ISSUE TITLE
Added new functionality ==> ITWEB-Settings Lock-down

### ISSUE THREAD

**Issue by patris70** [AdoptOpenJDK/IcedTea-Web#399]
Allows for .locked properties to be added to System and User deployment.properties file so that certain widgets will be disabled in the IcedTea-Web Control Panel.

**Updates to netx/net/sourceforge/jnlp/controlpanel/DesktopShortcutPanel.java**

Check for .locked property for desktop shortcut settings and disable the widget at line 108.

       System.out.println("*** Checking for locked settings...");
        Boolean lock = false;
        String propKey = DeploymentConfiguration.KEY_CREATE_DESKTOP_SHORTCUT;
        try {
        	System.out.println("*** Getting raw configuration data for '" + propKey + "'");
            Setting<String> setting = config.getRaw().get(propKey);
            System.out.println("*** Got configuration data, checking boolean");
            lock = setting.isLocked();
            System.out.println("Setting '" + propKey + "' locked? " + lock.toString());
        }
        catch (Exception e) {
        	System.out.println("WARN: " + e.getMessage());
        }
        
        if (lock) { 
        	shortcutComboOptions.setEnabled(false);
        }

**Updates to netx/net/sourceforge/jnlp/controlpanel/SecuritySettingsPanel.java**

Multiple checks for Security Settings, if .locked property is set then disable widgets at line 129:

            System.out.println("*** Checking for locked settings...");
            Boolean lock = false;
            
            try {
            	System.out.println("*** Getting raw configuration data for '" + propKey + "'");
                Setting<String> setting = config.getRaw().get(propKey);
                System.out.println("*** Got configuration data, checking boolean");
                lock = setting.isLocked();
                System.out.println("Setting '" + propKey + "' locked? " + lock.toString());
            }
            catch (Exception e) {
            	System.out.println("WARN: " + e.getMessage());
            }
                
            securityGeneralOptions[i].setSelected(Boolean.parseBoolean(s));
            securityGeneralOptions[i].setActionCommand(properties[i]);
            securityGeneralOptions[i].addActionListener(this);
            if (lock) { 
            	securityGeneralOptions[i].setEnabled(false);
            }
            c.gridy = i + 1;
            topPanel.add(securityGeneralOptions[i], c);
        }

**Changes to netx/net/sourceforge/jnlp/controlpanel/NetworkSettingsPanel.java**

Update to allow disabling widgets on the Network Settings Panel, check for .locked properties at line 120:

        Boolean[] locks = new Boolean[5];
        for (int i = 0; i < properties.length; i++) {
        	String propKey = properties[i];
            Boolean lock = false;
            try {
                Setting<String> setting = config.getRaw().get(propKey);
                lock = setting.isLocked();
                locks[i] = lock;
            }
            catch (Exception e) {
        	    OutputController.getLogger().log("WARN: " + e.getMessage());
            }
        }

Check for locked element in new array and lock widget if necessary:

Address field at line 143:

        if (locks[1]) { addressField.setEnabled(false); }

Port field at line 149:

        if (locks[2]) { portField.setEnabled(false); }

Bypass check at line 169:

        if (locks[3]) { bypassCheckBox.setEnabled(false); }

PAC check at line 216:

        if (locks[4]) { locationField.setEnabled(false); }

**Changes to netx/net/sourceforge/jnlp/controlpanel/JVMPanel.java**

Allow widget locking in JVM Panel starting at line 158:

        lock = false;
        propKey = DeploymentConfiguration.KEY_JRE_DIR;
        try {
        	Setting<String> setting = config.getRaw().get(propKey);
            lock = setting.isLocked();
        }
        catch (Exception e) {
        	OutputController.getLogger().log("WARN: " + e.getMessage());
        }
        if (lock) { testFieldArgumentsExec.setEnabled(false); }
        
        final JButton selectJvm = new JButton(Translator.R("CPJVMPluginSelectExec"));
        
        if (lock) { selectJvm.setEnabled(false); }

 **Changes to netx/net/sourceforge/jnlp/controlpanel/TemporaryInternetFilesPanel.java**

Allow widget locking in Cache panel starting at line 154:

        Boolean lock = false;
        String propKey = DeploymentConfiguration.KEY_CACHE_COMPRESSION_ENABLED;
        try {
        	Setting<String> setting = config.getRaw().get(propKey);
            lock = setting.isLocked();
        }
        catch (Exception e) {
        	OutputController.getLogger().log("WARN: " + e.getMessage());
        }
        if (lock) { cbCompression.setEnabled(false); }

Allow checkbox locking at line 179:

        propKey = DeploymentConfiguration.KEY_CACHE_MAX_SIZE;
        try {
        	Setting<String> setting = config.getRaw().get(propKey);
            lock = setting.isLocked();
        }
        catch (Exception e) {
        	OutputController.getLogger().log("WARN: " + e.getMessage());
        }
        if (lock) { 
        	cacheSizeSpinner.setEnabled(false);
        	limitCacheSizeCheckBox.setEnabled(false);
        }

**Changes to netx/net/sourceforge/jnlp/config/DeploymentConfiguration.java**

Multiple changes throughout to allow saving .locked properties to User deployment properties as long as they exist in the System deployment.properties file:

[DeploymentConfiguration.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3577397/DeploymentConfiguration.zip)

Screenshot:

![lock](https://user-images.githubusercontent.com/39562080/64311090-0dd20f80-cfa3-11e9-9254-849591587237.jpg)

**Comment by judovana** [comment]
Hi this is cwery interesting. Alo it is nice patch. As you already did the work - do yuou mind to provide pull request?

**Comment by patris70** [comment]
Hi, for 10 months we use this option without any problems in enterprice environment.
As i told, i do not any info about pull request

**Comment by hendrikebbers** [comment]
@patris70 if you want we can do a remote session about pull requests tomorrow. Where are you from? I live in Germany (UTC+2 / CEST)

**Comment by patris70** [comment]
@hendrikebbers, can you please check my pull request?
I crested it.

**Comment by hendrikebbers** [comment]
@patris70 do you have time today or tomorrow for a remote session?

**Comment by patris70** [comment]
@hendrikebbers  please check Email
