### ISSUE TITLE
Suggestion: 2x JVM Path parameter for x86 and x64

### ISSUE THREAD

**Issue by patris70** [AdoptOpenJDK/IcedTea-Web#400]
Hi,

Icedtea-Web has just one JVM Path Parameter (deployment.jre.dir).
The problem is, Some Programs need java x86 version and some x64. If i set deployment.jre.dir with target x64 version path,, program fails, because program needs java x86 but java x64 started.

My Suggestion is, we need 2x JVM Path:
for **x64** Version ===> deployment.jre**64**.dir
for **x86** Version ===> deployment.jre**32**.dir 

As Info: Oracle Java uses:
deployment.javaws.jre.**0**.path
deployment.javaws.jre.**1**.path
 
Thanks

**Comment by judovana** [comment]
Thanx a lot for suggestion.
How oracle jdk is switchign between jdks?

**Comment by patris70** [comment]
Hi @judovana 
[https://blogs.oracle.com/java-platform-group/choosing-64-andor-32-bit-java](url)
[https://blogs.oracle.com/pranav/switch-between-different-jdk-versions-in-windows](url)

**Comment by Jamila891** [comment]
Hey @patris70, do you plan to create a pull request for this issue? otherwise we're going to close this issue.

**Comment by patris70** [comment]
Hi @Jamila891 
unfortunately i am not a java developer, i hope someone writes code.

regards
