### ISSUE TITLE
fixed User Keystore Password Prompt

### ISSUE THREAD

**Issue by patris70** [AdoptOpenJDK/IcedTea-Web#401]
Hi,

If user previously used Oracle Java and also had user keystore, Icedtea-Web gets KeyStore Password popup window, because Oracle Java does not set password for user keystore.
Here is fix:

**Updates to net/sourceforge/jnlp/security/KeystorePasswordAttempter.java**
Change Line 128
**From:**

`static final KeystorePasswordAttempter INSTANCE = new KeystorePasswordAttempter(new SavedPassword(getTrustedCertsPassword()));`

**To:**

`static final KeystorePasswordAttempter INSTANCE = new KeystorePasswordAttempter(new SavedPassword(getTrustedCertsPassword()), new SavedPassword("".toCharArray()));`

**Comment by judovana** [comment]
Please provide pull request. Also can this not break keystores with other then "" saved password?

**Comment by patris70** [comment]
@judovana 
no, not break keystore, **ojdkbuild** has added too:
[https://github.com/ojdkbuild/ojdkbuild/issues/99](url)

**Comment by andreiacsantos** [comment]
Is this issue already fix in version 1.8.8?
Some of our clients are still getting the pop up multiple times when they try to use icedTeaWeb.
