### ISSUE TITLE
JNLP files generated by app associated with ITW

### ISSUE THREAD

**Issue by Brodzio** [AdoptOpenJDK/IcedTea-Web#415]
Hello guys,

Will it be possible in future to automatically associate JNLPS / JNLP files generated by web application with ITW? Without setting any file associations in the browser?

**Comment by lherschi** [comment]
Did you install ITW together with AdoptOpenJDK or individually? The msi installer from the individual installation actually creates the necessary registry entries. This may not happen with the AdoptOpenJDK installer.

**Comment by Jamila891** [comment]
@Brodzio at the moment we do not have the resources to implement this for the icedTea-Web stand alone installer. You can try the AdoptOpenJDK installer or the [OpenWebStart](https://github.com/karakun/OpenWebStart) installer. Both automatically associate the JNLP mime type.

**Comment by lherschi** [comment]
As already written, the standalone icedtea-web installer creates all necessary registry entries. I have implemented some of them myself. So nothing needs to be implemented here. The AdoptOpenJDK installer, however, does not generate all the necessary entries.

**Comment by douph1** [comment]
https://github.com/AdoptOpenJDK/IcedTea-Web/issues/557
>Chrome or Edge Chromium does not launch Java automatically for JNLP resources (Google has configured JNLP file as >dangerous with auto_open_hint: DISALLOW_AUTO_OPEN).

Just a note for me :
ITW installer reg keys : https://github.com/AdoptOpenJDK/IcedTea-Web/blob/master/launchers/win-installer/installer.json.in
AdoptOpenJdk installer reg keys : https://github.com/AdoptOpenJDK/openjdk-installer/blob/master/wix/Main.hotspot.wxs
diff : "Content Type" "application/x-java-jnlp-file" vs "application/jnlp"
missing "URL Protocol"
missing EditFlags
missing DefaultIcon
missing jnlps
missing "SOFTWARE\\Classes\\MIME\\Database\\Content Type\\application/x-java-jnlp-file"

**Comment by douph1** [comment]
@Brodzio if your problem is about AdoptOpenJdk installer, please open a issue or better a pull request to fix it in the good repo 
https://github.com/AdoptOpenJDK/openjdk-installer/
including which browser don't handle it well and what content-type you get.
