### ISSUE TITLE
Add support for -Xnosplash option

### ISSUE THREAD

**Issue by akuhtz** [AdoptOpenJDK/IcedTea-Web#420]
Hi,

It would be nice to have support for `-Xnosplash` option from here: https://docs.oracle.com/javase/8/docs/technotes/tools/unix/javaws.html

I tried to prepare a PR but setting the environment variable `ICEDTEA_WEB_SPLASH` is not possible. The env var `ICEDTEA_WEB_SPLASH` is evaluated in `SplashUtils.getSplashEnvironmentVariable()`.
I'm not sure if adding a new member to `JNLPRuntime` and using this in `SplashUtils` is a good decision? Can you give some guidance?

**Comment by judovana** [comment]
+1 for this change. 
Reason why it is environment variable is, that it is shared between launchers and  java. 
It will have to be hnoroed on all three places. You can see how antive bitsda re doing that: 
https://github.com/AdoptOpenJDK/IcedTea-Web/blob/master/launchers/shell-launcher/launchers.sh.in#L7
https://github.com/AdoptOpenJDK/IcedTea-Web/blob/master/launchers/shell-launcher/launchers.sh.in#L161
https://github.com/AdoptOpenJDK/IcedTea-Web/blob/master/launchers/shell-launcher/launchers.sh.in#L148
https://github.com/AdoptOpenJDK/IcedTea-Web/blob/master/launchers/rust-launcher/src/main.rs#L69
https://github.com/AdoptOpenJDK/IcedTea-Web/blob/master/launchers/rust-launcher/src/main.rs#L43

Xnosplash will need to do similarly. To recognize it in https://github.com/AdoptOpenJDK/IcedTea-Web/blob/master/core/src/main/java/net/sourceforge/jnlp/runtime/Boot.java#L135 
and then use it in https://github.com/AdoptOpenJDK/IcedTea-Web/blob/master/core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/splashscreen/SplashUtils.java should be trivial.

Looking forward for PR!

**Comment by akuhtz** [comment]
I just tested it with the new alpha3 release and there is an error :-( 
I think it's in `launchers/rust-launcher/src/main.rs` as the -Xnosplash is a command line argument and not an env var. I try to get my build env ready to fix it.

```
-    is_splash_forbidden_testable(env::vars().collect::<Vec<_>>())
+    is_splash_forbidden_testable(env::vars().collect::<Vec<_>>(), env::args().collect::<Vec<_>>())
}

- fn is_splash_forbidden_testable(vars: Vec<(String, String)>) -> bool {
+ fn is_splash_forbidden_testable(vars: Vec<(String, String)>, aargs: Vec<String>) -> bool {
    for (key, value) in vars {
        if key == "ICEDTEA_WEB_SPLASH" {
            if value.to_lowercase() == "true" {
                return false;
            }
            return true;
        }
-        if key == "-Xnosplash" {
+    }
+    for s in aargs {
+        if clean_param(s) == ("-Xnosplash") {
            return true;
        }
    }
    false
}
```

**Comment by akuhtz** [comment]
@sclassen I was trying openwenstart-0.5.1 but javaws.exe does not start. I'm not sure if the changes in the launcher script were merged into OpenWebStart javaws.exe.

**Comment by sclassen** [comment]
they were merged before we built the 0.5.0 and 0.5.1 so they should be in there

**Comment by sclassen** [comment]
Just to make sure we are on the same page:
openwebstart does not use the rust launcher. It comes with yet another launcher.
Main reason for this is that we want to support macOS

In any case the changes to rust do not have an influence on the OWS launcher

**Comment by akuhtz** [comment]
@sclassen Thanks for this information, I wasn't aware of that. Does that mean I have to open an issue in OpenWebStart to hvae it support -Xnosplash?

**Comment by sclassen** [comment]
would be greate and then link to here
