### ISSUE TITLE
Add ability to override default WindowListener for Frame created for Applet

### ISSUE THREAD

**Issue by matthema** [AdoptOpenJDK/IcedTea-Web#440]
As currently implemented... When IT-W is used to launch an Applet, it creates an AWT Frame as a container for the Applet and specifies an initial `WindowListener.windowClosing()` operation for the Frame. The closing method calls `AppletInstance.destroy()` and `JNLPRuntime.exit(0)` to terminate the Applet and presumably clean-up any resources. The addition of the WindowListener is done in the 2 argument ctor: `AppletEnvironment(JNLPFile, AppletInstance)`.

The issue here is that this approach does not provide the client code (Applet) with the ability to specify its own close behavior through a documented IT-W API that would, in-turn, also call into any closing behavior that's required by IT-W.

For example: For an Applet implementation, I would like the ability to specify a modal dialog that asks the user "Are you sure you want to close this Applet?" and then as a function of the response, conditionally close or leave the Applet open. If the response is to close the Applet, then defer to IT-W to terminate the Applet and do any clean-up it needs to do. But this is not possible without a workaround (noted below) that has its own limitations.

Workaround: Client code can "walk" the Component hierarchy to find the Frame and then make calls to `Frame.getWindowListeners()`, `Frame.removeWindowListener()`, and `Frame.addWindowListener()` to effectively remove and/or re-order the list of WindowListener objects that have been added by IT-W, but such an implementation requires knowledge of IT-W implementation details. Further, the IT-W implementation could change over time, potentially affecting the workaround adversely.

I'm open to the possibility that there is a better way of accomplishing this. If so, advisement would be much appreciated.

**Comment by judovana** [comment]
Hmmm. Applets were fully removed in  2.0. Not sure if it have any point to dig into that dead stuff.

**Comment by matthema** [comment]
Thanks for the reply on this request. I'd like to request some
clarification. Are you saying that JNLP support for Applet has been removed
in IT-W 2.0? Put another way, will IT-W 2.0 not be capable of launching an
Applet, even when the java.applet.* classes are available in the runtime
environment?

The reason I ask... Java v11 - v13 still includes java.applet.*. We all
understand that Applet is deprecated. But it's still there and is still
used. Moreover, it has not yet been deprecated "for removal." I'm sure it
will be in time. But for now it's an integral part of the solution we
provide to large organizations, and I'm sure we're not alone in this. And
even when Applet is removed from OpenJDK, the potential exists for a JNLP
client to provide this implementation; this is probably not recommended but
should be possible, in theory. And would removal of Applet support from
IT-W represent a deviation from the JNLP specification?

If the plan is to remove support for Applet in IT-W 2.0, where can I find
more information about this?

Apologies if I'm not understanding things correctly and my concerns are
unwarranted.

Thanks again for your time and help.

Matt

**Comment by netopyr** [comment]
Hi Matt,

Applets are currently not supported in ITW 2.0 and at this point there are no plans to support them. This is not a deviation from the JNLP-standard as this is an optional feature according to the specs.

We will definitely not support Applets in browsers (I assume, this would not be possible in modern browsers anyway.) But I can imagine to support Applets as standalone applications. This seems to be what you need. Unfortunately none of our sponsors requires Applet-support and therefore this has no priority. Would you be interested in sponsoring the development of Applet-support?

**Comment by matthema** [comment]
@netopyr thank you for the reply and the additional information. Sorry, but I didn't see your reply until just now, otherwise I would have replied sooner. Support for Applet is critical for our product at this time. We could certainly transform it into an application, if necessary. Might I ask... Where can I find more information about the IT-W roadmap to remove Applet support? And where can I find more information about our company sponsoring IT-W?

**Comment by sclassen** [comment]
The development of ITW 2.x is mainly driven by the project https://openwebstart.com
OWS is based on ITW and contributes back as much code as possible.
