### ISSUE TITLE
Issue about PKIX certificate

### ISSUE THREAD

**Issue by Tay08** [AdoptOpenJDK/IcedTea-Web#446]
Context : 
Using AdoptOpenJDK
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b04)
OpenJDK Client VM (AdoptOpenJDK)(build 25.212-b04, mixed mode) include Iced Tea Web

Encountered problem :
When i use the package on thick client application with Java Web Started, an error occured :
`Fatal transport error: sun.security.validator.ValidatorException : PKIX path building failed : sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

**Comment by sclassen** [comment]
is this a duplicate of #445

**Comment by Tay08** [comment]
Yes a new cacerts has changed. It's done ! Thank you
