### ISSUE TITLE
Setting default Proxy setting for IcedTea/ AdoptopenJDK at install for all user in Windows

### ISSUE THREAD

**Issue by Lars-Garage** [AdoptOpenJDK/IcedTea-Web#453]
I need a way to set default Proxy settings at install of "OpenJDK8U-jre_x64_windows_hotspot_8u222b10.msi" so that all users get the same Proxy setting when the start javaws …… If I set Proxy settings with "itweb-settings.exe" it only works for that logged in user.
I aim to install this installation instead of Oracle Java JRE with centralised installation trough Microsoft System Center  Configuration Manager.

**Comment by hendrikebbers** [comment]
Hi, as far as I know such addition is not planned for IWT. If you have knowledge about the native build / installers you can try to contribute such extension.

For OpenWebStart (openwebstart.com) such extension is planned and should be available within the next weeks. While OpenWebStart uses IcedTeaWeb internally we can not contribute that extension to IcedTeaWeb since we use completely different native installers.

**Comment by jantari** [comment]
Hi,

could this please be reconsidered?

This does not have to be a feature of the installer, rather what we need is simply a system-wide configuration file
that an administrator can set. A machine-level equivalent of `$XDG_CONFIG_HOME/icedtea-web/deployment.properties`

This is how many programs operate, e.g. vim.
You have a system-wide default-config that is in `/etc/vim/vimrc.local` (on Debian-based systems)
and then a per-user `$XDG_CONFIG_HOME/.vimrc`

it is often very important to be able to set system-wide defaults on a multi-user machine.

Thank you!

**Comment by sclassen** [comment]
The following documentation is from the project OpenWebStart.
It is using IcedTeaWeb as its core. Thus the same approach is working for ITW.
https://github.com/karakun/OpenWebStart/blob/master/documentation/guide/OWSGuide.adoc#system-configuration

If you need more help in setting up a system wide config please come back

**Comment by jantari** [comment]
Thank you I was able to set that up and get it to work with IcedTeaWeb
