### ISSUE TITLE
IcedTea-Web parallel repo

### ISSUE THREAD

**Issue by hendrikebbers** [AdoptOpenJDK/IcedTea-Web#458]
Today I found the following repo: https://github.com/ojdkbuild/lookaside_icedtea-web
This looks like a clone of the 1.7 release of IcedTeaWeb that is used for the ojdkbuild project. I found this repo based on an issue (https://github.com/ojdkbuild/ojdkbuild/issues/101) and mentioned that bugfixes has been done on the ITW code in that repo. Since the contributor is from RedHat I ask myself if @judovana can maybe contact him and we could find a way to centralise the development in the Adopt ITW repo. We already have a 1.7 branch here and pack porting of issues would be much easier if everything is centralised in this repo.

**Comment by akashche** [comment]
@hendrikebbers, hi, generally ojdkbuild project follows "build CentOS7 (RHEL7) RPMs for Windows" approach. Sources are imported from [lookaside cache](https://github.com/ojdkbuild/ojdkbuild/wiki/LookasideRepos) and a set of patches (from RPM and other bugfixes) is maintained on top of them. For IcedTea-Web sources from Fedora are used. Generally I try to keep additional patches as small as possible and encourage people to contribute them to `AdoptOpenJDK/IcedTea-Web` first. I myself don't participate in IcedTea-Web development for a number of non-interesting reasons and currently have no plans to do so.

Hope this clarifies the situation with this "parallel" repo.

**Comment by hendrikebbers** [comment]
THX @akashche for the feedback. Will close the issue
