### ISSUE TITLE
lack of release source tarball signatures

### ISSUE THREAD

**Issue by anthraxx** [AdoptOpenJDK/IcedTea-Web#463]
Hi,
could you please consider using detached signatures for the release tarballs that are distributed on github and/or sign git tags with local developer keys?
It would be great to be able to retrieve authenticated sources :cat: 

F.e. download https://github.com/AdoptOpenJDK/IcedTea-Web/archive/icedtea-web-1.8.3.tar.gz and upload the detached source tarball signature to the release artifacts

thanks

**Comment by hendrikebbers** [comment]
Hi @anthraxx 

> upload the detached source tarball signature to the release artifacts

Do you have a link to a tutorial?

**Comment by Jamila891** [comment]
Hi @anthraxx, can you provide some help otherwise we are going to close this issue?

**Comment by anthraxx** [comment]
@Jamila891 @hendrikebbers hey, thanks for the response. I was a bit confused about what kind of tutorial your are expecting and then simply forgot that input was requested. Can you help me out in which specific area should I help giving information?
What comes to mind would be: How to create a key, how to manage release keys among team members (how many team members are eligible to create a release?). How to sign a release tarball and put the signature up in github?

If you can tell me which of those I should give input, I will try to write something down during the weekend.

**Comment by hendrikebbers** [comment]
Hi @anthraxx you do not need to write it down if there are already sources online. We are willing to do that be we can not spend much time in this issue. Therefore it would be good if you can send us links to a / some step-by-step documentations so that a developer can do that.

**Comment by anthraxx** [comment]
@hendrikebbers does this include how to create a signing key? Also I would be interested in knowing how many team members are issuing a final release as that is an important bit how to recommend appropriate handling of trusted signing keys. Otherwise a signature is not worth anything if there is no defined set of trusted keys.

**Comment by hendrikebbers** [comment]
I know how to create a key. But I have no idea how to sign a tarball for example ;) I hated there is a good step by step example on "how to sign tarballs for GitHub releases" or something like that :D

**Comment by sclassen** [comment]
Releases are built by a build server. So there is only one key neede.

**Comment by anthraxx** [comment]
@sclassen ah good to know. Is the matching git release tag created before the build server CI runs to release the version or afterwards?
Interesting to know for some recommendations that will follow as you also want to sign the sources as well not just the binary artifacts. The github matching source tarballs should have a signature as well :cat: And does the build server build from git and is aware of the release version label like `icedtea-web-1.8.4` ?

**Comment by sclassen** [comment]
Currently the build server is setup to listen on new git tags.
Thus we create a tag in github. This triggers a build on the buildserver. The buildserver uses git to get the sources from github.
Regarding the source tar balls. They are created by github and not by our build
