### ISSUE TITLE
No JNLP Protocol Handler installed in Windows

### ISSUE THREAD

**Issue by colomb001** [AdoptOpenJDK/IcedTea-Web#473]
Oracle windows installer registers jnlp protocol handler, pointing it to j2plauncher.exe. It would be useful if IcedTeaWeb did the same instead of having to use regedit to create a protocol handler pointing to IcedTeaInstallDir/WebStart/bin/javaws.exe. Firefox allows users to specify protocol handlers within the app, but Chrome relies on those in the registry.

 To reproduce, try opening any jnlp:// link in a web browser.
Expected result, protocol handler launches javaws to process jnlp
Actual result, nothing happens in Chrome, Firefox prompts for application

**Comment by lherschi** [comment]
Can be closed.
https://github.com/AdoptOpenJDK/IcedTea-Web/pull/384
