### ISSUE TITLE
Hide Splash on app start

### ISSUE THREAD

**Issue by DuzAwe** [AdoptOpenJDK/IcedTea-Web#479]
Is there a way to hide the splash on an app start in a windows environment. 

This is the one thing holding back complete rollout for us.

**Comment by sclassen** [comment]
-Xnosplash

**Comment by DuzAwe** [comment]
Where do I set this?

**Comment by sclassen** [comment]
it is a command line parameter

**Comment by DuzAwe** [comment]
So if I want this set globally for when I double click start an app not via command line. I run this?

**Comment by hendrikebbers** [comment]
@DuzAwe can we close this issue?
