### ISSUE TITLE
Dell EqualLogic Group Manager - Unable to run

### ISSUE THREAD

**Issue by firefoxthebomb** [AdoptOpenJDK/IcedTea-Web#482]
Sorry if in the wrong section. I am pretty new to this OpenJDK and IcedTea-Web

So we are trying to get away from Oracle Java and you will now have to pay for it.  So we are trying to get it to run on OpenJDK v13 and icedtea-web v1.8.

We have a Dell EqualLogic PS6000e NAS that requires Java to be able to manage it. We were able to get our Netapp stuff working but can't seem to get this EqualLogic to work.  I got it to the point where it starts to launch the icedtea-web and then just closes, does not launch the app so that we can login and run the program.

Not sure what you guys may need to get started with helping me out. Please advice and thanks in advance

**Comment by sclassen** [comment]
log files and jnlp file would be a start

**Comment by firefoxthebomb** [comment]
I have attached the jnlp file, and if you can share with me how to get you some logs I can see about doing that.

[groupmgr.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3769553/groupmgr.zip)

**Comment by sclassen** [comment]
log files reside in `${USER_HOME}/.config/icedtea-web/log`
If you find no logs there you must enable logging to file in the settings panel.
There is an executable besides javaws for launching the settings panel

**Comment by firefoxthebomb** [comment]
Thanks for the help thus far, I had to turn on logging, hope this helps.
[log.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3769579/log.zip)

**Comment by sclassen** [comment]
You ran into #437
It will be fixed in 2.0.0
Unfortunately I cannot give any ETA for 2.0.0
But you can try using [https://openwebstart.com](https://openwebstart.com) which is based on ITW 2.0.0-alpha versions

**Comment by firefoxthebomb** [comment]
Many thanks for the help, look forward to the 2.0.0 version.  In the meantime, we may try the one you mentioned above.
