### ISSUE TITLE
Packed resources are stored in cache with double file extension

### ISSUE THREAD

**Issue by AndreasEhret** [AdoptOpenJDK/icedtea-web#50]
This issue was imported from bugzilla with bugzilla2github
# Bugzilla Bug Referenze: [3714](https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3714)
Date: 2019-03-28 11:28:00 +0000
From: Lars Herschke &lt;<lhersch>&gt;
To:   JiriVanek &lt;<jvanek>&gt;
CC:   unassigned

Last updated: 2019-04-02 09:08:01 +0000

## Comment 17481
Date: 2019-03-28 11:28:58 +0000
From: Lars Herschke &lt;<lhersch>&gt;

Created attachment 1729
                described patch

                With packed resources, the file extension pack.gz or gz is appended, regardless of whether they already
                have it. I think you should save the resource with the original filename, as with unpacked resources.
                There can be no naming conflicts after unpacking, since different cache directories are used for the
                packed and unpacked variants.
                Enclosed a patch, which ensures exactly.
            

> Attached file: src_726d53216a2621706543644c479b48cad847b651_2.patch (text/plain, 965 bytes)
> Description:   described patch

## Comment 17482
Date: 2019-03-28 11:42:34 +0000
From: Lars Herschke &lt;<lhersch>&gt;

pull request:
                https://github.com/AdoptOpenJDK/icedtea-web/pull/5
            

## Comment 17499
Date: 2019-04-02 09:08:01 +0000
From: Lars Herschke &lt;<lhersch>&gt;

new pull request, with desired commit-message:
                https://github.com/AdoptOpenJDK/icedtea-web/pull/12

**Comment by lherschi** [comment]
Can be closed. Pull request was merged into master.
