### ISSUE TITLE
IcedTea shared jsobject.jar causes JVM crash

### ISSUE THREAD

**Issue by sofoklismalakelis** [AdoptOpenJDK/IcedTea-Web#500]
[Test.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3818489/Test.txt)
[error.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3818501/error.txt)

Windows 10
zulu11.33.15-ca-fx-jdk11.0.4-win_x64
icedtea-web-1.8.3.portable.bin.zip

Steps to reproduce:
Run the Test.txt java class from IcedTea

Workaround: 
Comment out the line below in javaws.bat
rem set "JSOBJECT_JAR=%ITW_HOME%/share/icedtea-web/jsobject.jar"

Tried it with other versions of OpenFX: 11,13,14

jsobject.jar is already included in JavaFX 
Desired solution: prevent IcedTea from using %ITW_HOME%/share/icedtea-web/jsobject.jar
without modifying the javaws.bat

**Comment by janakmulani** [comment]
ITW  must have bundled jsobject.jar that has _netscape.javascript.JSObject_ as it supports Applets.  ITW puts the bundled bundled jsobject.jar on the LAUNCHER_BOOTCLASSPATH.

_netscape.javascript.JSObject__ is also present in jfxrt.jar of JDK 8. 

JDK 11 and Azul FX-JDK 13 have it in jrt-fs.jar
