### ISSUE TITLE
Packed resources are unnecessarily cached after unpacking

### ISSUE THREAD

**Issue by AndreasEhret** [AdoptOpenJDK/icedtea-web#51]
This issue was imported from bugzilla with bugzilla2github
# Bugzilla Bug Referenze: [3715](https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3715)
Date: 2019-03-28 14:56:00 +0000
From: Lars Herschke &lt;<lhersch>&gt;
To:   JiriVanek &lt;<jvanek>&gt;
CC:   unassigned

Last updated: 2019-04-02 09:08:40 +0000

## Comment 17483
Date: 2019-03-28 14:56:03 +0000
From: Lars Herschke &lt;<lhersch>&gt;

Created attachment 1730
                described patch

                Enclosed a patch, which ensures that the packed resources are deleted from the cache. They are no longer
                needed because only the unpacked resources are accessed.
            

> Attached file: src_726d53216a2621706543644c479b48cad847b651_3.patch (text/plain, 4733 bytes)
> Description:   described patch

## Comment 17484
Date: 2019-03-28 15:32:25 +0000
From: Lars Herschke &lt;<lhersch>&gt;

pull request:
                https://github.com/AdoptOpenJDK/icedtea-web/pull/6
            

## Comment 17500
Date: 2019-04-02 09:08:40 +0000
From: Lars Herschke &lt;<lhersch>&gt;

new pull request, with desired commit-message:
                https://github.com/AdoptOpenJDK/icedtea-web/pull/13

**Comment by lherschi** [comment]
Can be closed. Pull request was merged into master.
