### ISSUE TITLE
IcedTea-Web as plugin for Browser on macOS?

### ISSUE THREAD

**Issue by tiiiecherle** [AdoptOpenJDK/IcedTea-Web#511]
Hey,

thanks for all the work that is done in this project and adoptopenjdk.

We need to use a java plugin in a current Firefox or if not possible in FirefoxESR (52.9.0, latest to support java plugins) and we do not want to use oracle java8.

Is it possible to use IcedTea-Web as plugin for browser on macOS?

If yes, what steps have to be done for an installation.

Thanks in advance

**Comment by sclassen** [comment]
Icedtea-web 1.8 does not support macOS
For 2.0 the plugin support has been removed.

So unfortunately I think we cannot help you with this.
