### ISSUE TITLE
Taking longer time ~6 mins to launch jnlp using javaws32

### ISSUE THREAD

**Issue by techRash** [AdoptOpenJDK/IcedTea-Web#513]
1. When I am trying open jnlp file using javaws32.bat, its taking longer time ~6 mins to launch jnlp using javaws32. Details are as below:

-AdoptOpenJDk version 1.8.0_222 on windows 10
-IceTeaWeb is installed at C:\Program Files\IcedTeaWeb\WebStart\bin
-Path variable -> C:\Program Files (x86)\Java\jdk8u222-b10\bin
-javaws32 version -> icedtea-web 1.7.1
[LongDuration.log.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3848794/LongDuration.log.txt)

Error logs are attached. Is there any way to optimize it and lower down the launch time?

2.  I can see every time dialog box of 'remember this option?' popping up and clicking it does not save any settings. Is there any way settings can be saved?
![image](https://user-images.githubusercontent.com/57774775/68899838-32134080-06f8-11ea-9070-8a259ef53b5f.png)

Please guide to resolve this issue.

**Comment by hendrikebbers** [comment]
Hi @techRash can you add the log from IcedTeaWeb please.
