### ISSUE TITLE
AdoptOpenJDK 8-  Icedteaweb settings (Network)

### ISSUE THREAD

**Issue by JAIMY86** [AdoptOpenJDK/IcedTea-Web#515]
Features that impact the whole project (e.g. Adding a new OpenJDK distribution)are made over at the [TSC](https://github.com/AdoptOpenJDK/TSC/).

Hello Team,

Good day.

This is regarding network option in IcedTea -Web control panel(itweb-settings) for Windows OS.

Currently we are using Automatic proxy configuration script under network by specifying the path of proxy file. We tried using "Use browser settings" option, but it was not successful since its not taking internet settings (IE) rather it uses Mozilla proxy settings which we never use in our environment.

1) Is there any possibility to capture the internet settings in Windows OS just like Oracle JRE?
2) Will there be a feature update/change for "Use browser settings" option to use internet settings rather than Mozilla settings in future versions of AdoptOpenJDK under Windows OS?

**Comment by hendrikebbers** [comment]
Hi @JAIMY86 we plan to support IE / Windows setting in near future.

**Comment by JAIMY86** [comment]
> Hi @JAIMY86 we plan to support IE / Windows setting in near future.

Hi,

Many thanks for the update.

Would the fix/feature will be available on or before April 2020?

A possible timeline would help us to plan and migrate the JRE apps on Win10 at an enterprise level.

**Comment by sclassen** [comment]
Planned is before Christmas

**Comment by JAIMY86** [comment]
> Planned is before Christmas

Thanks for the support and update.

looking forward to it :-)

**Comment by sclassen** [comment]
It is now available in OpenWebStart version 1.1.0
We will backport this to IcedTea-Web. But be warned that there is no date set for the ITW 2.0.0 release.
