### ISSUE TITLE
Deployment Rule set file for AdoptOpenJDK JRE 8

### ISSUE THREAD

**Issue by JAIMY86** [AdoptOpenJDK/IcedTea-Web#531]
Dear Team,

We have Deployment rule set file to manage Java exception list where it can bypass the Java prompts by not appearing for users in Oracle JRE 8 (Win10).
For Oracle JRE 8, file resides under "C:\Windows\Sun\Java\Deployment\DeploymentRuleSet.jar"
1)   Is the above file is accepted for AdoptOpenJDK JRE 8?
2 ) Is there any similar setting available in AdoptOpenJDK JRE 8 to bypass the Java warning/prompts?
3) If not the above, will this feature will be integrated in future ?

Thanks for your support.

Regards,
Jaimy

**Comment by patris70** [comment]
@karianna,

here ist my codes, same Oracle DeploymentRuleSet:
https://github.com/AdoptOpenJDK/IcedTea-Web/issues/394
**User** is same Oracle Exception.sites
**System** is same Oracle DeploymetRuleSet (you can using Wildcard in URL or Certificate HASH-256)

![RuleSet](https://user-images.githubusercontent.com/39562080/69870245-8fd68980-12af-11ea-93a5-5676f7a1092e.jpg)

**Comment by hendrikebbers** [comment]
@JAIMY86 at the moment we do not plan to add support for Oracle WebStart Rulesets
