### ISSUE TITLE
icedtea-web-windows-x86

### ISSUE THREAD

**Issue by 220160239** [AdoptOpenJDK/IcedTea-Web#534]
Why icedtea-web 1.8.3 only provides win64 version?  Will win32 version be provided later?

**Comment by sclassen** [comment]
I do not know what the exact plans for version 1.8
There will be a 32 bit version of openwebstart.com which is based on icedtea-web starting next week

**Comment by patris70** [comment]
@sclassen,

please read my suggestion:
https://github.com/AdoptOpenJDK/IcedTea-Web/issues/400

**Comment by lherschi** [comment]
https://github.com/AdoptOpenJDK/IcedTea-Web/issues/248#issuecomment-498236121

**Comment by lherschi** [comment]
Here http://portal.incore.de/install/icedtea-web-1.8.3_x86.msi you can download my 32-bit build. However, this build already has a few backports from the master branch and deployment.https.noenforce defaults to true
