### ISSUE TITLE
System jars (jars of the jre itself) are not recognized as such under windows

### ISSUE THREAD

**Issue by AndreasEhret** [AdoptOpenJDK/icedtea-web#54]
This issue was imported from bugzilla with bugzilla2github
# Bugzilla Bug Referenze: [3720](https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3720)
Date: 2019-04-01 08:26:00 +0000
From: Lars Herschke &lt;<lhersch>&gt;
To:   JiriVanek &lt;<jvanek>&gt;
CC:   unassigned

Last updated: 2019-04-02 15:08:03 +0000

## Comment 17493
Date: 2019-04-01 08:26:39 +0000
From: Lars Herschke &lt;<lhersch>&gt;

Created attachment 1731
                described patch

                In that they are not recognized as such, it then attempts to acquire permissions based on the system
                policies, which then fails and leads to an exception.
                I think if the jre directory contains blank characters, the problem also appears under linux.
                The problem arises from comparing a URL with a platform-specific string.

                Under linux e.g. made the following comparison that works.

                "/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunjce_provider.jar".startsWith("/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext");

                Under windows e.g. made the following comparison that does not work.

                "/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/sunjce_provider.jar".startsWith("C:\Program
                Files\Java\jre1.8.0_201\lib\ext");

                Enclosed a patch that fixes the problem.
            

> Attached file: net_sourceforge_jnpl_runtime_JNLPPolicy.java.patch (text/plain, 1150 bytes)
> Description:   described patch

## Comment 17494
Date: 2019-04-01 08:55:43 +0000
From: Lars Herschke &lt;<lhersch>&gt;

pull request:
                https://github.com/AdoptOpenJDK/icedtea-web/pull/7
            

## Comment 17495
Date: 2019-04-01 09:46:55 +0000
From: Lars Herschke &lt;<lhersch>&gt;

new pull request, the old one was with windows line feeds:
                https://github.com/AdoptOpenJDK/icedtea-web/pull/8
            

## Comment 17497
Date: 2019-04-01 14:49:39 +0000
From: Lars Herschke &lt;<lhersch>&gt;

new pull request, with desired commit-message:
                https://github.com/AdoptOpenJDK/icedtea-web/pull/9
            

## Comment 17501
Date: 2019-04-02 15:08:03 +0000
From: JiriVanek &lt;<jvanek>&gt;

test

**Comment by lherschi** [comment]
Can be closed. Pull request was merged into master
