### ISSUE TITLE
No entry for a JVM in the JVM Manager

### ISSUE THREAD

**Issue by SaschaJostock** [AdoptOpenJDK/IcedTea-Web#547]
After install OpewebStart 1.1.0, i will configure the JVM in OpenwebStart.
Open the configuration Dialog from OpenwebStart and goto to JVM Manager,
then click the Button "Add", selected my JVM, click "open", create no entry for
a JVM in the Manager.
![image](https://user-images.githubusercontent.com/6065642/70702098-ccea4500-1ccd-11ea-97e5-1cc6372f0d23.png)
The list is empty. No Errors or log entries.

I use the JVM 1.8 and JVM 11 from Eclipse OpenJ9 and JVM 1.8 from Oracle

Cheers, 
Sascha

**Comment by hendrikebbers** [comment]
Hi,
can you please provide the OpenWebStart Log-File?

**Comment by sclassen** [comment]
Try to select a parent dir of the installation.
If this does not work could you please attach the log file from `%USER_HOME%\.config\.icedtea-web\log` to this ticket

**Comment by SaschaJostock** [comment]
I've select the parent dir of the Installation, no JVM found :-(
The Folder %USER_HOME%\.config\.icedtea-web\log is empty.
![image](https://user-images.githubusercontent.com/6065642/70713225-d2538980-1ce5-11ea-8e1a-c9aef6dc5d80.png)

**Comment by hendrikebbers** [comment]
to see some log you need to activate its in the OpenWebStart settings. Please activate debug logging and logging to file system
