### ISSUE TITLE
iDrac jnlp won't open

### ISSUE THREAD

**Issue by jboznw** [AdoptOpenJDK/IcedTea-Web#554]
iDrac controller jnlp will not open on AdoptOpenJDK 8 x64 as downloaded from Ninite.com
Sticks at this screen:
![image](https://user-images.githubusercontent.com/48067947/71113129-f8bc6d80-219a-11ea-84ca-16992566a172.png)

**Comment by hendrikebbers** [comment]
can you please attach the URL of the JNLP file and the log of ITW.
