### ISSUE TITLE
IcedTea Web fails to Cache Jar files correctly. They have Size of 0 KB

### ISSUE THREAD

**Issue by AlexDeep6** [AdoptOpenJDK/IcedTea-Web#566]
When I start specific JNLP Files (SAP PI Tools, some other Tools of our Company) I get an Error, that the main class could not load. Further investigations shows me, that the JAR Files from the OnlineRepositories are not downloaded correctly by javaws. 

The JAR Files in the .Cache Folder are created, but stays 0 KB and of course couldnt load properly. I have other JNLP Files where the JAR Files downloaded correctly. 

This is a Major Showstopper for migrating to AdoptOpenJDK in our case. I saw this behavior in the last three builds. (Using jdk8u232-b09). 

Things I've done so far to troubleshoot:
- Check Privileges on the .Cache and Subfolders - my User has Full Access
- Give unlimited space for caching
- changed Cache Location
- Check if there is a Proxy Issue (since IcedTea Web didnt use the Proxy.pac from IE, we dont use Firefox) - in this case there is no active proxy between my client and the SAP PI Tools Host

I didnt find anything here to this issue, so I open a new Issue.

**Comment by AlexDeep6** [comment]
I've checked the JNLP which runs fine against the one which doesnt. The code for downloading JAR Files from the vendor repositories are different. See below:

Working JNLP
<jar href="some.jar" version="1.0"/>

Not Working JNLP
<jar href="directory/com.sap.xpi.ibdir.client.jar" download="lazy" part="part-11"/>

- changed Lazy to eager - no success
- removed HeapSize restrictions - no success
- removed "Download="something" from JNLP - no success

But I would bet the Issue comes from different coded jnlp files. Some work fine, some maybe has to be updated/edited to be work again. Any JNLP Coders here which can confirm/deny my thoughts?!

**Comment by AlexDeep6** [comment]
Working JNLP
`<jar href="some.jar" version="1.6"/>`

Not Working JNLP
`<jar href="directory/com.sap.xpi.ibdir.client.jar" download="lazy" part="part-11"/>`

**Comment by sclassen** [comment]
could you provide log files and JNLP file for a non working application

**Comment by AlexDeep6** [comment]
Hello Sclassen,

See logfile (outputJWS.txt) and jnlp (directory.jnlp)
[directory.jnlp.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4069999/directory.jnlp.txt)
[outputJWS.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4070000/outputJWS.txt)

Iam able to download the jar Files manually via IE in every case where I see that 0 KB behavior.

**Comment by sclassen** [comment]
I am not a 100% sure what is going wrng. I do see a lot fo stacktraces:
```
java.io.EOFException: Unexpected end of ZLIB input stream
     at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
     at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
     at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
     at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
     at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
     at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
     at java.io.FilterInputStream.read(FilterInputStream.java:107)
     at net.sourceforge.jnlp.cache.ResourceDownloader.uncompressGzip(ResourceDownloader.java:488)
     at net.sourceforge.jnlp.cache.ResourceDownloader.downloadGZipFile(ResourceDownloader.java:405)
     at net.sourceforge.jnlp.cache.ResourceDownloader.downloadResource(ResourceDownloader.java:362)
     at net.sourceforge.jnlp.cache.ResourceDownloader.run(ResourceDownloader.java:118)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:748) 
```
It looks like the jars are sent gziped from the server and ITW fails to unpack them and therefore you see the files only with size 0.
But why it cannot unpack is unclear to me

**Comment by AlexDeep6** [comment]
Hey there. 

Does anyone has a clue, why the files arent properly unzipped. I see this error on another Applet we use.

With the other applet its strange - if I download the jnlp File from a http Source (testing area) it works fine. If I download the jnlp from a https source (productive area) it fails with the same 'Unexpected end of ZLIB input stream' error. 

Could that be an Issue with certhandling?

**Comment by sclassen** [comment]
no, check you http server if it is using gzip compression or if it is sending the files uncompressed

**Comment by AlexDeep6** [comment]
Thanks for your fast reply.
I will check this on Monday.

**Comment by klaus4040** [comment]
I'm experiencing the same problem. And yes, the webserver compresses with gzip. It is not within my domain though, so I can't disable it.

**Comment by AlexDeep6** [comment]
Hello Together,

I've searched about IcedTeaWeb and GZIP and found another Projekt: OpenWebstart via this Thread:
https://github.com/AdoptOpenJDK/IcedTea-Web/issues/487

With this Software and a local JVM (AdoptOpenJDK works fine here) all our Applets which has the GZIP Problem could be strarted. Further Tests from the ApplicationOwners will show if it works properly.

**Comment by haddybo** [comment]
Hi sclassen，
     We witnessed the same issue, any plan to fix it?  The .zip file decompress fail is introduced [here](https://github.com/AdoptOpenJDK/IcedTea-Web/commit/3f08fb429347209a8d7d8f2dde779df5e862f7af).

**Comment by sclassen** [comment]
@judovana do you have plans for another 1.8.x release?
We still focus all of our developmento onto the 2.0.0 release. But unfortunately we do not have a ETA yet.

**Comment by orhanmustafa** [comment]
I am having the same issue. 

I enabled GZIP on my Tomcat 8 Server (compression="on"), but it didn't help. I was able to confirm via curl (calling the jnlp URL) that encoding is on:
```
curl -H "Accept-Encoding: gzip" -I https://example.com:8443/testsystem/application6.jnlp

HTTP/1.1 200
Vary: accept-encoding
Accept-Ranges: bytes
ETag: W/"1643-1632753540961"
Last-Modified: Mon, 27 Sep 2021 14:39:00 GMT
Content-Encoding: gzip
Content-Type: application/x-java-jnlp-file
Transfer-Encoding: chunked
```

But IcedTeaWeb-Webstart still can't download the jnlp properly. It says "downloading... (encoding: gzip)" and yet again it gets the "Unexpected end of ZLIB" error. (See Webstart log)

Unfortunately my situation is this: Our clients have AdoptOpenJDK deployed by their administrator and we have no way of changing that. I can only act within the boundaries of the server, change its configuration, the JNLP and/or JARs.

So does anyone have any idea or workaround, which does not involve changing the standard AdoptOpenJDK IcedTeaWeb Webstart (e.g. "use OpenWebStart")? Anything else I can try on my Tomcat 8 configuration?

[webstart.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/7260561/webstart.log)
[aplication6.jnlp.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/7260564/aplication6.jnlp.txt)

_P.s.: I'm pretty sure it's the combination of my Tomcat configuration + AdoptOpenJDK IcedTeaWeb Webstart, because I can run the Java example [DynamicTree](https://docs.oracle.com/javase/tutorialJWS/samples/deployment/dynamictree_webstartJWSProject/dynamictree_webstart.jnlp) on docs.oracle.com, but if I upload that same JNLP and JAR to my Tomcat Server, then I get the "Unexpected end of ZLIB" error again._

**Comment by pbiering** [comment]
Ran into the same issue trying to access Lenovo XCC interface (hardware server remote management) from a Linux (EL8) host

```
$ javaws -version
icedtea-web 1.8.4 (fedora-4.el8-x86_64)

$ javaws -Xclearcache
$ javaws -jnlp Downloads/rp.jnlp 

Unable to use Firefox's proxy settings. Using "DIRECT" as proxy type.
JAR https://192.0.2.123/JavaRP/avctKVM.jar not found. Continuing.
JAR https://192.0.2.123/JavaRP/avctKVMIOLinux64.jar not found. Continuing.
JAR https://192.0.2.123/JavaRP/avctVMAPI_DLLLinux64.jar not found. Continuing.
JAR https://192.0.2.123/JavaRP/avctKVM.jar not found. Continuing.
JAR https://192.0.2.123/JavaRP/avctKVMIOLinux64.jar not found. Continuing.
JAR https://192.0.2.123/JavaRP/avctVMAPI_DLLLinux64.jar not found. Continuing.
netx: Initialization Error: Could not initialize application. (Fatal: Initialization Error: Unknown Main-Class. Could not determine the main class for this application.)
net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize application. The application has not been initialized, for more information execute javaws from the command line.
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:823)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:531)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:946)
Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Unknown Main-Class. Could not determine the main class for this application.
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:776)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:338)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:421)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:495)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:468)
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:815)
	... 2 more

$ find .cache/icedtea-web/ -ls
  4503171      0 drwxr-xr-x   5  testuser users          44 Sep 30 12:23 .cache/icedtea-web/
 13144741      0 drwxr-xr-x   2  testuser users           6 Sep 30 12:23 .cache/icedtea-web/pcache
  6456937      0 drwxr-xr-x   2  testuser users           6 Sep 30 12:23 .cache/icedtea-web/tmp
 14730998      0 drwxr-xr-x   5  testuser users          54 Sep 30 12:23 .cache/icedtea-web/cache
 14731000      4 -rw-r--r--   1  testuser users         351 Sep 30 12:23 .cache/icedtea-web/cache/recently_used
   119361      0 drwxr-xr-x   3  testuser users          19 Sep 30 12:23 .cache/icedtea-web/cache/0
  2178885      0 drwxr-xr-x   3  testuser users          26 Sep 30 12:23 .cache/icedtea-web/cache/0/https
  4503172      0 drwxr-xr-x   3  testuser users          20 Sep 30 12:23 .cache/icedtea-web/cache/0/https/192.0.2.123
  6456932      0 drwxr-xr-x   2  testuser users          67 Sep 30 12:23 .cache/icedtea-web/cache/0/https/192.0.2.123/JavaRP
  6456938      4 -rw-------   1  testuser users         170 Sep 30 12:23 .cache/icedtea-web/cache/0/https/192.0.2.123/JavaRP/avctKVMIOLinux64.jar.info
  6456943      0 -rw-r--r--   1  testuser users           0 Sep 30 12:23 .cache/icedtea-web/cache/0/https/192.0.2.123/JavaRP/avctKVMIOLinux64.jar
  8461509      0 drwxr-xr-x   3  testuser users          19 Sep 30 12:23 .cache/icedtea-web/cache/1
 10738590      0 drwxr-xr-x   3  testuser users          26 Sep 30 12:23 .cache/icedtea-web/cache/1/https
 13144742      0 drwxr-xr-x   3  testuser users          20 Sep 30 12:23 .cache/icedtea-web/cache/1/https/192.0.2.123
 14731001      0 drwxr-xr-x   2  testuser users          75 Sep 30 12:23 .cache/icedtea-web/cache/1/https/192.0.2.123/JavaRP
 14731002      4 -rw-------   1  testuser users         170 Sep 30 12:23 .cache/icedtea-web/cache/1/https/192.0.2.123/JavaRP/avctVMAPI_DLLLinux64.jar.info
 14731003      0 -rw-r--r--   1  testuser users           0 Sep 30 12:23 .cache/icedtea-web/cache/1/https/192.0.2.123/JavaRP/avctVMAPI_DLLLinux64.jar
   119382      0 drwxr-xr-x   3  testuser users          19 Sep 30 12:23 .cache/icedtea-web/cache/2
  2178898      0 drwxr-xr-x   3  testuser users          26 Sep 30 12:23 .cache/icedtea-web/cache/2/https
  4503182      0 drwxr-xr-x   3  testuser users          20 Sep 30 12:23 .cache/icedtea-web/cache/2/https/192.0.2.123
  6456941      0 drwxr-xr-x   2  testuser users          49 Sep 30 12:23 .cache/icedtea-web/cache/2/https/192.0.2.123/JavaRP
  6456942      4 -rw-------   1  testuser users         170 Sep 30 12:23 .cache/icedtea-web/cache/2/https/192.0.2.123/JavaRP/avctKVM.jar.info
  6456944      0 -rw-r--r--   1  testuser users           0 Sep 30 12:23 .cache/icedtea-web/cache/2/https/192.0.2.123/JavaRP/avctKVM.jar
```

JAR files have empty size,  `javaws` show very huge % values during download.

Ugly workaround to get it used at all is entering each cache directory and download the JAR file via `wget`.
