### ISSUE TITLE
JARs downloaded with URI-escaped characters don't get loaded

### ISSUE THREAD

**Issue by puckipedia** [AdoptOpenJDK/IcedTea-Web#573]
If a `jnlp` file is loaded that contains a JAR like `https://example.com/thing.jar?foo=bar%40baz`, the file gets stored in `.cache/icedtea-web/cache/N/https/example.com/thing.jar.foo_bar%40baz`, but but when the URI classloader tries to load the JAR, it doesn't load it.

I'm not certain on the exact details, but in 1.8, adding `%` to the `FileUtils.INVALID_PATH` list seems to fix it? This is 1.8.3 with the OpenJDK JRE on Linux (NixOS)

**Comment by nigredo-tori** [comment]
Just hit this as well.
1. There was a snapshot dependency with version dynamically generated from Git history (`foo:0.1+12-abcdef01-SNAPSHOT`).
1. Coursier escaped the corresponding JAR as `foo-0.1%2B12-abcdef01-SNAPSHOT.jar`.
1. The SBT plugin we use to build our JNLPs used that file name as-is.
1. On the client side, the JAR is successfully downloaded/cached, but it fails to load.

**Comment by SchwingSK** [comment]
I was too affected by this bug: it stems from an inconsistency in the storage/retrieval of local files URLs in the download cache.
The cache is a map of <original URL, local file URL>
When a local file is stored in the cache, File.toURI().toURL() is called to transform it to an URL. The toURI() call URI-encodes the path.
So if the path was foo%40.jar, it becomes foo%2540.jar

However, when the local file URL is retrieved from this cache, the URL is converted to a file using URL.getPath(), which returns foo%2540.jar. Calling URL.toURI().getPath() correctly returns foo%40.jar.
Here's a patch that fixes the problem (or at least fixes it with no detected problems on my setup)
