### ISSUE TITLE
support for sun.awt.disableMixing = true

### ISSUE THREAD

**Issue by benchpresser** [AdoptOpenJDK/IcedTea-Web#586]
we need this property sun.awt.disableMixing in the list of the 
common/src/main/java/net/adoptopenjdk/icedteaweb/JavaSystemPropertiesConstants.java
and whitelisted in core/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/element/security/SecurityDesc.java

otherwise we get problems running apps where LW and HW are mixed.
AFAIK, setting sun.awt.disableMixing in System.setProprty (after JVM has started) is too late and it should be added in the JNLP phase.

**Comment by sclassen** [comment]
What are you understanding by 'whitelisted' ?
The properties in the lists `sandboxPermissions` and `jnlpRIAPermissions` are specified in the JSR-56.

**Comment by benchpresser** [comment]
same issue was in the oracle jdk
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6851271
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6788954
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6852243

in our application we have to mix hw+lw and also use a customglasspane (jdesktop jxlayer)
we run fine with adopt openjdk without jnlp (run as batch java .exe -jar etc) but get problems with HW components when started with icedtea the reason is setting sun.awt.disableMixing in the jnlp has no effect and setting in main System.setProp.. is too late (since JVM has already started)

**Comment by AndreasEhret** [comment]
please test with 1.1.7

**Comment by benchpresser** [comment]
thank you very much i am testing it
