### ISSUE TITLE
ECMAScript Engine not found

### ISSUE THREAD

**Issue by ledahulevogyre** [AdoptOpenJDK/IcedTea-Web#588]
The nashorn JS engine doesn't seem to be working when using ITW, even when all-permissions is declared.
Even if I add nashorn.jar in the classpath, it doesn't work.
Is it a security feature, or a bug ?

Thank you.

**Comment by sclassen** [comment]
Can you be more specific what does "not working" mean.
Do you get an exception or just no result?

**Comment by ledahulevogyre** [comment]
The following test prints "jdk.nashorn.api.scripting.NashornScriptEngine@17faa95" when running from the command line. But through IcedTea-Web, it prints "null".

    ScriptEngineManager manager = new ScriptEngineManager();
    System.out.println(manager.getEngineByName("ECMAScript"));

It seems that the nashorn JS engine is not accessible when running through IcedTea-Web.
You can run this test yourself [here](https://leunen.me/test.jnlp).

**Comment by sclassen** [comment]
Found the issue:
The problem is that the JNLPClassloader is not properly setup in the class loader hierarchy.
Currently it is a child of the bootstrap class loader. But correctly it should be a child of the system class loader (see https://www.baeldung.com/java-classloaders)

Will be fixed in 2.0.0

**Comment by ledahulevogyre** [comment]
Thank you very much for the info.
I see v. 2.0.0 is in alpha stage. Do you have any rough estimate of a date for the prod release ?

**Comment by sclassen** [comment]
There is no prod release planned in the near future.
But there exists https://openwebstart.com which builds on 2.0.0-alpha

**Comment by ledahulevogyre** [comment]
Ok. Thank you. 
I have two more questions:

When you say JNLPClassloader will be fixed in 2.0.0, do you mean it's already fixed but not in a release yet? or is it already fixed in the icedtea-web-2.0.0-alpha12 release ? Or a fix is yet to be developed ?

Do you know if AdoptOpenJDK and ojdkbuild also build on 2.0.0-alpha ?

Thank you very much.
Have a good day

**Comment by sclassen** [comment]
It is fixed on the branch classloader-prototype.
But be aware that this branch is an experimental re-implementation of the core of ITW. Some features are missing compared to master (e.g. sandboxing)

As far as I know there are currently no 2.0.0-alpha builds from Adopt
