### ISSUE TITLE
Unsupported optional start parameter "SurvivorRatio" makes all parameters being ignored

### ISSUE THREAD

**Issue by cohe** [AdoptOpenJDK/IcedTea-Web#591]
**Platform:** Windows7 and Windows10

**Architecture:** 32bit and 64bit

When starting a complex webStart-Application via IcedTea and/or OpenWebStart,
all optional start parameters are ignored
if the option -XX:SurvivorRatio=6 exists.

Tested on systems mentioned above.
It has resulted in an out-of-memory situation since another parameter -Xmx was not applied.
Removing the option -XX:SurvivorRatio=6 solved the issue and all other parameters had effect.

Used versions of AdoptOpenJDK:
8u222, 8u232 and 8u242

Best regards,
cohe

**Comment by janakmulani** [comment]
Can you please send your jnlp file?

**Comment by cohe** [comment]
Hello janakmulani,

the old parameter line was:
`<j2se version="1.5+" java-vm-args="-Xmx512m -Xms128m -XX:SurvivorRatio=6 -XX:NewSize=96m -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=30"/>`
there every parameter was ignored.

After removing `-XX:SurvivorRatio=6` the other parameters are applied:
`<j2se version="1.5+" java-vm-args="-Xmx512m -Xms128m -XX:NewSize=96m -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=30"/>`

best regards,
cohe

**Comment by janakmulani** [comment]
Thanks for the jnlp. I can reproduce the issue.
