### ISSUE TITLE
--add-modules JVM parameter doesn't seem to be honored

### ISSUE THREAD

**Issue by don-vip** [AdoptOpenJDK/IcedTea-Web#595]
The [JOSM JNLP file](https://josm.openstreetmap.de/download/josm.jnlp) declares the following JVM arguments:

```xml
<java version="1.8+" max-heap-size="2048m"
 java-vm-args="--add-modules=java.scripting,java.sql --add-exports=java.base/sun.security.util=ALL-UNNAMED --add-exports=java.base/sun.security.x509=ALL-UNNAMED --add-exports=java.desktop/com.apple.eawt=ALL-UNNAMED --add-exports=java.desktop/com.sun.imageio.spi=ALL-UNNAMED --add-exports=java.desktop/com.sun.imageio.plugins.jpeg=ALL-UNNAMED --add-exports=javafx.graphics/com.sun.javafx.application=ALL-UNNAMED --add-exports=jdk.deploy/com.sun.deploy.config=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/jdk.internal.loader=ALL-UNNAMED --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.desktop/javax.imageio.spi=ALL-UNNAMED --add-opens=java.desktop/javax.swing.text.html=ALL-UNNAMED --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED"/>
```

As per:
* https://josm.openstreetmap.de/ticket/18751 (icedtea-web:x86_64-1.7.1)
* https://josm.openstreetmap.de/ticket/18737 (icedtea-netx:all-1.7.2-2)
* https://josm.openstreetmap.de/ticket/18742 (icedtea-netx:amd64-1.8-0ubuntu8)
* my own experience running OpenWebStart 1.1.4 with JDK11

it seems the JVM parameters are not all honored correctly.

In particular, the "**--add-modules=java.scripting,java.sql**" is not respected, and results for users with "**ClassNotFoundException: javax.sql.DataSource**" or "**NoClassDefFoundError: java/sql/Date**" errors when the JOSM GeoTools or wikipedia plugins are loaded.

Problem doesn't happen with Oracle Java WebStart.

**Comment by AndreasEhret** [comment]
it is fixed in OpenWebStart (release 1.1.7)
