### ISSUE TITLE
Minor typos in english texts

### ISSUE THREAD

**Issue by activityworkshop** [AdoptOpenJDK/IcedTea-Web#611]
Hi all,
I noticed a minor typo in one of the warning messages shown: "Be very careful when application is loading from different space th**e**n you expect" - in this case "then" should be "than".
The version reported is 19.6.26659.7340" if that helps.  It's provided by Debian's package of icedtea-netx version 1.7.2-2.

I found the text in the file "common/src/main/resources/net/adoptopenjdk/icedteaweb/i18n/Messages.properties" and saw in there that there are other cases of "More th**e**n one" (instead of "More than one") and "Cant" (instead of Can't).  Also "an parameter" instead of "a parameter", and "there is to many" instead of "there are too many".

I realise these are very trivial issues, but I assume they are therefore pretty easy to fix.  Maybe something for a first-time-fixer?
Thanks!

**Comment by sclassen** [comment]
A pull request would be highly appreciated

**Comment by activityworkshop** [comment]
pull request on the way.  let me know if it needs tweaking.

**Comment by sclassen** [comment]
merged #612
