### ISSUE TITLE
Direct socket download fails

### ISSUE THREAD

**Issue by thezboe** [AdoptOpenJDK/IcedTea-Web#618]
```
Fri Apr 03 13:55:25 MST 2020 [DEBUG  ] net.adoptopenjdk.icedteaweb.resources.downloader.BaseResourceDownloader: Header of: http://192.168.1.10:8080/files/example.jar (location=http://192.168.1.10:8080/files/example.jar version=null state=INCOMPLETE)
Fri Apr 03 13:55:25 MST 2020 [DEBUG  ] net.adoptopenjdk.icedteaweb.resources.downloader.BaseResourceDownloader:
HTTP/1.1 200 OK
Server: httpd
Date: Fri, 03 Apr 2020 20:34:57 GMT
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Type: application/x-java-archive
Content-Length: 1236014


Fri Apr 03 13:55:25 MST 2020 [DEBUG  ] net.adoptopenjdk.icedteaweb.resources.downloader.BaseResourceDownloader: Body is: 1236014 bytes long
Fri Apr 03 13:55:25 MST 2020 [DEBUG  ] net.adoptopenjdk.icedteaweb.resources.downloader.BaseResourceDownloader: Exception while downloading resource location=http://192.168.1.10:8080/files/example.jar version=null state=INCOMPLETE from http://192.168.1.10:8080/files/example.jar - Index 1 out of bounds for length 1
```

This is due to this line https://github.com/AdoptOpenJDK/IcedTea-Web/blob/76bf7aa0561443a31ec0e3e0f924980ae6a3e19b/core/src/main/java/net/adoptopenjdk/icedteaweb/resources/downloader/BaseResourceDownloader.java#L179

If you are going to split a line, then access [0] and [1], then the filter line should read:
```                .filter(a -> a.length == 2)```
to ensure the array has length 2.
The way it is currently will almost always guarantee an exception.

I'm also not sure why my servers response isn't parsed as valid HTTP, which is why it is falling back to direct socket.

**Comment by sclassen** [comment]
Thanks for finding this mistake, it is a part of the code which rarely is executed.
fixed in https://github.com/AdoptOpenJDK/IcedTea-Web/commit/fd2b26f8b480081ed499fca50944ad2050c58924
