### ISSUE TITLE
RUN_ARGS_LOCATION in itweb-javaws is wrong

### ISSUE THREAD

**Issue by joakim-tjernlund** [AdoptOpenJDK/IcedTea-Web#622]
I got
```
RUN_ARGS_LOCATION=/var/tmp/portage/dev-java/icedtea-web-1.7.2/image/usr/bin/itw-modularjdk.args
```
which point to where icedtea-web was built, how do a configure, during build, another location?

**Comment by joakim-tjernlund** [comment]
1.8 has the same problem

**Comment by hendrikebbers** [comment]
Can you please have a look at the 2.0 branch. Currently we do not plan to back port fixes to 1.8 anymore. We plan to do a last 1.8 release in near future and than switch to 2.0

**Comment by joakim-tjernlund** [comment]
I suspect 2.0 has new build changes so I would have work on that first. If you are on 2.0,
can you check what your RUN_ARGS_LOCATION is?

**Comment by sclassen** [comment]
We changed this in the 2.0 branch. The args are now in the Java code an no longer in a file
