### ISSUE TITLE
net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file

### ISSUE THREAD

**Issue by cedricbousmanne** [AdoptOpenJDK/IcedTea-Web#627]
Hi, 

I'm running into an issue trying to launch a JNLP file.

The file is a card game available online, it works well on a windows computer with `javaws`, but I can seem to have it working on my computer (Linux/Manjaro).

I have little to zero experience with Java or IcedTea-Web, but I seem to understand that the distant `?application_launch` returns a 403 error instead of a 200 which would hopefully allow me to run the program?

What I don't understand though, is that the exact same JNLP file works on windows via a virtual machine and not on the host system. 

I spent a lot of time googling around and tried multiple things but my lack of experience in the matter prevent me to find a solution. (ie: i made sure the SSL CA was trusted).

Could anyone please help me understand what's happening / how can I get this to work?

[javaws.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4497745/javaws.log)
```
$ java --version
openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode)

```
`Java Runtime AdoptOpenJDK-1.8.0_242`

**Comment by sclassen** [comment]
Can you please also attach the JNLP file

**Comment by cedricbousmanne** [comment]
Here's the JNLP file : [whist.jnlp](https://gist.github.com/cedricbousmanne/9194eb56135bd1c557ce53b0a308b7af)

**Comment by sclassen** [comment]
OK, I found an issue in our code. But fixing this did not resolve the issue.
I keep on getting a HTTP 403 response from the server.
But when I try to access the URL from the browser I get a 200.
So it seams there is some rule in place which rejects the requests from OWS.

**Comment by sclassen** [comment]
Further trials show that useing HTTP instead of HTTPS lets me download all resources.
never the less I end in a known classloader problematic.
You can try our 3.0.0-alpha release to see if the classloader issue is fixed there.
But first you should find out why your server is rejecting the HTTPS requests from OWS

**Comment by sclassen** [comment]
OK, enforcing HTTP and using 3.0.0-alpha I can launch the application and reach the login scree

**Comment by cedricbousmanne** [comment]
Thank you very much. 

I'm not familiar with java though. I downloaded the [3.0.0-alpha1](https://github.com/AdoptOpenJDK/IcedTea-Web/releases/tag/icedtea-web-3.0.0-alpha1) release and i seem to understand that i need to lauch the `./launchers/build.sh´ script but it also seem i'm missing some ENV variable. 

I couldn't find a doc explaining how to build it from the source, could you point me one so i can have a try? 

Thanks

**Comment by sclassen** [comment]
You can find binaries in the open web start project:
https://github.com/karakun/OpenWebStart/releases/tag/v3.0.0-alpha1

**Comment by cedricbousmanne** [comment]
Thanks. I managed to install the 3.0.0.alpha version. Although I still cannot run the application. 

Here's the [logfile](https://gist.github.com/cedricbousmanne/a6c7888a5a8625555d3121bc5e43c1d7) and the [JNLP](https://gist.github.com/cedricbousmanne/61aec81ec78d2012a6d03e3e33405eff) modified as you advised. Do you see something I would have done the wrong way?

**Comment by sclassen** [comment]
No, you are currently seeing the bug which I fixed on master but is not yet in a release.

A tmporary workaround would be to remove the `href='/?application_launch'` from the JNLP.
The next version will contain the fix.

**Comment by cedricbousmanne** [comment]
It seems to work indeed, I have the prompt at the start and the bell sound that indicated the code runs, although all I see is a white screen. I think this is outside of this bug's scope but if you have any suggestion that'd be helpful

**Comment by sclassen** [comment]
Could be related to the java version.
You could set the version in the JNLP to `1.8*`.
Maybe this has an effect

**Comment by cedricbousmanne** [comment]
I changed this line 
`<jnlp spec='1.5+' codebase='http://www.whistenligne.com'>`
Like this :
`<jnlp spec='1.8*' codebase='http://www.whistenligne.com'>`

Is that what you meant? If so unluckily it didn't work.

**Comment by sclassen** [comment]
Sorry for being unclear. I ment tge `j2se` version

**Comment by cedricbousmanne** [comment]
Still no luck :(

Do you see the login screen yourself?

**Comment by sclassen** [comment]
I see the following with Azul 1.8.0_242 and Adopt 1.8.0_242

![loginScreen](https://user-images.githubusercontent.com/1795224/79859451-570b8e00-83d1-11ea-82f8-d0409b9e6275.png)

**Comment by sclassen** [comment]
Maybe you see something in the client log. The file is named `itw-clienta-2020-04-*.log`
And should be in the same directory as the other logs.
Maybe you need to activate the log to file in the settings first.

**Comment by cedricbousmanne** [comment]
I've installed and configured itw to use the same version as yours, but still have the same issue

Heree's [the client log](https://gist.github.com/873923c5555f3cf087f79f1beac4f9c0) : i see a bunch of warning but none of them seems critical, am I right?

**Comment by sclassen** [comment]
Yes non of them are an issue. 
Does your application log anything?
There are no more log lines after the main method of your apllication is invoked.

**Comment by cedricbousmanne** [comment]
I don't see any other logs. Are they supposed to be in the same file or somewhere else?

**Comment by sclassen** [comment]
They should be in the same file.
`System.out` and `System.err` are captured an printed to the above file.
It now depends on the configuration of your logging framework. If it prints to System.out then it should be in this file. If you log using a file appender then the logs are in the directory specified by your configuration.

**Comment by cedricbousmanne** [comment]
I emptied the log folder and retried it. I now have 3 log files : 

1. [itw-clienta-2020-04-21_22:33:37.147.log](https://gist.github.com/287a62d043a7fbd204a4eb555c43517f)
2. [itw-javantx-2020-04-21_22:33:35.665.log](https://gist.github.com/287a62d043a7fbd204a4eb555c43517f)
3. [itw-javantx-2020-04-21_22:33:47.476.log](https://gist.github.com/cedricbousmanne/8d89220d65859d3564a030e25ebe412f)

The second one has an interesting line, although i'm not sure what it means : 
`[ERROR_ALL][Tue Apr 21 22:33:36 CEST 2020] Error while trying to find a remote version: www.whistenligne.be`

**Comment by sclassen** [comment]
sorry was busy today
1. and 2. point to the same gist

**Comment by cedricbousmanne** [comment]
My bad, i edited my previous comment accordingly

**Comment by sclassen** [comment]
OK, I see the line you mention.
It is not related. It comes from the JVM Manager. It is telling you, that it was not able to download the list of available JVMs from the server. Therefore it will chose a JVM which is already installed on your machine.

It looks like you have changed the URL of the server in the JVM Manager settings. If you are trying to host your own server have a look at our guide: https://github.com/karakun/OpenWebStart/blob/master/documentation/guide/OWSGuide.adoc#setup-a-custom-download-server

**Comment by cedricbousmanne** [comment]
It was not my intention, i tried a bunch of things before reaching out here. 

I reverted to what I think was the default value, but I still got the white screen after having had the prompt "pas de nouvelle version disponible pour le moment"

Here's the [updated log file](https://gist.github.com/cedricbousmanne/e6b362c7dbb65d2d0cede759c57dc2f5)

**Comment by cedricbousmanne** [comment]
Update : i retried yesterday after a full reboot and it worked. 

I have no idea how. Thanks for your time & help!

**Comment by sclassen** [comment]
Great to hear it works !!
If you are not sure about the default value you can clear the field. If no value is set the default is taken.
