### ISSUE TITLE
FirefoxPreferencesFinder.find() method does not handle absolute paths correctly

### ISSUE THREAD

**Issue by pkeusem** [AdoptOpenJDK/IcedTea-Web#629]
In looking for the Firefox preferences file: prefs.js, the FirefoxPreferencesFinder.find() method is invoked to locate and read the Firefox user profile.ini file.  The method searches the profile.ini file for the default profile section and use the value of the PATH property from that section to formulate a path to the user's pref.js file.  The PATH may be relative or absolute, this is indicated by the isRelative property for the given Profile section.  If isRelative equals 0, the path is absolute, if isRelative equals 1, the path is relative.  In the case where the PATH variable is set to an absolute path and isRelative equals 0, the method incorrectly concatenates the profile.ini path () with the value of the PATH property from the default Profile section (C:\Users\Firefox\Profiles\ql52tczi.default), resulting in an invalid path.  For example:

  C:\Users\UserID>\AppData\Roaming\Mozilla\Firefox\profile.ini:
  [Profile0]
  Name=<UserId>
  IsRelative=0
  Path=C:\Users\Firefox\Profiles\ql52tczi.default
  Default=1

The resulting prefs.js path would be:

  C:\Users\<UserId>\AppData\Roaming\Mozilla\Firefox\C:\Users\Firefox\Profiles\ql52tczi.default\prefs.j

In the case of a non-relative PATH, the value of the PATH should be used as is, without prepending the path to the profile.ini file.  Using the data from the example above:

  C:\Users\Firefox\Profiles\ql52tczi.default\prefs.j

**Comment by sclassen** [comment]
There is a new implementation for proxy in https://openwebstart.com
Can you try this.
We plan on migrating the proxy implementation over to IcedteaWeb in the future

**Comment by pkeusem** [comment]
I responded to this via email on May 8, but that apparently did not make it here.

What is the proxy?
Where can I find it on [https://openwebstart.com]?
How is the proxy related to locating the Firefox preferences file?

**Comment by sclassen** [comment]
Sorry I guess my response was a little short.
OpenWebStart re-implemented the section of ITW which reads the proxy settings.
This new implementation supports more options (some OS specific) to read proxy settings.

OpenWebStart is an application based on ITW and offers some additional features on top.

**Comment by pkeusem** [comment]
OK, so is this OpenWebStart 1.1.7 you are talking about?

**Comment by sclassen** [comment]
yes

**Comment by pkeusem** [comment]
OK, thanks.

**Comment by hendrikebbers** [comment]
The new Proxy in OpenWebStart will support absolute path in Firefox with the next release. See https://github.com/karakun/OpenWebStart/pull/275
