### ISSUE TITLE
Windows desktop shortcut with null target

### ISSUE THREAD

**Issue by zalexeev** [AdoptOpenJDK/IcedTea-Web#640]
I running Java Swing Application with Java Web Start (jnlp). Jnlp contains configuration which creates windows desktop shortcut for our application.
  <shortcut>      
		   <desktop/>      
          <menu submenu="app name"/>
  </shortcut>     

Shortcut created with Oracle jdk have target like this:
"C:\Program Files (x86)\Java\jre1.8.0_181\bin\javaws.exe" -localfile "C:\Users\zalexeev\AppData\LocalLow\Sun\Java\Deployment\cache\6.0\0\20a23d80-2f62589e"

and working properly.

Shortcut created with AdoptOpenJdk 8 have target 
"C:\Program Files\AdoptOpenJDK\jre-8.0.252.09-hotspot\bin\javaws.exe" "null"

and not working.

Please help to solve this issue.

**Comment by sclassen** [comment]
please attach the JNLP file.

**Comment by zalexeev** [comment]
[netxplorer.jnlp.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4645078/netxplorer.jnlp.txt)

**Comment by sclassen** [comment]
The JNLP looks good. So I have more questions:
- do you see any exceptions in the log? make sure to turn on logging to file and debug in the settings
- is there a different version of the JNLP at http://10.110.108.180/netxplorer.jnlp  ?

**Comment by zalexeev** [comment]
I turned on logging and debug and see a lot of exceptions. I working with Chrome browser and in the log it write not found Firefox settings. I tried to work with with IE and Firefox, problem is the same. Log file attached.
[itw-javantx-2020-05-20_08_46_03.398.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4654903/itw-javantx-2020-05-20_08_46_03.398.log)

**Comment by sclassen** [comment]
The error message about firefox is only related to proxy. ITW is trying to read the proxy settings from firefox profile. You can change the proxy settings in ITW to make this exception go away.
The rest of the exceptions are class not found. Unfortunately ITW 1.8 is very verbose on debug. Especially the class loader.

What is more interesting is that on line 31 there is no `href` attribute in the `<jnlp>` tag.
This could be causing the null in the shortcut

**Comment by zalexeev** [comment]
Thank you! Now it's works. It was no href in the jnlp
