### ISSUE TITLE
3rd party JNLP not running

### ISSUE THREAD

**Issue by SubHuman1963** [AdoptOpenJDK/IcedTea-Web#649]
Hi all,
I'm moving from Java to OpenJDK (build 1.8.0_232-b09) in combination with Ice Tea Web (1.7.1). OpenJDK will be used to support Java based Webconsoles. Got 1 running without (all to many) problems, the other won't start. Get the splash screen, ice fills up, but nothing happens. See exception in the DOS box:

java.lang.VerifyError: Final superclass netscape/javascript/JSObject can't be extended 

Exception in thread "Launch the Management Console with Java Web Start" java.lang.RuntimeException: java.lang.VerifyError: Final superclass netscape/javascript/JSObject can't be extended

Added the environment settings and complete exception as txt files.

Any thoughts?

Kind regards 
Marco

[run.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4702215/run.txt)
[env.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4702216/env.txt)

**Comment by hendrikebbers** [comment]
Hi @SubHuman1963 
can you try your application with ITW 1.8.x and send us the created log files. File logging can be activated in the settings of ITW.

**Comment by SubHuman1963** [comment]
Hi Hendrik,
Thanks for your reply!
I reverted to 1.7.1 because I encountered the following error while starting a jnlp file in IE:
net.sourceforge.jnlp.LaunchException: Fatal: Launch Error: Could not launch JNLP file. The application has not been initialized, for more information execute javaws/browser from the command line and send a bug report.
Also in IE an IFramed applet does not show.

So I set up Chrome and 1.7.1. with regards to your question I removed 1.7.1 and reinstalled 1.8.3

I'm attaching 6 files. 
3 starting with 'mc-' fail, itw is starting but the jnlp never shows
3 starting with 'vpmlauncher-' fail, itw is starting, the jnlp fails with 'Caused by: java.lang.NoClassDefFoundError: bluecoat.sgos.ui.MCInterface'

I'll revert to 1.7.1. again and try to get the logs for the same actions.

Thanks in advance

Kind regards,
Marco

[vpmLauncher-itw183-clienta-2020-06-03_08_31_34.671.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4721669/vpmLauncher-itw183-clienta-2020-06-03_08_31_34.671.log)
[vpmLauncher-itw183-javantx-2020-06-03_08_31_31.77.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4721670/vpmLauncher-itw183-javantx-2020-06-03_08_31_31.77.log)
[vpmLauncher-itw183-nativerustlauncher-1591165889.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4721671/vpmLauncher-itw183-nativerustlauncher-1591165889.log)
[mc-itw-clienta-2020-06-03_08_39_40.777.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4721672/mc-itw-clienta-2020-06-03_08_39_40.777.log)
[mc-itw-javantx-2020-06-03_08_39_17.358.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4721673/mc-itw-javantx-2020-06-03_08_39_17.358.log)
[mc-itw-nativerustlauncher-1591166356.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4721674/mc-itw-nativerustlauncher-1591166356.log)

**Comment by SubHuman1963** [comment]
Sorry, wrong button...

Uploading the 1.7.1 logfiles. 
Starting with 'chrome-mcitw171-': fail, itw is starting but the jnlp never shows
Starting with '*-vpmlauncher-itw171' actually work (apparently fine)

**Comment by SubHuman1963** [comment]
[IE-vpmLauncher-itw171-javantx-2020-06-03_10_27_33.854.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4734241/IE-vpmLauncher-itw171-javantx-2020-06-03_10_27_33.854.log)
[IE-vpmLauncher-itw171-javantx-2020-06-03_10_30_03.946.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4734242/IE-vpmLauncher-itw171-javantx-2020-06-03_10_30_03.946.log)
[chrome-mc-itw171-clienta-2020-06-03_10_21_59.398.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4734243/chrome-mc-itw171-clienta-2020-06-03_10_21_59.398.log)
[chrome-mc-itw171-javantx-2020-06-03_10_21_55.727.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4734244/chrome-mc-itw171-javantx-2020-06-03_10_21_55.727.log)
[chrome-vpmLauncher-itw171-clienta-2020-06-03_10_19_36.191.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4734245/chrome-vpmLauncher-itw171-clienta-2020-06-03_10_19_36.191.log)
[chrome-vpmLauncher-itw171-javantx-2020-06-03_10_14_31.279.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4734246/chrome-vpmLauncher-itw171-javantx-2020-06-03_10_14_31.279.log)
[chrome-vpmLauncher-itw171-javantx-2020-06-03_10_19_32.518.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4734247/chrome-vpmLauncher-itw171-javantx-2020-06-03_10_19_32.518.log)
[IE-vpmLauncher-itw171-clienta-2020-06-03_10_27_37.405.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4734248/IE-vpmLauncher-itw171-clienta-2020-06-03_10_27_37.405.log)

**Comment by hendrikebbers** [comment]
@SubHuman1963 let's concentrate on the issues that you have with 1.8.x

Issue a: `java.lang.VerifyError: Final superclass netscape/javascript/JSObject can't be extended`
Issue b: `java.lang.NoClassDefFoundError: bluecoat.sgos.ui.MCInterface`

- What is the difference between issue a and issue b? Did you just started the same application in the same way 2 times after each other or have you done something different?
- Are you using a PAC based proxy?
- Are you using JavaScript in your application?
- I assume the `bluecoat.sgos.ui.MCInterface` class is part of your application and you can find it in one of the JARs. Correct?

Next to this can you please give [OpenWebStart](https://openwebstart.com) a try? This free tool uses a newer version of ITW internally. For this version (2.x) we do not have a ITW release now but plan to release it in near future. Would be good to know if your application can be started with OpenWebStart.

**Comment by SubHuman1963** [comment]
Hi Hendrik,
Issues a and b differ, 
issue a is launching a standalone jnlp file (vpmlauncher.jnlp) from within a html page
issue b is framing a different jnlp file (mc.jnlp) in a html page

Not using a proxy, nor a PAC file. All resources are local.

There is .js in the page

All classes used in the application are found in the jars

Furthermore, I gave OpenWebStart a try after deinstalling ITW1.7.1 / ITW1.8.3
[itw-javantx-2020-06-08_09_40_51.379.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4744559/itw-javantx-2020-06-08_09_40_51.379.log)
[itw-javantx-2020-06-08_09_40_51.379.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4744562/itw-javantx-2020-06-08_09_40_51.379.log)

, got 'No suitable JVM was found to start the application'
java.lang.IllegalStateException: could not find any suitable runtime
	at com.openwebstart.launcher.OwsJvmLauncher.getLocalJavaRuntimeOrExit(OwsJvmLauncher.java:74)
	at com.openwebstart.launcher.OwsJvmLauncher.launchExternal(OwsJvmLauncher.java:125)
	at com.openwebstart.launcher.OwsJvmLauncher.launchExternal(OwsJvmLauncher.java:68)
	at net.sourceforge.jnlp.Launcher.launchExternal(Launcher.java:284)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:365)
	at net.sourceforge.jnlp.Launcher.access$200(Launcher.java:69)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:651)

I'll upload the log

**Comment by sclassen** [comment]
The exception you see is caused by a connection timeout.
OWS is trying to download a suitable JVM to run the application. In order to do so it connects to https://download-openwebstart.com/jvms which then ends in a connection timeout.

Do you need to configure some proxy settings to connect to the internet?

If you cannot connect to the internet you can open the settings UI and add a localy installed JVM in the JVM manager

**Comment by SubHuman1963** [comment]
Hi sclassen,
Thnx, I wasn't aware of that... Whitelisted download.openwebstart.com in our proxy. I did download a JVM (download-openwebstart.com/Azul/zulu11.37.17-ca-jdk11.0.6-win_x64.zip) but crashed all the same. I'll append the logs.

Furthermore, I tried to add a local JVM from my AdoptOpenJDK installation directory, but I was unable to do so, as the browse dialog didn't show the jvm.dll (picture appended).
![jvm](https://user-images.githubusercontent.com/66125106/84501743-50a1e000-acb7-11ea-8aca-4e1eb6e99c50.png)
[itw-clienta-2020-06-12_13_49_44.585.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4770637/itw-clienta-2020-06-12_13_49_44.585.log)
[itw-javantx-2020-06-12_13_48_37.734.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4770638/itw-javantx-2020-06-12_13_48_37.734.log)

**Comment by sclassen** [comment]
if you want to add a JVM manually you should select the parent folder of the JVM.

The error in your log is class not found: `javafx.embed.swing.JFXPanel`
Is your application a JavaFX one? if so you need to be aware that not all the JVMs include JavaFX

**Comment by sclassen** [comment]
May be related to https://github.com/karakun/OpenWebStart/issues/125

**Comment by Jamila891** [comment]
@SubHuman1963 does this issue still occure? It might have been fixed with the latest release. If so, we will close this issue.

**Comment by SubHuman1963** [comment]
Hi all, sorry, haven't updated this issue for a while. As we were informed by the 3rd party they will be investigating this issue at their side. So I'll be closing this one. Many thanks to all who replied and gave some usefull suggestions and insight.
