### ISSUE TITLE
JNLPFileFactory runs into NullPointerException after proxy settings where wrong

### ISSUE THREAD

**Issue by FelixJongleur42** [AdoptOpenJDK/IcedTea-Web#654]
see https://github.com/karakun/OpenWebStart/issues/226

to sum up:

1. first jnlp download fails due to wrong proxy settings
2. correct proxy settings
3. second jnlp download will fail with NPE in JNLPFileFactory

note that browser is able to download JNLP file

**Comment by hendrikebbers** [comment]
closed since this is duplicate to karakun/OpenWebStart#226
