### ISSUE TITLE
Could not parse or read the JNPL file

### ISSUE THREAD

**Issue by hostafrica** [AdoptOpenJDK/IcedTea-Web#657]
Hi Team,
we regularly hitting the same error when connecting via IcedTea trough the Proxy to IPMI console on our dedicated servers. We have problems to replicate the issue. For some servers all is fine for some not.
![image](https://user-images.githubusercontent.com/44834090/84074228-82bef380-a9d2-11ea-8ea5-704919d7160a.png)

Are you able to help on this?

Regards
M.

**Comment by sclassen** [comment]
Which version of ITW are you using?

**Comment by hostafrica** [comment]
Its Version 1.8

**Comment by patris70** [comment]
Hi,
have you configured SSL intercept in proxy?
If yes, disable SSL intercept for your link/URL.

regards

**Comment by Jamila891** [comment]
@hostafrica is this issue still open? If yes, can you please attach the JNLP file.
