### ISSUE TITLE
icedtea-web 1.8.3 is this supporting jdk11?

### ISSUE THREAD

**Issue by GKNEKKANTI** [AdoptOpenJDK/IcedTea-Web#662]
as per migration guide given in adoptopenjdk page  https://adoptopenjdk.net/migration.html?variant=openjdk11&jvmVariant=openj9
icedtea-web is not supported for jdk11.

Please confirm whether the icedtea-web 1.8.3 supports jdk 11 officially or not.
Thank you so much.

**Comment by sclassen** [comment]
There is some code in place but I guess we cannot say it is "officially" supported.
So go ahead and give it a try.

Also have a look at openwebstart.com it adds additional support for Java11 on top of ITW

**Comment by hendrikebbers** [comment]
https://github.com/AdoptOpenJDK/openjdk-website/issues/734

**Comment by hendrikebbers** [comment]
PR https://github.com/AdoptOpenJDK/openjdk-website/pull/745
