### ISSUE TITLE
Open JDK WebStart showing -  Wrong Publisher(EMC) and Expired security certificates 

### ISSUE THREAD

**Issue by rchandrabrcm** [AdoptOpenJDK/IcedTea-Web#666]
Platform : Windows 

OpenJDK  Version : 1.8.0.242.08 (OpenJDK8U-jre_x64_windows_hotspot_8u242b08)

Tested with Oracle Jre (1.8.0_X), here there is no issue

* **Steps to reproduce**:
- Install OpenJDK and Webstart part of 1.8.0.242.08
- Launch .jnlp file 
- Showing Wrong Publisher(EMC) and Expired security certificates 

* **Error messsage and/or description of what is not working as expected**:

**With OpenJDK WebStart**
=================

![Wrong_Publisher](https://user-images.githubusercontent.com/67726756/86349964-9121c780-bc7f-11ea-9c6c-04fd6e39c707.png)

![degital_signature_expired](https://user-images.githubusercontent.com/67726756/86350160-e8c03300-bc7f-11ea-9ed3-8dfad61923e3.png)

![EMC_Expired_Certificate](https://user-images.githubusercontent.com/67726756/86350325-20c77600-bc80-11ea-9711-8866d5648911.png)

![JCE_Expired_Certificate](https://user-images.githubusercontent.com/67726756/86350330-2329d000-bc80-11ea-84e7-f2c378af6846.png)

**With Oracle JRE**
=============
![Oracle_JRE_Publisher](https://user-images.githubusercontent.com/67726756/86350779-d2ff3d80-bc80-11ea-95b5-d52f946db734.png)

![CA_Certificate_Validity](https://user-images.githubusercontent.com/67726756/86350790-d692c480-bc80-11ea-91ef-90a0a3a90e52.png)

![Semantic_Certificate_Validity](https://user-images.githubusercontent.com/67726756/86350802-dabee200-bc80-11ea-94fc-60f658e96d05.png)

![Verisign_Expired_Validity](https://user-images.githubusercontent.com/67726756/86350805-de526900-bc80-11ea-8de3-fc1806cbf57b.png)

================================

Please note this issue is with only openJDK and but not Oracle JRE.
Oracle JRE showing publisher and Certificates properly .

Could you Please help on this.

**Comment by sclassen** [comment]
Could you share the JNLP file. This helps understanding why the publisher is different.

For the Certificate we can do very little.
ITW only uses the certificates provided (by the JVM and the local trust store)
It does not handle any certificates itself

**Comment by rchandrabrcm** [comment]
Thanks for the update.
Oracle JRE taking correct certificates, but not openJDK, i am not sure, is any settings required explicitly. 

Here is the my JNLP content.
[oneclick _OC_JNLP.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4864260/oneclick._OC_JNLP.txt)

**Comment by sclassen** [comment]
Interesting. The JNLP does not contain any of the strings which are visible in the first screen shot.
Are there any other applications launched?

**Comment by rchandrabrcm** [comment]
No, only we have one application which need to launch using .JNLP file

**Comment by rchandrabrcm** [comment]
Any help on this please ....

**Comment by sclassen** [comment]
Can you please post the log files from running the app with ITW

**Comment by rchandrabrcm** [comment]
I am sorry, what is ITW  ?
Can you please help, how to run/launch application(.JNLP) using  ITW ? 
Could you Please help

**Comment by rchandrabrcm** [comment]
Any update please ....

**Comment by sclassen** [comment]
ITW is the short form for icedtea-web.
If you open the settings you can enable logging to file and debug logs.
Also in that view you see where log files are located on your file system

Please create a set of log files by enabling the above options and then launch your application

**Comment by rchandrabrcm** [comment]
Thanks for the update.

When I tried to launch icedtea-web, it is directly opening, i could not see any settings.

Could you please provide screenshot and steps, how to enable debug and collect logs.

Thanks
Channa

**Comment by sclassen** [comment]
there is a separate executable in the same folder as the javaws executable. You need to start this to open the settings

**Comment by rchandrabrcm** [comment]
Thank you.

I have enabled the the debug,  below the screenshot of icedtea-web console 
![image](https://user-images.githubusercontent.com/67726756/86891563-aa61c280-c11c-11ea-95e3-d773d48bbdff.png)

Please find the log files below from path (C:\Users\Administrator\.config\icedtea-web)
[log.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4889192/log.zip)

Please review and help.

Regards
Channa

**Comment by rchandrabrcm** [comment]
Please let me know if you need any information

**Comment by rchandrabrcm** [comment]
icedtea-web console debug

[openJDKWeb_Debug_Console.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4889718/openJDKWeb_Debug_Console.txt)

**Comment by hendrikebbers** [comment]
I had a quick look in the log.
I do not think that your problem is based on it but the following line in your JNLP looks wrong:
`<j2se version="1.8.0_232" java-vm-args="--add-modules=java.se.ee" href="http://java.sun.com/products/autodl/j2se" initial-heap-size="96m" max-heap-size="1024m"></j2se>`

You are using Java 8 but defining `--add-modules=java.se.ee` that is only available in Java 9+. You should remove that :)

**Comment by hendrikebbers** [comment]
I found a ClassNotFound Exception:
`java.lang.ClassNotFoundException: com.aprisma.spectrum.app.alarm.client.render.LinkDownInterfaceListRendererCustomizer`

Can you please doublecheck that the class in part of the JARs.

**Comment by hendrikebbers** [comment]
mmmh, IcedTeaWeb tries to download this classes directly from your server:
`Selecting proxy for: http://10.17.153.216/spectrum/com/aprisma/spectrum/app/alarm/client/render/LinkDownInterfaceListRendererCustomizer.class`

**Comment by hendrikebbers** [comment]
I do not assume that `<property name="javaws.cfg.jauthenticator" value="true"></property>` is supported by IcedTeaWeb.

**Comment by hendrikebbers** [comment]
Can you explain what the` ;no_javaws_cheat` suffix does?

**Comment by hendrikebbers** [comment]
Are you an user of the JNLP application or are you the developer?

**Comment by rchandrabrcm** [comment]
Thanks for update.

Please note that, same JNLP file is working fine with Oracle Jre (1.8.0_X)

Here issue is, Why it is showing Publisher as "EMC Corporation" and showing expired certificates.

Do we need to change anything and test it ? please help

Thanks
Channa

**Comment by sclassen** [comment]
regarding the certs:
```
CN=VeriSign Universal Root Certification Authority,OU=(c) 2008 VeriSign\, Inc. - For authorized use only,OU=VeriSign Trust Network,O=VeriSign\, Inc.,C=US found in cacerts (C:\Program Files\AdoptOpenJDK\jre-8.0.242.08-hotspot\lib\security\cacerts)
CN=CA INC,OU=78615,O=CA INC,L=Islandia,ST=New York,C=US found in cacerts (C:\Users\Administrator\.config\icedtea-web\security\trusted.certs)
```

**Comment by sclassen** [comment]
concerning the tile:
`EMC Corporation` cannot be found in any log.
Can you check the main jar `clientconsole.jar` and see if its MANIFEST.FM contains this string

**Comment by rchandrabrcm** [comment]
Below the my MANIFEST.MF file content
==========================
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.9.4
Permissions: all-permissions
Codebase: *
Spectrum-Version: 10.4.1.0.215
Created-By: 1.8.0_232-b09 ()

Name: com/aprisma/spectrum/app/console/client/ConsoleApp$1.class
SHA-256-Digest: SaIftccB+MGbExu6/dVMzAfJxUNmUhqOD3dRE/ssECE=

Name: com/aprisma/spectrum/app/console/client/package_ja_JP.properties
SHA-256-Digest: AHVIUFYW4c277jsocOoGf2Jbe5/vo49eXaPVgIHcejU=

Name: com/aprisma/spectrum/app/console/common/ContextDefs.class
SHA-256-Digest: On+WlbowCGHF2ZoYackepw/JOjiSEa/XjHlQva8Oo+Q=

Name: com/aprisma/spectrum/app/console/client/package_zh_TW.properties
SHA-256-Digest: nGOuqlUL79+pu0F9ILqbqj05gxwHc0+FHalkFxUsCoQ=

Name: com/aprisma/spectrum/app/console/client/ConsoleView$TwoPanelNavi
 gationClonedView.class
SHA-256-Digest: FEn+z0oUi+QDbzVMcZB5usk5QYJkmvcSNzxTpDEvm9E=

Name: com/aprisma/spectrum/app/console/client/ConsoleView.class
SHA-256-Digest: S8aho1E2BCjZ2deNH40Wat/d2Uu3DrHmHIpz/PRy0U0=

Name: com/aprisma/spectrum/app/console/client/package_en_US.properties
SHA-256-Digest: jnvHHkhCyHusmcC3aOMnLcLPKIuSfMP7sCihIGDEDTA=

Name: com/aprisma/spectrum/app/console/client/ConsoleApp$SwingContextC
 hange.class
SHA-256-Digest: QuaH+Xm/KJL67sF20BAnVmIZUfsdwcEZuyozt1TriBI=

Name: com/aprisma/spectrum/app/console/common/Privileges.class
SHA-256-Digest: Tr3YwipvFO86mTbcDgwFlx6h9MLpX7SSYZnFEntuhz0=

Name: com/aprisma/spectrum/app/console/client/ConsoleApp$ClonedViewPre
 f.class
SHA-256-Digest: iTh4WOky3Bq3yynB7czBbrEh3Hk8KRbk+FK01XeTwRY=

Name: com/aprisma/spectrum/app/console/client/ConsoleApp$4.class
SHA-256-Digest: 7NVCUp7CwMJNxWeM99KAFSYFhcX48jNd5JiMIMkHdTs=

Name: com/aprisma/spectrum/app/console/client/ConsoleView$TwoPanelNavi
 gationUndockedView.class
SHA-256-Digest: lRlgaFzEmqJtYZ1/fTm+0tqEi1amRU81j3yxvsTR8Lg=

Name: com/aprisma/spectrum/app/console/client/package_zh_CN.properties
SHA-256-Digest: KmcV8Q7YqvnF5f1UjdxTyMDr3cpi1xY03jdlRvHO6XY=

Name: com/aprisma/spectrum/app/console/client/ConsoleApp$3.class
SHA-256-Digest: LFTSBGZZxi6+cm20m0mQmYeVw+IxzJbbU8+DTA0TFrU=

Name: com/aprisma/spectrum/app/console/client/ConsoleApp$2.class
SHA-256-Digest: wKFq1odwBUbmq7tD2p6aMekXtK6J1TJpjuWaMyI15So=

Name: com/aprisma/spectrum/app/console/client/ConsoleApp.class
SHA-256-Digest: kqQN9lgDPAqr6WiKv+hBoKaAKd6SMhxh4TPCbx8cBmQ=

===================================================

**Comment by rchandrabrcm** [comment]
In our case, showing expired certificates. Could you please see the provided screenshots  previously .

**Comment by rchandrabrcm** [comment]
I could not get, why publisher showing "EMC Corporation" and showing expired certificates, but this is not the case of Oracle JRE
do we need to any setting/changes in ..JNLP file ? Could you please help...

**Comment by janakmulani** [comment]
Can you please try your application with [OpenWebStart](https://github.com/karakun/OpenWebStart)?

**Comment by rchandrabrcm** [comment]
I have tested on OpenWebStart as well,  but getting same issue. Could you please suggest next steps.

**Comment by hendrikebbers** [comment]
@rchandrabrcm this looks like a general bug in ITW. To be true I do not have a good idea how to start finding this bug without reproducing the error. Is it possible to create a small JNLP based application that reproduces the behaviour?

**Comment by rchandrabrcm** [comment]
As Hendrik suggested, I have removed below 2 lines in JNLP file, but still getting same error.
============
<property name="javaws.cfg.jauthenticator" value="true" />

    <j2se version="1.8.0_232" java-vm-args="--add-modules=java.se.ee" href="http://java.sun.com/products/autodl/j2se"
          initial-heap-size="96m" max-heap-size="1024m"/>
============

**Comment by rchandrabrcm** [comment]
As Hendrik suggested, I have removed below 2 lines in JNLP file, but still getting same error.
============================
<property name="javaws.cfg.jauthenticator" value="true" />
<j2se version="1.8.0_232" java-vm-args="--add-modules=java.se.ee" href="http://java.sun.com/products/autodl/j2se"
      initial-heap-size="96m" max-heap-size="1024m"/>
==========================

**Comment by rchandrabrcm** [comment]
As Hendrik suggested, I have removed below 2 lines in JNLP file, but still getting same error.

<property name="javaws.cfg.jauthenticator" value="true" />
<j2se version="1.8.0_232" java-vm-args="--add-modules=java.se.ee" href="http://java.sun.com/products/autodl/j2se"
          initial-heap-size="96m" max-heap-size="1024m"/>

**Comment by rchandrabrcm** [comment]
<property name="javaws.cfg.jauthenticator" value="true" />
    <j2se version="1.8.0_232" java-vm-args="--add-modules=java.se.ee" href="http://java.sun.com/products/autodl/j2se"
          initial-heap-size="96m" max-heap-size="1024m"/>

**Comment by hendrikebbers** [comment]
I assumed that this won't help with your concrete problems but I would remove this lines anyway since they are just wrong.  Based on the given information I do not know how we can help you since we are not able to reproduce this issue. Is the application available online so that we can check the JNLP app?

**Comment by rchandrabrcm** [comment]
There is one observation

We have 2 products OC and SOI
Tried to launch both from same java version i.e OpenJDK Version : 1.8.0.232.08 (OpenJDK8U-jre_x64_windows_hotspot_8u232b09)
But this issue (Wrong Publisher and expired certificates)  exists for OC, but not for SOI

SOI JNLP file below (Working Product)
=============================
[SOI_JNLP.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4933127/SOI_JNLP.txt)

OC JNLP file below (Issue exists for Product)
===============================
[OC_JNLP.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4933152/OC_JNLP.txt)

Could you please help on this.

**Comment by hendrikebbers** [comment]
Since this is not working with ITW and OpenWebStart I would like to open an additional issue in OpenWebStart and link both. By doing the members of both communities can help you. @rchandrabrcm can you please open an additional issue at [OWS](https://github.com/karakun/OpenWebStart/issues). I will take care of linking both issues and getting more people on it :)

**Comment by Jamila891** [comment]
@rchandrabrcm is this issue still open?
