### ISSUE TITLE
Not able to run jnlp file using Java 11

### ISSUE THREAD

**Issue by neelambatra** [AdoptOpenJDK/IcedTea-Web#667]
I am trying to launch JNLP file using openwebstart. I have configured the java version as 11.0* in my JNLP file so that openwebstart downloads 11.* JVM version. I can see that "11.0.7 Azul Systems"  got downloaded in the JVM Manager but the launching of the application fails. When I checked the logs it says as below:

[MESSAGE_DEBUG][Thu Jul 02 05:26:56 PDT 2020] Exiting Boot.mainWithReturnCode() with 0
[MESSAGE_DEBUG][Thu Jul 02 05:26:56 PDT 2020] Release shared lock on C:\Users\ADMINI~1\AppData\Local\Temp\2\Administrator\netx\locks\netx_running
[MESSAGE_ALL][Thu Jul 02 05:26:56 PDT 2020] No other instances of javaws are running

The same works fine with Java 8, same I tested by changing the java version to 1.8* in my jnlp file which downloaded "1.8.0.252 Azul Systems" JVM.

Can someone give me the pointers what can be the issue? I am attaching the log file for reference.
[itw-javantx-2020-07-02_05_26_55.72.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4864241/itw-javantx-2020-07-02_05_26_55.72.log)

**Comment by sclassen** [comment]
Ther is a second log file which was created just about the same time.
It contains further details. Can you please post this also. thx

**Comment by neelambatra** [comment]
No I don't see any other log file at the same time. Do I need to enable any logging somewhere. As of now I have checked all the boxes available under logging.

Thanks

**Comment by neelambatra** [comment]
Got the attached log file created after some time. Please check.

Thanks
[itw-javantx-2020-07-02_09_08_14.64.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4867858/itw-javantx-2020-07-02_09_08_14.64.log)

**Comment by hendrikebbers** [comment]
The attached log is based on opening the settings of OWS. Can you clear the log folder and restart the application. That should create log files.

**Comment by neelambatra** [comment]
As suggested above, I have deleted all the logs from log directory and re-launched jnlp with 11.0* Java version. I have attached the logs which I got.

Thanks
[itw-javantx-2020-07-03_04_07_54.654.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4869387/itw-javantx-2020-07-03_04_07_54.654.log)
[itw-javantx-2020-07-03_04_04_46.285.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4869389/itw-javantx-2020-07-03_04_04_46.285.log)

**Comment by sclassen** [comment]
The attached logs are still not helpful:
the file `itw-javantx-2020-07-03_04_07_54.654.log` is another log of the startup phase of OWS.
the file `itw-javantx-2020-07-03_04_04_46.285.log` is a log from opening the settings and deleting 2 azul JVMs

When OWS is launched its is doing this in 2 phases.
First we have a startup phase (or phase 1) where it determines which JVM to use for launching the application.
You have provided us two logs of this phase. They both contain no error information
Then we have the application phase (or phase 2) where the application is started in a new JVM instance.
Most likely something is going wrong here. But so far you have not posted any logs from this phase.

Can you please give it another try by clearing the log folder and *only* start the application once.
Do not start the settings or other jnlp applications.

**Comment by neelambatra** [comment]
Ok, I have tried again, without opening the settings but I can see only one log file getting created, attaching the same.
[itw-javantx-2020-07-03_23_52_44.765.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4872223/itw-javantx-2020-07-03_23_52_44.765.log)

Is it possible to have a call to see what's going wrong and why the 2nd log file is not getting generated.

**Comment by sclassen** [comment]
We offer calls only for our payed support customers.
Youfind details for the payed support on https://openwebstart.com

I will look into the log one more time but so far there are no obvious errors in there

**Comment by neelambatra** [comment]
Hello,

We don't have paid support but I am really looking forward for some help in resolving this issue.

Regards

**Comment by hendrikebbers** [comment]
I close this issue and create a new one in the OpenWebStart repository since the topic is related to OpenWebStart. See https://github.com/karakun/OpenWebStart/issues/287
