### ISSUE TITLE
javaws about Exception

### ISSUE THREAD

**Issue by vladimir-kokovic** [AdoptOpenJDK/IcedTea-Web#668]
How is it possible for 'javaws about' to generate Exception?
[owsabout.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4865419/owsabout.log)

**Comment by janakmulani** [comment]
What info are you looking for by passing the "about" parameter?

From the log it appears that ITW is trying to bring up AboutDialog and failing. Perhaps this is not supported or has a bug as it is resulting in NPE.

For IcedTeaWeb you could try itweb-settings.sh > About IcedTea-Web > About


You can try OpenWebStart itw.settings > About OpenwebStart.

You can also try javaws -console to see the messages on console.

**Comment by vladimir-kokovic** [comment]
I don't know how to apologize to the people from "AdoptOpenJDK IcedTea-Web" for asking the question because in it, it was checked that 'javaws -about' works correctly.
My problem was that I tried a 'javaws -about' from 'OpenWebStart' javaws, in which it doesn't work without me being aware that there are 2 javaws scripts.

**Comment by sclassen** [comment]
Do not worry, OpenWebStart and icedtea-web are maintaind by the same people.
And yes OpenWebStart targets more GUI and less the console
