### ISSUE TITLE
Getting error while trying to launch using IcedTea Web

### ISSUE THREAD

**Issue by rchandrabrcm** [AdoptOpenJDK/IcedTea-Web#676]
Adopt Open JDK : OpenJDK8U-jre_x64_windows_hotspot_8u232b09

![image](https://user-images.githubusercontent.com/67726756/87664696-517cd480-c783-11ea-9914-db0484847248.png)

**Comment by rchandrabrcm** [comment]
Found missing the 'permissions' attribute in the Iced-web log as below
======================================
Decided action for missing permissions at http://10.17.153.216/spectrum/ was YES
Your Extended applets security is at 'high' and this application is missing the 'permissions' attribute in manifest. And you have allowed to run it.
Found alaca URLs to be verified
 - http://10.17.153.216/spectrum
 - http://10.17.153.216/spectrum/lib
OK - http://10.17.153.216/spectrum is from codebase/docbase.
OK - http://10.17.153.216/spectrum/lib is from codebase/docbase.
All applications resources (http://10.17.153.216/spectrum) are from codebas/documentbase http://10.17.153.216/spectrum//http://10.17.153.216/spectrum/, skipping Application-Library-Allowable-Codebase Attribute check.
Entry-Point can not be checked now, because of not existing launch info.
Application title was not found in manifest. Check with application vendor
Acceptable title tag found, contains: DX NetOps Spectrum OneClick Console
Activate jar: file:/C:/Users/Administrator/.cache/icedtea-web/cache/188/http/10.17.153.216/spectrum/lib/cryptojFIPS.jar_no_javaws_cheat
Activate native: http://10.17.153.216/spectrum/lib/cryptojFIPS.jar;no_javaws_cheat
Permission added: ("java.io.FilePermission" "C:\Users\Administrator\.cache\icedtea-web\cache\188\http\10.17.153.216\spectrum\lib\cryptojFIPS.jar_no_javaws_cheat" "read")
Finding best URL for: http://10.17.153.216/spectrum/lib/clientconsole.jar;no_javaws_cheat : DownloadOptions[use pack: false; use version: false]
All possible urls for location=http://10.17.153.216/spectrum/lib/clientconsole.jar;no_javaws_cheat state=PRECONNECT CONNECTING PREDOWNLOAD PROCESSING : [https://10.17.153.216/spectrum/lib/clientconsole.jar;no_javaws_cheat, 





https://10.17.153.216/spectrum/lib/clientconsole.jar;no_javaws_cheat, http://10.17.153.216/spectrum/lib/clientconsole.jar;no_javaws_cheat, http://10.17.153.216/spectrum/lib/clientconsole.jar;no_javaws_cheat]
Connecting https://10.17.153.216/spectrum/lib/clientconsole.jar;no_javaws_cheat
Adding sun.net.www.protocol.https.DelegateHttpsURLConnection:https://10.17.153.216/spectrum/lib/clientconsole.jar;no_javaws_cheat
done https://10.17.153.216/spectrum/lib/clientconsole.jar;no_javaws_cheat
Selecting proxy for: https://10.17.153.216/spectrum/lib/clientconsole.jar;no_javaws_cheat

**Comment by rchandrabrcm** [comment]
JNLP File
=======

[oneclick _OC_JNLP.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4931125/oneclick._OC_JNLP.txt)

**Comment by rchandrabrcm** [comment]
We have below entry in main jar and corresponding tags in JNLP file
MANIFEST.MF
==
Permissions: all-permissions
==
.JNLP file
=============
  <security>
    <all-permissions/>
  </security>
==============

Do we need entry in all *.jars or only main jar ? 
if required for all jars, how to identify which jar is missng permissions attribute.

Please help

**Comment by rchandrabrcm** [comment]
In my JNLP file, we have entry "all-permissions" like below

 <security>
    <all-permissions/>
</security>

**Comment by rchandrabrcm** [comment]
Do we need entry "Permissions: all-permissions"  in all *.jars or only main jar only?
if required for all jars, how to identify which jar is missing permissions attribute.

Please help

**Comment by hendrikebbers** [comment]
@rchandrabrcm can you maybe contact me by mail. Maybe we can do a call.

**Comment by Jamila891** [comment]
@rchandrabrcm any update here?

**Comment by andreiacsantos** [comment]
I am also having this warning for our application and we do have "Permissions: all-permissions" on our manifest. Do you know if there is any way of solving this problem?
