### ISSUE TITLE
The "icedtea-netx" package does not include the Firefox "IcedTeaPlugin.so" plugin.

### ISSUE THREAD

**Issue by 49studebaker** [AdoptOpenJDK/IcedTea-Web#677]
The "icedtea-netx" package does not include the Firefox "IcedTeaPlugin.so" plugin.

**Comment by janakmulani** [comment]
Which version IcedTeaWeb are you using?

New versions of IcedTeaWeb do not support Applets in browsers.

**Comment by 49studebaker** [comment]
I am using the version 1.7.2-2 (stable). 
OS: Debian 10

**Comment by hendrikebbers** [comment]
Since ITW is part of AdoptOpenJDK we never supported the Applet Plugin for Firefox. Maybe @judovana can give you a hind where you can get it for old versions.
