### ISSUE TITLE
Provide a .editorconfig file

### ISSUE THREAD

**Issue by hendrikebbers** [AdoptOpenJDK/IcedTea-Web#681]
**🆕🐥🐶 First Timers Only**
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 

**👾 Description of the issue**
We should add a `.editorconfig` file to IcedTea-Web (ITW) . See [https://editorconfig.org/](https://editorconfig.org/) for he definition of such file. This is based on a discussion in AdoptOpenJDK/IcedTea-Web#679 and the PR contains the info how such file can be created in IntelliJ. For now we use the default formatting of IntelliJ. This should not change in future but should be backed by such `.editorconfig` for other editors and developers that have changed the default format in the IDEA.

**📋 Step by Step**
To solve this issue and contribute a fix to IcedTea-Web you should check the following step-by-step list:

🙋 Claim this issue: Comment below.
🍴 fork the repository in github by simply clicking the 'fork' button.
⤵️ check out the forked repository
🔀 create a feature branch for the issue. We do not have any naming definition for branches.
💾 Commit your changes.
🔀 Start a Pull Request.
🏁 Done 👍 Ask in comments for a review :)
🔬 If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
💥 you did it! We will merge the fix in the master of the IcedTeaWeb project.
💐 Thanks, thanks, thanks for being part as an open source contributor for IcedTeaWeb

**🤔❓ Questions**
You can join our [community chat at Slack](http://adoptopenjdk.slack.com/). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions).

**Comment by stonefix** [comment]
Please, assign to me)

**Comment by hendrikebbers** [comment]
Done. If you need any help just ask here in the issue or at our slack channel.

**Comment by stonefix** [comment]
Ok, i tried it in PR #684
