### ISSUE TITLE
ITW classloader doesn't scale well with the large number of classes

### ISSUE THREAD

**Issue by FranciscoMeloJr** [AdoptOpenJDK/IcedTea-Web#690]
Hello, doing some tests with a high number of classes, so results show a very long startup (several times slower than a direct startup without IcedTeaWeb) with local JAR paths. When the cache is not used at all, the same occurs.

**Comment by hendrikebbers** [comment]
Hi, can you provide a test scenario? a Zip for example that we can start to see the effect.

**Comment by hendrikebbers** [comment]
Next to this we have released 1.2 yesterday. It provides parallel downloads of application resources.

**Comment by Jamila891** [comment]
@FranciscoMeloJr did you test the release 1.2.1 ? Can you provide a test scenario?

**Comment by FranciscoMeloJr** [comment]
I will close this for now.
