### ISSUE TITLE
Unable to launch application using Iced Web Tea 1.8 - Zulu 

### ISSUE THREAD

**Issue by NikitaS1609** [AdoptOpenJDK/IcedTea-Web#696]
I am getting below exception while launching a java based application:

```
!SESSION 2020-09-10 11:11:39.596 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_202
java.vendor=Azul Systems, Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_IN
Command-line arguments:  -debug

!ENTRY org.eclipse.osgi 4 0 2020-09-10 11:11:48.920
!MESSAGE Bundle org.eclipse.equinox.common_3.8.0.v20160509-1230 [1] is not active.

!ENTRY org.eclipse.osgi 4 0 2020-09-10 11:11:48.932
!MESSAGE Bundle org.eclipse.core.runtime_3.12.0.v20160606-1342 [4] is not active.

!ENTRY org.eclipse.osgi 4 0 2020-09-10 11:11:48.944
!MESSAGE Bundle org.eclipse.equinox.simpleconfigurator_1.1.200.v20160504-1450 [5] is not active.

!ENTRY org.eclipse.swt.win32.win32.x86 2 0 2020-09-10 11:11:48.959
!MESSAGE Could not resolve module: org.eclipse.swt.win32.win32.x86 [10]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(& (osgi.ws=win32) (osgi.os=win32) (osgi.arch=x86))"


!ENTRY org.eclipse.equinox.launcher.win32.win32.x86_64 2 0 2020-09-10 11:11:48.970
!MESSAGE Could not resolve module: org.eclipse.equinox.launcher.win32.win32.x86_64 [82]
  Unresolved requirement: Fragment-Host: org.eclipse.equinox.launcher; bundle-version="[1.0.0,1.4.0)"


!ENTRY org.eclipse.core.filesystem.win32.x86 2 0 2020-09-10 11:11:48.980
!MESSAGE Could not resolve module: org.eclipse.core.filesystem.win32.x86 [96]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(& (osgi.os=win32) (osgi.arch=x86))"


!ENTRY org.eclipse.core.resources.win32.x86 2 0 2020-09-10 11:11:48.989
!MESSAGE Could not resolve module: org.eclipse.core.resources.win32.x86 [40]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(& (osgi.os=win32) (osgi.arch=x86))"


!ENTRY org.eclipse.equinox.launcher.win32.win32.x86 2 0 2020-09-10 11:11:48.999
!MESSAGE Could not resolve module: org.eclipse.equinox.launcher.win32.win32.x86 [49]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(& (osgi.ws=win32) (osgi.os=win32) (osgi.arch=x86))"


!ENTRY org.eclipse.osgi 4 0 2020-09-10 11:11:49.012
!MESSAGE Application error
```
```
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:78)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:628)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:578)
	at org.eclipse.equinox.launcher.WebStartMain.basicRun(WebStartMain.java:80)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1389)
	at org.eclipse.equinox.launcher.WebStartMain.main(WebStartMain.java:56)
	at com.nomura.dna.hub.securelauncher.WebStartMain.main(WebStartMain.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:576)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:945)
```

Can someone help me with this?

**Comment by Jamila891** [comment]
Could you add an reproducible example? Or you could also give us access to your application, if it is public?

**Comment by NikitaS1609** [comment]
Thanks for you reply!
I am afraid that the application is private. Hence, wont be able to give access to it.
This application launches fine with Oracle Javaws. I have been trying to launch it with the help of IceTea Web and Zulu 8.
Getting above error with iced tea web.
Below is the jnlp file for reference.


<?xml version="1.0" encoding="UTF-8"?>
<jnlp spec="1.0+" codebase="http://admefgqa1.eu-dev2.gslb.abc.com/">
  <information>
    <title>efg-Hub</title>
    <vendor>abc International</vendor>
    <homepage href="http://www.abc.com" />
    <description>efg-Hub (Java)</description>
  </information>
 
  <security>
    <all-permissions/>
  </security>
 
  <application-desc main-class="com.abc.efg.hub.securelauncher.WebStartMain">
	<argument>-showsplash</argument>
		<argument>-debug</argument>
  </application-desc>
 
  <resources>
    <j2se initial-heap-size="512m" max-heap-size="1024m" version="1.6+" 
          java-vm-args="-Dorg.apache.cxf.Logger=org.apache.cxf.common.logging.Log4jLogger"
    />

    <jar href="/efg/ALC/E4/deploy/jars/com.abc.efg.hub.securelauncher_6.7.0.jar"/> 
    <jar href="/efg/ALC/E4/deploy/jars/org.eclipse.equinox.launcher_6.7.0.jar"/> 
    
    
    
    <jar href="/efg/ALC/E4/deploy/jars/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.401.v20161122-1740.jar"/>
	<jar href="/efg/ALC/E4/deploy/jars/org.eclipse.equinox.launcher.win32.win32.x86_1.1.401.v20161122-1740.jar"/>
	
	    
	
	
	
	<extension name="efgAccount" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.allocator.admin.account_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="efgAllocation" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.allocator.allocation_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="efgPositions" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.allocator.position_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="LRAC" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.hub.eclipse_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="efgOrderEntry" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.allocator.manual.order_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="efgClearer" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.clearer.settlements_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="efgNAP" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.allocator.file.mapping_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="efgBlotter" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.allocator_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="efgRisk" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.allocator.risk_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="efgSecurity" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.allocator.admin.security_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="efgPositionMonitoring" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.allocator.risk.monitoring_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="efgPositionsService" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.allocator.position.service_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
		
	
	<property name="jnlp.osgi.install.area" value="@user.home/Application Data/abc/efg/QA/install"/>
	<property name="jnlp.osgi.instance.area" value="@user.home/Application Data/abc/efg/QA/workspace"/>
    <property name="jnlp.osgi.configuration.area" value="@user.home/Application Data/abc/efg/QA/configuration"/>
 
    <property name="jnlp.eclipse.product" value="com.abc.efg.hub.ui.application.product"/>        
    <property name="jnlp.osgi.splashPath" value="platform:/base/plugins/com.abc.efg.hub.ui.application"/>
    <property name="jnlp.osgi.bundles.defaultStartLevel" value="4"/>
    <property name="jnlp.osgi.clean" value="true"/>
	<property name="jnlp.eclipse.security" value="osgi" />	
	
	<property name="jnlp.com.sun.xml.namespace.QName.useCompatibleSerialVersionUID" value="1.0"/>
    
    <property name="jnlp.log4j.ignoreTCL" value="true"/>    
    
    <property name="jnlp.com.abc.efg.hub.name" value="abc efg Allocator "/>
    <property name="jnlp.com.abc.efg.allocator.webservice.rw.url" value="http://admefgqa1.eu-dev2.gslb.abc.com/"/>
    <property name="jnlp.com.abc.efg.allocator.webservice.ro.url" value="http://admefgqa1.eu-dev2.gslb.abc.com/"/>
    <property name="jnlp.com.abc.efg.hub.llServerURL" value="http://admefgqa1.eu-dev2.gslb.abc.com/"/>
    <property name="jnlp.com.abc.efg.allocator.server.client.useWebService" value="true"/>
    <property name="jnlp.com.abc.efg.hub.authLevel" value="basic"/>
    
	<property name="jnlp.com.abc.efg.allocator.ui.env" value="QA"/>
	<property name="jnlp.com.abc.efg.hub.env" value="QA"/>
	<property name="jnlp.lrac.env" value="QA"/>
	<property name="jnlp.lrac.logdir.prefix" value="Allocator"/>
	<property name="jnlp.lrac.logdir.suffix" value="logs"/>
    <property name="jnlp.com.abc.efg.allocator.ui.logdir.prefix" value="Allocator"/>
    <property name="jnlp.com.abc.efg.allocator.ui.logdir.suffix" value="logs"/>
    
    <property name="jnlp.com.abc.efg.hub.gdcToken.enabled" value="false"/>
	<property name="jnlp.com.abc.efg.hub.gdcToken" value="$$gcdJNLPToken"/>


    <property name="jnlp.com.abc.efg.hub.xpUserId" value="sahunikn"/>
    <property name="jnlp.com.abc.efg.hub.gdcUserId" value="sahunikn"/>
    
    <property name="jnlp.com.abc.efg.hub.NNCookieValue" value="%%SSOCOOKIEVALUE%%"/>
    <property name="jnlp.com.abc.efg.hub.NNCookieName" value="%%SSOCOOKIENAME%%"/>
    
    <property name="jnlp.com.abc.efg.hub.isIntranet" value="true"/>
  
    
  </resources>
</jnlp>

**Comment by NikitaS1609** [comment]
<--<?xml version="1.0" encoding="UTF-8"?>
<jnlp spec="1.0+" codebase="http://admefgqa1.eu-dev2.gslb.abc.com/">
  <information>
    <title>efg-Hub</title>
    <vendor>abc International</vendor>
    <homepage href="http://www.abc.com" />
    <description>efg-Hub (Java)</description>
  </information>
 
  <security>
    <all-permissions/>
  </security>
 
  <application-desc main-class="com.abc.efg.hub.securelauncher.WebStartMain">
	<argument>-showsplash</argument>
		<argument>-debug</argument>
  </application-desc>
 
  <resources>
    <j2se initial-heap-size="512m" max-heap-size="1024m" version="1.6+" 
          java-vm-args="-Dorg.apache.cxf.Logger=org.apache.cxf.common.logging.Log4jLogger"
    />

    <jar href="/efg/ALC/E4/deploy/jars/com.abc.efg.hub.securelauncher_6.7.0.jar"/> 
    <jar href="/efg/ALC/E4/deploy/jars/org.eclipse.equinox.launcher_6.7.0.jar"/> 
    
    
    
    <jar href="/efg/ALC/E4/deploy/jars/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.401.v20161122-1740.jar"/>
	<jar href="/efg/ALC/E4/deploy/jars/org.eclipse.equinox.launcher.win32.win32.x86_1.1.401.v20161122-1740.jar"/>
	
	    
	
	
	
	<extension name="efgAccount" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.allocator.admin.account_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="efgAllocation" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.allocator.allocation_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="efgPositions" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.allocator.position_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="LRAC" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.hub.eclipse_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="efgOrderEntry" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.allocator.manual.order_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="efgClearer" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.clearer.settlements_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="efgNAP" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.allocator.file.mapping_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="efgBlotter" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.allocator_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="efgRisk" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.allocator.risk_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="efgSecurity" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.allocator.admin.security_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="efgPositionMonitoring" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.allocator.risk.monitoring_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
	<extension name="efgPositionsService" href="/efg/ALC/E4/combined/launch/features/com.abc.efg.allocator.position.service_6.7.0.jnlp?codebase=admefgqa1.eu-dev2.gslb.abc.com/"/>
		
	
	<property name="jnlp.osgi.install.area" value="@user.home/Application Data/abc/efg/QA/install"/>
	<property name="jnlp.osgi.instance.area" value="@user.home/Application Data/abc/efg/QA/workspace"/>
    <property name="jnlp.osgi.configuration.area" value="@user.home/Application Data/abc/efg/QA/configuration"/>
 
    <property name="jnlp.eclipse.product" value="com.abc.efg.hub.ui.application.product"/>        
    <property name="jnlp.osgi.splashPath" value="platform:/base/plugins/com.abc.efg.hub.ui.application"/>
    <property name="jnlp.osgi.bundles.defaultStartLevel" value="4"/>
    <property name="jnlp.osgi.clean" value="true"/>
	<property name="jnlp.eclipse.security" value="osgi" />	
	
	<property name="jnlp.com.sun.xml.namespace.QName.useCompatibleSerialVersionUID" value="1.0"/>
    
    <property name="jnlp.log4j.ignoreTCL" value="true"/>    
    
    <property name="jnlp.com.abc.efg.hub.name" value="abc efg Allocator "/>
    <property name="jnlp.com.abc.efg.allocator.webservice.rw.url" value="http://admefgqa1.eu-dev2.gslb.abc.com/"/>
    <property name="jnlp.com.abc.efg.allocator.webservice.ro.url" value="http://admefgqa1.eu-dev2.gslb.abc.com/"/>
    <property name="jnlp.com.abc.efg.hub.llServerURL" value="http://admefgqa1.eu-dev2.gslb.abc.com/"/>
    <property name="jnlp.com.abc.efg.allocator.server.client.useWebService" value="true"/>
    <property name="jnlp.com.abc.efg.hub.authLevel" value="basic"/>
    
	<property name="jnlp.com.abc.efg.allocator.ui.env" value="QA"/>
	<property name="jnlp.com.abc.efg.hub.env" value="QA"/>
	<property name="jnlp.lrac.env" value="QA"/>
	<property name="jnlp.lrac.logdir.prefix" value="Allocator"/>
	<property name="jnlp.lrac.logdir.suffix" value="logs"/>
    <property name="jnlp.com.abc.efg.allocator.ui.logdir.prefix" value="Allocator"/>
    <property name="jnlp.com.abc.efg.allocator.ui.logdir.suffix" value="logs"/>
    
    <property name="jnlp.com.abc.efg.hub.gdcToken.enabled" value="false"/>
	<property name="jnlp.com.abc.efg.hub.gdcToken" value="$$gcdJNLPToken"/>


    <property name="jnlp.com.abc.efg.hub.xpUserId" value="sahunikn"/>
    <property name="jnlp.com.abc.efg.hub.gdcUserId" value="sahunikn"/>
    
    <property name="jnlp.com.abc.efg.hub.NNCookieValue" value="%%SSOCOOKIEVALUE%%"/>
    <property name="jnlp.com.abc.efg.hub.NNCookieName" value="%%SSOCOOKIENAME%%"/>
    
    <property name="jnlp.com.abc.efg.hub.isIntranet" value="true"/>
  
    
  </resources>
</jnlp>-->

**Comment by hendrikebbers** [comment]
I assume this is specific for Eclipse / OSGI. I never tried to start an application that is based on OSGI with ITW. Since I have zero knowledge about OSGI it would be really good to have a small "Hello world" application that shows the error. @NikitaS1609 would it be possible to provide such application?

**Comment by NikitaS1609** [comment]
Hi All,

I am able to launch the application now.
I was trying with the .zip installation available on the website.
When I tried with .msi, it is launching fine.
Thank you all for the replies.

The applications is working as expected. However, i see below error  [net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1605)] NETX Thread# 1e999c23, name Thread-43
java.lang.ClassNotFoundException: com.abc.efg.allocator.webservice.jaxws.ListUsers
        at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClassExt(JNLPClassLoader.java:1802)


Any idea, How can i suppress this?

Regards,
Nikita

**Comment by sclassen** [comment]
Is this class part of your application?
Is it required to run the app?
Is it contained in one of the JARs?
