### ISSUE TITLE
Add Travis Build

### ISSUE THREAD

**Issue by hendrikebbers** [AdoptOpenJDK/IcedTea-Web#700]
**🆕🐥🐶 First Timers Only**
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

**👾 Description of the issue**
IcedTea-Web should have a [Travis](https://travis-ci.org) build. Information how a Java project can be build by Travis can be found [here](https://docs.travis-ci.com/user/languages/java/). IcedTea-Web is based on [Maven](https://maven.apache.org) and a `mvn clean verify` should be executed by the Travis build. Today we do not have a maven wrapper but that can be added when solving this issue (optional). IcedTea-Web should be build on the last Java 8 release of [AdoptOpenJDK](https://adoptopenjdk.net). Providing an additional build that is based on Java 11 would be a big benefit (optional).

**📋 Step by Step**
To solve this issue and contribute a fix to IcedTea-Web you should check the following step-by-step list:

* Claim this issue: Comment below.
* fork the repository in github by simply clicking the 'fork' button.
* check out the forked repository
* create a feature branch for the issue. We do not have any naming definition for branches.
* Commit your changes.
* Start a Pull Request.
* Done 👍 Ask in comments for a review :)
* If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
* you did it! We will merge the fix in the master of the IcedTeaWeb project.
* Thanks, thanks, thanks for being part as an open source contributor for IcedTeaWeb

**🎉 Contribute to Hacktoberfest**
Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a change to receive cool goodies like a T-Shirt. 🎽

**🤔❓ Questions**
If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions here.

**Comment by karianna** [comment]
Commenting purely on the template design here (if we were to adopt it across all repos).  I do find the heavy icon usage distracting.  Perhaps we could tone down some of that.

The bulleted list could/should be numeric?

Overall I love the concept

**Comment by hendrikebbers** [comment]
Added the template as a GIST for future discussion here: https://gist.github.com/hendrikebbers/8e4dec9ddea5e2a420080d1314af025f

Since this is a real issue we should discuss the template in the gist. I will update this issue from time to time to have a real sample :)

**Comment by hendrikebbers** [comment]
Oh, and I removed several emojis ;)

**Comment by bmsbharathi** [comment]
Hey, I am interested in setting up Travis CI. Let me know what is the expectation here

**Comment by Jamila891** [comment]
@bmsbharathi we are more than happy if you want to work on this issue. The expectations are described in the description of this issue. If you need further help in the github workflow see this URL: https://github.com/firstcontributions/first-contributions/blob/master/README.md
