### ISSUE TITLE
Override java.locale.providers not working when running openwebstart 1.2.1

### ISSUE THREAD

**Issue by matand72** [AdoptOpenJDK/IcedTea-Web#702]
When running an application using openwebstart 1.2.1 (using AdoptOpenJDK 11) we cannot set the java.locale.providers. we want to change the so that is uses the JRE locale information and not the CLDR information.

http://openjdk.java.net/jeps/252

The parsing of the CLDR locale information is not work correctly with some locales (for instance se_SV and negative numbers). So we need to specify the -Djava.locale.providers=COMPAT,SPI and it works with out a problem when running as a normal java application.

But when trying to use the following resource tags in the JNLP file the locale database used is still CLDR. 

`<resources>
    <property name="jnlp.packEnabled" value="true"/>
    <property name="java.locale.providers" value="COMPAT,SPI"/>
    <j2se version="11+" initial-heap-size="100m" max-heap-size="512m"/>
...
</resources>`      

We are experiencing this with sv_SE locale
 
And as far as I can tell it is the startup code in Boot.java that are creating a locale indirectly  before is sets the java.locale.providers system properties due to the 

private static final Logger LOG = LoggerFactory.getLogger(Boot.class); 

![image](https://user-images.githubusercontent.com/53760809/93710360-5759b200-fb46-11ea-8ee8-8177520b0fad.png)

The locale providers are cached in sun.util.locale.provider.LocaleProviderAdapter so it is crucial that the system properties are updated before any locales are created.

Is this just not supported or are there any other way to solve this?

**Comment by sclassen** [comment]
`java.locale.providers` is currently not on the list of save properties to pass at JVM start.
We will consider adding this to our next version (scheduled for November).

**Comment by matand72** [comment]
Great news! If you need someone to test this or some other help just let me know. This is a real problem for us. We are right know considering using the icu4j lib to circumvent this but it is massive and we do not want to add another 12 Mb of size to our web start application.

**Comment by hendrikebbers** [comment]
see https://github.com/AdoptOpenJDK/IcedTea-Web/pull/704

**Comment by matand72** [comment]
White list of system properties in #702 is of course a needed for this issue but I don't think it will solve the problem since the current code in Boot.jar (as shown in stack trace above) creates a LocaleProviderAdapter before the java.locale.providers will be  set.

And since the LocaleProviderAdapter  are cached setting the the java.locale.providers will not help since it will be ignored. The code in Boot.jar must be rewritten to not create a LocaleProviderAdapter indirectly before the system properties are set. So the logging in Boot.jar need to be handled in a different way I guess?

**Comment by sclassen** [comment]
Yes and no.
It is sufficient as OWS will start the second VM with the property on the VM arguments thus the property is set before any code is executed.

And no the new solution is limiting in that it requires you to add the exact VM argument (including the value) and does not allow to specify simply the property.
I will take this limitation back to the dev team maybe we offer two configuration lists. One for arguments and one for properties.

**Comment by matand72** [comment]
Ok! Sorry for my limited knowledge of the code. Aa long as I'm able to set the  

<resources> 
    <property name="java.locale.providers" value="COMPAT,SPI"/> 
   <j2se version="11+" initial-heap-size="100m" max-heap-size="512m"/> 
... 
</resources>

in the JNLP file and the code set it before any of the application code is executed then I'm happy :)

**Comment by sclassen** [comment]
Well almost. You need to set the property as a 'java-vm-args' and not as a 'property'

```
<resources> 
   <j2se version="11+" initial-heap-size="100m" max-heap-size="512m" java-vm-args="-Djava.locale.providers=COMPAT,SPI"/> 
... 
</resources>
```

**Comment by matand72** [comment]
I can verify that this works using 1.3.0 (and using whitelist in deployment.properties). Thanks!

**Comment by sclassen** [comment]
great to hear
