### ISSUE TITLE
Fatal: Read Error: Could not read or parse the JNLP file

### ISSUE THREAD

**Issue by ulooky** [AdoptOpenJDK/IcedTea-Web#707]
I am getting the following error when I run javaws on my asdm.jnlp file
[asdm.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/5271826/asdm.zip)
[asdm.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/5271828/asdm.zip)

net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:487)
	at net.sourceforge.jnlp.Launcher.launch(Launcher.java:287)
	at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:258)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:62)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:198)
Caused by: java.io.IOException: java.lang.NullPointerException: name can't be null
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:318)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:240)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:451)
	... 6 more
Caused by: java.lang.NullPointerException: name can't be null
	at java.io.FilePermission.init(FilePermission.java:209)
	at java.io.FilePermission.<init>(FilePermission.java:310)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
	at java.io.FileInputStream.<init>(FileInputStream.java:127)
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:316)
	... 11 more

**Comment by sclassen** [comment]
This error happens when ITW is unable to download the resources. Could you please attach the log files for further debugging this. Thanks

**Comment by jastax** [comment]
I'm running into a same/similars issue from time to time (1.3.1). Sometimes launching the app works, sometimes this or a similar error shows up. It seems to happen more often when I'm trying to launch the application multiple times. It could be a race condition on the download / cache. Maybe it's a problem with download speed dropping below a certain threshold (or 0 for short bursts?).

I've not yet have enough time to further investigate and I don't know when I will be able to. Just wanted to give a heads up, just in case it could help.

**Comment by Jamila891** [comment]
can you provide the log files? The stack trace is not helpful for us to solve this problem.

**Comment by jastax** [comment]
I've launched the application multiple times. Launching it once seems to work. Launching it twice at the same time seems to lead to problems.

[log.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/5677673/log.zip)

**Comment by sclassen** [comment]
@jastax 
Thank you for the logs. I found the cause of your problem. A fix is here #728 
Unfortunately it is a different one from the original reporter.

The next release is currently planned for April 2021.

**Comment by sclassen** [comment]
@ulooky if you still need help on this issue, we would need log files from your case.

**Comment by jastax** [comment]
Hi @sclassen that's great, thank you.

I'm wondering about why the cache is even deleted though?

Is there a way to speed up the release? We'd like to use OWS 1.3.x in production starting in Q1/21.

**Comment by sclassen** [comment]
We do offer different support options.
Details can be found on the official homepage: https://openwebstart.com/support/
There is also the possibility to have a customized splash screen.

For the free/community version there is only the half year release schedule.

**Comment by sclassen** [comment]
I will take a second look at the cache deletion over the weekend

**Comment by sclassen** [comment]
Just one question:
Have you set a limit to the cache size?
You can see the current settings in the settings UI on the "cache" tab.

**Comment by jastax** [comment]
I'm sorry, I'll only have access to the windows computer in January. I don't think the cache limit is set / that low though. I'll check it next month

**Comment by jastax** [comment]
`
![cache](https://user-images.githubusercontent.com/1672178/103868865-c9401200-50c9-11eb-9dbc-2bfe957e2b5f.PNG)
`

**Comment by Jamila891** [comment]
@jastax we are going to take a deeper look into this bug. We'll keep you updated.

**Comment by jastax** [comment]
@Jamila891  Thanks!

> We do offer different support options.
> Details can be found on the official homepage: https://openwebstart.com/support/
> There is also the possibility to have a customized splash screen.
> 
> For the free/community version there is only the half year release schedule.

We have booked a support option now (LVM). I'd like to test whether the fix solves the problems - are you going to release it soon? :)

**Comment by jastax** [comment]
(We are using OWS, so the fixed Version would need to be applied there too)

**Comment by sclassen** [comment]
We will do a release today. It will be available tomorrow and contains the fix for your issue.
Also we added more logging for the cache cleanup which will help debug the reason why in your setup the application is removed from the cache.

**Comment by jastax** [comment]
@sclassen That's great, thanks!

**Comment by sclassen** [comment]
Can you please open a new issue for the cache cleanup if you can still reproduce the behavior with 1.3.2
Thanks
