### ISSUE TITLE
IcedTea Web authorization failure issue (403) with CA Siteminder Single-Sign-On Server

### ISSUE THREAD

**Issue by deepankardixit90** [AdoptOpenJDK/IcedTea-Web#717]
I am using IcedTea Web v1.8.3 to launch an application (via JNLP) on client machine. Upon launching the application, ITW fetches the jar files necessary to run the application from a remote server (over HTTPS). This works fine when there is no Single-Sign-On Server (SSO) in between and the authentication takes place through a valid client certificate or through a simple basic authentication. But when I try to launch the same application with ITW for a different environment which requires single sign on (SSO), the authorization fails with HTTP Server 403 status. 

We are using CA Siteminder server for SSO on this environment. On debugging, it was found that Siteminder server, post successful basic authentication (username/password), sends a cookie **(SMCHALLENGE=YES**) which is NOT being included by ITW in subsequent requests. This causes authorization failure on the server while fetching jar files and other resources required to run the application. We tested the same scenario with Oracle Webstart and it worked just fine.

The request/response flow is as below:

1.	IcedTea-Web --> Server:
HEAD /codebase_url/resource.jar HTTP/1.1

2.	Server --> IcedTea-Web:
HTTP/1.1 401 Unauthorized
Server: Apache (Unix) OpenSSL
WWW-authenticate: basic realm="app with basic authentication"
Set-Cookie: SMCHALLENGE=YES; path=/; domain=.somedomain.com  (this cookie should be sent by IcedTea-Web)                                  

3.	IcedTea-Web --> Server:
GET /codebase_url/resource.jar HTTP/1.1
Accept-Encoding: gzip, deflate
User-Agent: Java/1.8.0_232
Host: somehost.com
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: close
Authorization: Basic a2FoaXJyYW86QXZheWExMjM=      (Cookie: SMCHALLENGE=YES NOT being sent by ITW here)

We are using Azul OpenJDK v1.8.0_232 (Zulu) with ITW, though we also reproduced the steps using Oracle Java with ITW and the result was same. Client OS is Windows 10.

Attaching relevant part of the logs for reference.

[GitHub_ITW_Log.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/5393492/GitHub_ITW_Log.txt)

Is there a workaround for this issue? If its a bug in ITW, it would be helpful to know if there would be any resolution/fix planned in future releases.

**Comment by Jamila891** [comment]
@deepankardixit90 can you please try https://github.com/karakun/OpenWebStart since we did some changes regarding this issue in OpenWebStart.

**Comment by deepankardixit90** [comment]
Thanks for your comment @Jamila891. I tried OpenWebStart v1.2.2 and unfortunately, the issue still persists. We are still getting HTTP 403 Forbidden response from server.

**Comment by hendrikebbers** [comment]
At the moment there is no plan to provide single-sign-on functionalities for Iced-Tea Web.

**Comment by janakmulani** [comment]
> Thanks for your comment @Jamila891. I tried OpenWebStart v1.2.2 and unfortunately, the issue still persists. We are still getting HTTP 403 Forbidden response from server.

@deepankardixit90 Can you please try with OWS 1.8.0?
