### ISSUE TITLE
Replace Travis CI with something else

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/IcedTea-Web#724]
Travis CI basically terminated free CI for OSS overnight. Could you please replace it with something else, like GitHub Actions? Please see https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1668 for details.

**Comment by sclassen** [comment]
We build ITW also on our company CI. So in worst case until we find a solution we could stop using Travis.
I guess as it is best to not implement 10 different CI solutions we at ITW will just wait until Adopt has decided for an alternative to Travis and will then follow with the migration.

**Comment by Jamila891** [comment]
we will be moving to github actions.

**Comment by hendrikebbers** [comment]
Moving to GitHub Actions needs to take care of the UI tests.

Sample:
https://github.com/juliangruber/browser-run/issues/147#issuecomment-754553635

**Comment by sclassen** [comment]
Master is green on github actions.
Using the following: https://github.com/marketplace/actions/gabrielbb-xvfb-action
