### ISSUE TITLE
IcedTea rejects vaild JNLP file

### ISSUE THREAD

**Issue by marcus905** [AdoptOpenJDK/IcedTea-Web#733]
When trying to start a valid JNLP file IcedTea will reject the file with 

```
net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file.
Caused by: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "48x48"
```

In the JNLP file there is a presumably valid (JSR56 does not specify the type of the attribute size) element

`<icon href="..." size="48x48"/> `

The parser at https://github.com/AdoptOpenJDK/IcedTea-Web/blob/e3e147e1439b59cf9dfde9558a6dfe10025fd9ef/core/src/main/java/net/sourceforge/jnlp/Parser.java#L759 therefore incorrectly tries to parse the element as int.

I assume the correct way to parse the element would be to either:

-  treat it as string, if the attribute could be used like that easily,
- or alternately, if the other width, height and depth attributes are -1, to populate them by parsing the element (when depth is not specified it could be assumed 24bits per pixel) and multiplying them overriding the size (e.g. 48x48 with assumed 24bpp would lead to a value of 48 * 48 * (24/8) = 6912 for the size attribute.
- or also to fallback any non-int value with the default one by catching the NumberFormatException and in the catch block forcing the value as -1

According to what would be better, I can fix the bug and provide a pull request.

**Comment by sclassen** [comment]
Here is the section about the icon from the JSR:

> icon element: The icon can be used by a JNLP Client to identify the application to the user.
>
>The optional width and height attributes can be used to indicate the resolution of the images. Both are measured in pixels.
>
>The optional depth attribute can be used to describe the color depth of the image.
>
>The optional kind attribute can be used to indicate the use of the icon, such as default, selected, disabled, rollover, splash, and shortcut.
>
>The optional size attribute can be used to specify the download size of the icon in bytes.
>
>The image file can be either GIF or JPEG format, or other (possibly platform dependant) formats. The JNLP Client may assume that a typical JNLP file will have at least an icon in GIF or JPEG format of 32x32 pixels in 256 colors of the default kind. Its location is specified as described in section 3.4, and it is downloaded using the protocols described in Section 6.

For my understanding 48x48 is not a valid size. You should pass these values as width and height attribute.
