### ISSUE TITLE
Correct the 'msi' installer extension in the release.

### ISSUE THREAD

**Issue by mdeweerd** [AdoptOpenJDK/IcedTea-Web#734]
In https://github.com/AdoptOpenJDK/IcedTea-Web/releases/ , the 'msi' installer should not have the 'exe' extension.  It works when changing the extension to .msi.

It also impacts https://adoptopenjdk.net/icedtea-web.html where the 'msi' points to a link that does not exist because of the invalid extension.

**Comment by Jamila891** [comment]
Thank you for reporting. We fixed the problem.
