### ISSUE TITLE
MacOS dock name option is not accepted

### ISSUE THREAD

**Issue by kelemenb-ewit** [AdoptOpenJDK/IcedTea-Web#738]
According to MacOS documentation the application "dock-name" should be set with startup option "`-Xdock:name=<MyAppName>`". Unfortunately the "`-Xdock:name`" is does not appears in JvmUtils.java constants an will be ignored.

I can certainly add this option in `getValidStartingVMArguments()` and create a pull request with it, but I don't think you will accept that. Or will you?

Is there any suggestions, how to set dock-name in MacOS using JNLP?

**Comment by sclassen** [comment]
You can enable jvmargs in the configuration:
https://openwebstart.com/docs/OWSGuide.html#_whitelist_for_jvm_arguments

Is this sufficient for your use case?

**Comment by prampec** [comment]
Sounds like a workaround instead of a solution. :)
I need to ask the customers about this possibility.

**Comment by sclassen** [comment]
this is the fastest way because you do not need to wait for a new version of ITW or OWS to be released.

**Comment by sclassen** [comment]
since this issue also is present in OWS we continue the discussion in karakun/OpenWebStart#382
