### ISSUE TITLE
Cisco ASDM does not work with OpenJDK 8 (deploy.jar missing)

### ISSUE THREAD

**Issue by le-jawa** [AdoptOpenJDK/IcedTea-Web#741]
**Windows, Linux & Mac:**

**x64:**

Not sure if this is a problem for Cisco or OpenJDK; it depends on where the actual problem is.  ASDM requires Java 8, but does not work with OpenJDK 8.  If the libraries required for ASDM are not intended to be there (ie, Oracle intentionally did not include them), then oh well I guess.  Hopefully we can convince Cisco to support OpenJDK if that's the case.  However,  if this is something that should be there now, or in the near future, then yes, a lot of system/network admins out there would love to see this fixed.

I've attached the console log with the stack trace from ASDM.  

[ASDM-java-log.txt](https://github.com/AdoptOpenJDK/openjdk-build/files/3238166/ASDM-java-log.txt)

**Comment by nvaert1986** [comment]
For those interested, you can actually get this to work:
1. Make sure the asdm-openjre-version.bin is installed on the ASA
2. Use a browser with a user agent switch and make sure you set it to Microsoft Windows with any browser
3. Download the dm-launcher.msi
4. Install using wine (works with wine-staging-5.22)
5. Copy the .wine/drive_c/Program Files (x86)/Cisco/ASDM folder to ~/ASDM
6. Run a chmod +x on all the jar files in there
7. Make sure the latest AdoptOpenJDK 8.0 release is installed
8. Run java -jar asdm-launcher.jar in the ASDM folder
9. Optional make a shortcut on the desktop if desired with this command

This way it launches just fine and can connect to any ASA using OpenJDK on Linux. The .bin doest just not include a Linux installer file, but the jar files work fine when extracted and ran manually. Tested using asdm-openjre-7151.bin
