### ISSUE TITLE
2 Java Processes are getting spawned when launching a single JNLP client console.

### ISSUE THREAD

**Issue by mahboobbaig** [AdoptOpenJDK/IcedTea-Web#743]
**Windows Environment:**
I am using the AdoptOpenJDK 1.8.0.265. When I launch the oneclick.jnlp file using AdoptOpenJDK with IceTeaWeb 1.8.0.265 it will connect and work with the webserver, however I do see 2 memory processes that are spawned from a single JNLP Client Console.
 
The first one is the OC Client Console I launched, the second one is listed in **background** **processes** and doesn´t appear to be important and can be killed without harming my jnlp OC client console, but is opened when launched OC Client anyways and it consumes memory as well.

I have tested this with the latest updated JRE version(1.8.0.275) but the results are the same.

Business Impact is that we use a jump sever for our users to connect to our webapplication, and currently because of this memory issue, we have to limit our users.

Its high impacting issue for us and any quick suggestions would be highly helpful.

**Comment by hendrikebbers** [comment]
Hi,
when using JNLP you want to have your application running in a sandbox. To support that sandboxing we need to start the application in a second Java process.

A concrete example: You can specify JVM arguments in the JNLP file for your application. Such arguments must be passed the the java process at start time. Since the first Java process reads the JNLP file he has no chance to use the defined JVM args. Therefore a second process needs to be started to handle the JVM args.

**Comment by mahboobbaig** [comment]
> Hi,
> when using JNLP you want to have your application running in a sandbox. To support that sandboxing we need to start the application in a second Java process.
> 
> A concrete example: You can specify JVM arguments in the JNLP file for your application. Such arguments must be passed the the java process at start time. Since the first Java process reads the JNLP file he has no chance to use the defined JVM args. Therefore a second process needs to be started to handle the JVM args.

Thanks for your response Hendrik. Really appreciate it. So as per you its working as designed right? But the problem here is Memory consumption, 2 java processes getting launched and consuming memory is a concern with our customers. And moreover when compared with Oracle JRE this behavior is not observed, it spawns only a single Java process. Can anything be done to fix this?

**Comment by sclassen** [comment]
Which version are you running?
ITW 1.8.3 or are you using the OpenWebStart version?

**Comment by mahboobbaig** [comment]
> Which version are you running?
> ITW 1.8.3 or are you using the OpenWebStart version?

I am using ITW 1.8.4.

**Comment by sclassen** [comment]
OK, with ITW there is a possibility to start a JNLP with only one VM.
You must make sure that in the JNLP there is no jvm-args set and also no memory constraints given.
In that case ITW should run the app with the current JVM and not launch a second one

**Comment by patris70** [comment]
@mahboobbaig,

you can using **-Xnofork** Parameter.
JAVAWS.exe -Xnofork -JNLP

**Comment by sclassen** [comment]
Be aware that simply adding `-Xnofork` can break your application if it depends on jvm-args beeing passed.
Thus we recommend removing the jvm-args from the JNLP if possible as it increases awareness of what changes are applied to the application start

**Comment by patris70** [comment]
@sclassen,

I've been using -Xnofork parameters for 2 years and have never had problems.

**Comment by sclassen** [comment]
It will not cause problems for most applications. But we have also seen a good hand full of JNLPs which pass information to the application using the vm-args. These applications need to spawn a second JVM. ITW will take care of this issue and if possible only start a second JVM when it is needed. Therefore it is safer to change the JNLP.

It also has the benefit that it will effect all users and not just the ones which pass the -Xnofork parameter

**Comment by mahboobbaig** [comment]
Hi Guys, I used the -Xnofork option as suggested and it worked as expected,  there is no second java process launched.

The syntax is like this:
javaws -Xnofork oneclick.jnlp


Thanks to everyone for their valuable suggestions.

**Comment by sclassen** [comment]
Did you find out which entry in the JNLP caused the forking?
Or could you past your JNLP here. Thanks

**Comment by mahboobbaig** [comment]
Here is my jnlp file for your reference. I am using java-vm-args and also passing min and max mem values, may be those are causing it??

<?xml version="1.0" encoding="utf-8"?>


<jnlp spec="1.0+" codebase="http://hostname:port/yyyy"
                  href="/zzzzzz/oneclick.jnlp">
  <information>
    <title>Title goes here</title>
    <vendor>Vendor Name</vendor>
    <homepage href="index.jsp"/>
    <description>Description goes here</description>
    <description kind="short">Description goes here</description>
    <icon href="images/i_icon.jpg"/>
    
  </information>

  <security>
    <all-permissions/>
  </security>

   <resources>
    
    <property name="sun.awt.noerasebackground" value="true"/>
    
    <property name="javaws.cfg.jauthenticator" value="true" />

    <j2se version="1.8.0_242" java-vm-args="--add-modules=java.se.ee" href="http://java.sun.com/products/autodl/j2se"
          initial-heap-size="96m" max-heap-size="1042m"/>

    <jar href="lib/clientconsole.jar;no_javaws_cheat"/>
    <jar href="lib/clientalarm.jar;no_javaws_cheat"/>
    <jar href="lib/clienttopo.jar;no_javaws_cheat"/>
    <jar href="lib/jgraphx.jar;no_javaws_cheat"/>
    <jar href="lib/webswing-api.jar;no_javaws_cheat"/>
    <jar href="lib/clientapp.jar;no_javaws_cheat"/>
    <jar href="lib/clientevent.jar;no_javaws_cheat"/>
    <jar href="lib/clientadmin.jar;no_javaws_cheat"/>
    <jar href="lib/util.jar;no_javaws_cheat"/>
    <jar href="lib/utilsrv.jar;no_javaws_cheat"/>
    <jar href="lib/utilnet.jar;no_javaws_cheat"/>
    <jar href="lib/utilapp.jar;no_javaws_cheat"/>
    <jar href="lib/utilgui.jar;no_javaws_cheat"/>
    <jar href="lib/jecds.jar;no_javaws_cheat"/>
    <jar href="lib/global.jar;no_javaws_cheat"/>
    <jar href="lib/productsuite.jar;no_javaws_cheat"/>
    <jar href="lib/jdom.jar;no_javaws_cheat"/>
    <jar href="lib/xercesImpl.jar;no_javaws_cheat"/>
    <jar href="lib/xml-apis.jar;no_javaws_cheat"/>
    <jar href="lib/commons-collections.jar;no_javaws_cheat"/>
    <jar href="lib/mindterm.jar;no_javaws_cheat"/>
    <jar href="lib/oneclickclient.jar;no_javaws_cheat"/>
    <jar href="lib/occversion.jar;no_javaws_cheat"/>
    <jar href="lib/icu4j-4_4_2_2.jar;no_javaws_cheat"/>
    <extension name="RSA Crypto-J" href="cryptoj.jnlp"/>

  </resources>

  <application-desc main-class="ClassName">
    
    <argument>-timeout 0</argument>
    <argument>-loginTitle </argument>
    <argument>-appBrandName </argument>
    <argument>-appSuiteName </argument>
    <argument>-appIcon </argument>
    <argument>-splashImage </argument>

    <argument>-model_bits 24</argument>
    <argument>-contextPort 43000</argument><argument>-compress 9</argument>
    
  </application-desc>
</jnlp>

**Comment by patris70** [comment]
This is OneClick CA Spectrum Application.

https://techdocs.broadcom.com/us/en/ca-enterprise-software/it-operations-management/spectrum/10-3-1/administrating/oneclick-administration/oneclick-administration-pages.html

1- You must using OpenJDK x64.
2- You must disable other LOGs in Icedtea-Web 1.8.x Version.
3- If you have AntiVirus (Trendmicro, McAfee), you must add Icedtea-Web and OpenJDK to Whitelist and set for minimum Scan.

I had same Problem and that was Trick.

**Comment by sclassen** [comment]
OK, I took the liberyt to remove the resources out of your post, as they are not relevant.

The forking is caused by the following entries `java-vm-args="--add-modules=java.se.ee"`, `initial-heap-size="96m"` and `max-heap-size="1042m"`
So if you remove them from the JNLP on the server the forking should no longer happen.

The question arises if the application is able to run without them. Or in other words, why have they be added in the first place.
Especially the `--add-modules=java.se.ee` is interesting since it is not a valid argument to a 1.8 JVM...

**Comment by mahboobbaig** [comment]
> This is OneClick CA Spectrum Application.
> 
> https://techdocs.broadcom.com/us/en/ca-enterprise-software/it-operations-management/spectrum/10-3-1/administrating/oneclick-administration/oneclick-administration-pages.html
> 
> 1- You must using OpenJDK x64.
> 2- You must disable other LOGs in Icedtea-Web 1.8.x Version source files.
> 3- If you have AntiVirus (Trendmicro, McAfee), you must add Icedtea-Web and OpenJDK to Whitelist and set for minimum Scan.
> 
> I had same Problem and that was Trick.

Hi Patris, I am using 64bit OpenJDK and was facing this issue.

C:\Users\xxxx>java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.275-b01, mixed mode)

**Comment by mahboobbaig** [comment]
> OK, I took the liberyt to remove the resources out of your post, as they are not relevant.
> 
> The forking is caused by the following entries `java-vm-args="--add-modules=java.se.ee"`, `initial-heap-size="96m"` and `max-heap-size="1042m"`
> So if you remove them from the JNLP on the server the forking should no longer happen.
> 
> The question arises if the application is able to run without them. Or in other words, why have they be added in the first place.
> Especially the `--add-modules=java.se.ee` is interesting since it is not a valid argument to a 1.8 JVM...

Hi Sclassen, I tried removing the **java-vm-args="--add-modules=java.se.ee"** section and relaunched JNLP file using ITW and it still spawned 2 java processes.

Then I then removed the memory parameters as well : initial-heap-size="96m" max-heap-size="1042m" and relaunched jnlp file but it still resulted the same.

Then I removed the entire j2se section itself :
 <j2se version="1.8.0_242" java-vm-args="--add-modules=java.se.ee" href="http://java.sun.com/products/autodl/j2se"
          initial-heap-size="96m" max-heap-size="1042m"/>

But the problem still remains the same.

So for me the only solution worked is launching the jnlp file using -Xnofork option.

**Comment by sclassen** [comment]
where did you make the changes? on a local copy of the JNLP?

If so then this will not work as ITW will download the original from the server and use that one.
If you want to test a local copy of the JNLP you also need to remove the `href` in the `<jnlp>` tag.

**Comment by mahboobbaig** [comment]
> where did you make the changes? on a local copy of the JNLP?
> 
> If so then this will not work as ITW will download the original from the server and use that one.
> If you want to test a local copy of the JNLP you also need to remove the `href` in the `<jnlp>` tag.

Hi Sclassen, I tried as you suggested i.e., removed href from the jnlp tag and then I tried the following step by step:
1. Removed href from jnlp tag and removed **java-vm-args="--add-modules=java.se.ee"**  the problem still persist.
2. Removed href from jnlp tag and removed **java-vm-args="--add-modules=java.se.ee"** and **initial-heap-size="96m" max-heap-size="1042m"** now there is only one java process listed.

We can remove **java-vm-args="--add-modules=java.se.ee"** from the jnlp file as its not required on Java 1.8 and higher versions. But we were supplying min and max memory values for Client console... if we remove this then how can we achieve memory configuration for Client console?

**Comment by sclassen** [comment]
Short answer: you cannot configure the memory options.

The same thing happens when you pass `-Xnofork`. The command line argument disables the jvm-args and the memory configuration.
The explanation is simple. ITW starts a JVM and loads the JNLP file. So by the time ITW parses the JNLP and knows about the vm-args and the memory configuration the JVM has already been started. So the only way to apply the vm-args and the memory configuration is by starting a second JVM using the arguments from the JNLP file.
