### ISSUE TITLE
Virtual console applet (iDRAC 6): Can´t enter anything

### ISSUE THREAD

**Issue by Af0x** [AdoptOpenJDK/IcedTea-Web#764]
Hello,

when one launches the iDRAC 6 virtual console applet with Iced Tea on a Fedora 33 client it is not possible to enter anything. It seems the input is not passed to the server.

I am 100% sure it worked before but can´t tell since when it stopped working.

Version 2.0.0-pre.2.alpha13.patched1.fc33

I verified this issue with 2 different clients and am grateful for any help.

Best regards

**Comment by sclassen** [comment]
Hi

I am sorry but since we do not have access to the iDRAC sources we cannot help you with this issue.
Basically once ITW hands over to the application code it is out of the loop. There are still some hocks and callbacks which allow the application and ITW to interact. But without knowledge of the aplication's code it is impossible to help.

My recommendation is to get into contact with de developers of iDRAC maybe they are able to help

**Comment by Af0x** [comment]
The iDRAC wasn´t updated at all since the last time it was working with a Fedora client. I am just not quite sure if it was under Fedora 32 = icedtea-web-1.8.x. If so, there must be something on the ITW side that did change to make it not work anymore.

**Comment by sclassen** [comment]
@judovana we see that you created the fedora package.
Maybe you have an idea what could be going wrong?

**Comment by Af0x** [comment]
Luckily I had a Fedora 32 client to test with and I can confirm that this issue only exists under Fedora 33 and not under Fedora 32. The version of ITW was the same (2.0.0-pre.2.alpha13.patched1.fc32).

**Comment by sclassen** [comment]
Can we close this or do you need more input to help track this down?

**Comment by Af0x** [comment]
I filed a bug at the bugtracker of the distro: https://bugzilla.redhat.com/show_bug.cgi?id=1933968

**Comment by Af0x** [comment]
I reopen this because obviously they don´t care about this issue.

**Comment by Af0x** [comment]
There is a high probability that this issue is due to a higher Java version (java-11-openjdk) instead of java-1.8.0-openjdk.

**Comment by Af0x** [comment]
running the .jnlp file from a console after setting the Java Version fixed the problem:
> export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
> javaws file.jnlp
