### ISSUE TITLE
ITW 1.8.5 Release

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/IcedTea-Web#766]
We haven't had a release since June 2020. Looks like lots of patches have gone in and this would be a good chance to test the new GH Actions Release process. https://github.com/AdoptOpenJDK/IcedTea-Web/wiki/IcedTea-Web-1.8.x-Release-Guide

**Comment by douph1** [comment]
The github release 1.8.5 is missing ./icedtea-web-image/win-deps-runtime/mslinks.jar
which if think is always required for Windows users to create desktop shortcut.
Waiting a fix for this before embeded it into Adopt create_installer_windows job

**Comment by gdams** [comment]
How strange, I copied the build scripts directly from the jenkins job. I noticed that the portable build has `--with-mslinks="${WORKSPACE}/mslinks.jar"` but the windows one does not.

**Comment by gdams** [comment]
Testing if this PR fixes the issue https://github.com/AdoptOpenJDK/IcedTea-Web/pull/772

**Comment by gdams** [comment]
I see the following in the release build:

```bash
**********************************************
*  Warning you are building without mslinks  *
* Your windows desktop integration will fail *
**********************************************
```
