### ISSUE TITLE
Fatal: Read Error: Could not read or parse the JNLP file

### ISSUE THREAD

**Issue by kejloh** [AdoptOpenJDK/IcedTea-Web#767]
Hello,

I'm evaluating OpenWebStart with two devices with embedded web server.  On the first device the javaws application start without problems but on the other one I run into problems:

> net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file at 'http://192.168.0.20/ProcessPage?file=%2FStatMon.jnl&frame=0&module=13&count=21&connect=1'. You can try to download this file manually and send it as bug report to IcedTea-Web team.

The JLNP file is identical on both devices but the embedded web server is different.  On the first (working) device it's an Beck SC143, on the second it's an older Beck SC13.  Oracle Java 8 is able to start the application from both devices.

Here are the JLNP file (JLN renamed to TXT, the embedded web server only supports 8.3 file names) and the LOG:

[StatMon.jln.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/6010525/StatMon.jln.txt)

[2021-02-19_15_07_35.370-ows-stage1.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/6010531/2021-02-19_15_07_35.370-ows-stage1.log)

Regards,
Jürgen

**Comment by sclassen** [comment]
The log shows that it is an XML parsing error.
Can you delete your `${USER_HOME}/.cache/iced-tea/cache` folder and try again.
Maybe the file was corrupted during download

**Comment by kejloh** [comment]
I deleted the cache but it didn't change anything.  Is there something wrong with the JLNP file?

**Comment by kejloh** [comment]
btw: This is the content of the cache folder after getting the error message:

[cache.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/6011732/cache.zip)

**Comment by sclassen** [comment]
in your cache there is only a single file with the following content:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<!-- Start.htm -->
<html><head>
<title>Rubidium Configuration</title>
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
<meta name="DC.rights" content="Copyright (c) 2012-2020 PLURA Europe GmbH, Germany">
<meta name="author" content="PLURA Europe GmbH">
<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
<link rel="stylesheet" type="text/css" href="/Style.css">
<script type="text/javascript" src="Script.js"> </script>
</head>

<body>
<form name="START" method=post action="/ProcessPage">
<input type=hidden name="file" value="">
Loading...
<noscript>
  failed.<br>
  Please enable JavaScript in your browser to use the configuration page.
</noscript>
</form>
<script type="text/javascript"> File_Start(); DoConfig(); </script>
</body></html>
<!-- /Start.htm -->
```

**Comment by sclassen** [comment]
This is an HTML error page and not a JNLP. So the question arrises why the server returns this page

**Comment by kejloh** [comment]
That's the embedded web server's default (start) page.  I'll Wireshark the traffic why it's returned.

**Comment by kejloh** [comment]
The web server did not handle the HTTP HEAD request correctly but answered it with a redirect to /.  That's fixed now and OpenWebStart is working.

Thank you for pointing me to the .cache folder.

**Comment by kejloh** [comment]
bw: Java 8 WebStart didn't send HTTP HEAD but GET only, that's why it worked.

**Comment by sclassen** [comment]
Yes, ITW and Oracle are using different strategies to check if a file is available on the server and if it needs refreshing in the cache
