### ISSUE TITLE
wine - Error spawning JVM process, java executable

### ISSUE THREAD

**Issue by vladimir-kokovic** [AdoptOpenJDK/IcedTea-Web#769]
I use, icedtea-web instead of Oracle JWS and I am very satisfied, but there is a problem I don't understand and it appears only in git wine environment.
Any icedtea-web exe can't load java JVM and in the log file is the message "Thread 'Main' Paniced at 'Error Spawning JVM Process, Java Executable ..."
In the file that is attached is the log for itweb-settings.exe.

**Comment by vladimir-kokovic** [comment]
itweb-settings.exe.

Z:\tmp>rem z:\var\www\pp-ispp-itw\llvm-mingw\javaws-wine.bat 

Z:\tmp>set path=/usr/x86_64-w64-mingw32/bin;C:\windows\system32;C:\windows;C:\windows\system32\wbem;C:\windows\system32\WindowsPowershell\v1.0;d:\jdk-10-oracle\bin;d:\icedtea-web-image-1.8.4.win\bin;d:\jdk-10-oracle\bin;d:\icedtea-web-image-1.8.4.win\bin 

Z:\tmp>set JAVA_HOME=d:\jdk-10-oracle 

Z:\tmp>set ITW_HOME=d:\icedtea-web-image-1.8.4.win 

Z:\tmp>set RUST_BACKTRACE=1 

Z:\tmp>d:\icedtea-web-image-1.8.4.win\bin\itweb-settings.exe -verbose 
itw-rust-debug: checking deployment.log.file in: C:\users\root\.config\icedtea-web\deployment.properties
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.log.file in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.log.file in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.log.file in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.log.stdstreams in: C:\users\root\.config\icedtea-web\deployment.properties
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.log.stdstreams in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.log.stdstreams in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.log.stdstreams in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.log.system in: C:\users\root\.config\icedtea-web\deployment.properties
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.log.system in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.log.system in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.log.system in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.user.logdir in: C:\users\root\.config\icedtea-web\deployment.properties
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.user.logdir in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.user.logdir in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.user.logdir in: None
itw-rust-debug: property not located or file inaccessible
d:\icedtea-web-image-1.8.4.win\bin\itweb-settings.exe
itw-rust-debug: itw mode: BUNDLED
itw-rust-debug: trying jdk over properties (deployment.jre.dir)
itw-rust-debug: checking deployment.jre.dir in: C:\users\root\.config\icedtea-web\deployment.properties
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.jre.dir in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.jre.dir in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.jre.dir in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: nothing
itw-rust-debug: trying jdk JAVA_HOME
itw-rust-debug: found and using
selected jre: d:\jdk-10-oracle
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\share/icedtea-web\javaws.jar
d:\icedtea-web-image-1.8.4.win\share/icedtea-web\javaws.jar
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\share/icedtea-web\plugin.jar
d:\icedtea-web-image-1.8.4.win\share/icedtea-web\plugin.jar
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\share/icedtea-web\jsobject.jar
d:\icedtea-web-image-1.8.4.win\share/icedtea-web\jsobject.jar
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\share/icedtea-web\js.jar
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\linux-deps-runtime\js.jar
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\win-deps-runtime\js.jar
d:\icedtea-web-image-1.8.4.win\win-deps-runtime\js.jar
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\share/icedtea-web\tagsoup.jar
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\linux-deps-runtime\tagsoup.jar
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\win-deps-runtime\tagsoup.jar
d:\icedtea-web-image-1.8.4.win\win-deps-runtime\tagsoup.jar
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\share/icedtea-web\mslinks.jar
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\linux-deps-runtime\mslinks.jar
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\win-deps-runtime\mslinks.jar
d:\icedtea-web-image-1.8.4.win\win-deps-runtime\mslinks.jar
itw-rust-debug: checking deployment.launcher.rust.bootcp.remove in: C:\users\root\.config\icedtea-web\deployment.properties
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.launcher.rust.bootcp.remove in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.launcher.rust.bootcp.remove in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.launcher.rust.bootcp.remove in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.launcher.rust.bootcp.add in: C:\users\root\.config\icedtea-web\deployment.properties
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.launcher.rust.bootcp.add in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.launcher.rust.bootcp.add in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.launcher.rust.bootcp.add in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.launcher.rust.cp.remove in: C:\users\root\.config\icedtea-web\deployment.properties
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.launcher.rust.cp.remove in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.launcher.rust.cp.remove in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.launcher.rust.cp.remove in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.launcher.rust.cp.add in: C:\users\root\.config\icedtea-web\deployment.properties
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.launcher.rust.cp.add in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.launcher.rust.cp.add in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: checking deployment.launcher.rust.cp.add in: None
itw-rust-debug: property not located or file inaccessible
itw-rust-debug: exemplar boot classpath: -Xbootclasspath/a:C:/Users/jenkins/workspace/icedtea-web_build_x86-64_windows/icedtea-web-image/share/icedtea-web/javaws.jar;C:/Users/jenkins/workspace/icedtea-web_build_x86-64_windows/icedtea-web-image/share/icedtea-web/plugin.jar;C:/Users/jenkins/workspace/icedtea-web_build_x86-64_windows/icedtea-web-image/share/icedtea-web/jsobject.jar;C:/cygwin64/usr/share/rhino-1.6/lib/js.jar;C:/cygwin64/usr/share/java/tagsoup.jar;C:/cygwin64/usr/share/java/mslinks.jar
itw-rust-debug: used boot classpath: -Xbootclasspath/a:d:\icedtea-web-image-1.8.4.win\share/icedtea-web\javaws.jar;d:\icedtea-web-image-1.8.4.win\share/icedtea-web\plugin.jar;d:\icedtea-web-image-1.8.4.win\share/icedtea-web\jsobject.jar;d:\icedtea-web-image-1.8.4.win\win-deps-runtime\js.jar;d:\icedtea-web-image-1.8.4.win\win-deps-runtime\tagsoup.jar;d:\icedtea-web-image-1.8.4.win\win-deps-runtime\mslinks.jar;d:\jdk-10-oracle\lib\ext\nashorn.jar;
itw-rust-debug: used classpath: d:\jdk-10-oracle\lib\rt.jar;d:\jdk-10-oracle\lib\ext\jfxrt.jar;
itw-rust-debug: expected name: itweb-settings
itw-rust-debug: current name: itweb-settings.exe
itw-rust-debug: installed bin: C:/Users/jenkins/workspace/icedtea-web_build_x86-64_windows/icedtea-web-image/bin/itweb-settings
itw-rust-debug: current bin: d:\icedtea-web-image-1.8.4.win\bin\itweb-settings.exe
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\share/icedtea-web\javaws_splash.png
d:\icedtea-web-image-1.8.4.win\share/icedtea-web\javaws_splash.png
itw-rust-debug: command "d:\\jdk-10-oracle\\bin\\java" "-version"
itw-rust-debug: detected jdk 9 or up
itw-rust-debug: modular jdk
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\share/icedtea-web\itw-modularjdk.args
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\linux-deps-runtime\itw-modularjdk.args
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\win-deps-runtime\itw-modularjdk.args
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\win-deps-all\itw-modularjdk.args
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\../share/icedtea-web\itw-modularjdk.args
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\../linux-deps-runtime\itw-modularjdk.args
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\../win-deps-runtime\itw-modularjdk.args
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\../win-deps-all\itw-modularjdk.args
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\.\itw-modularjdk.args
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\bin\itw-modularjdk.args
d:\icedtea-web-image-1.8.4.win\bin\itw-modularjdk.args
itw-rust-debug: trying d:\icedtea-web-image-1.8.4.win\share/icedtea-web\jsobject.jar
d:\icedtea-web-image-1.8.4.win\share/icedtea-web\jsobject.jar
itw-rust-debug: command "d:\\jdk-10-oracle\\bin\\java" "-splash:d:\\icedtea-web-image-1.8.4.win\\share/icedtea-web\\javaws_splash.png" "@d:\\icedtea-web-image-1.8.4.win\\bin\\itw-modularjdk.args" "--patch-module" "jdk.jsobject=d:\\icedtea-web-image-1.8.4.win\\share/icedtea-web\\jsobject.jar" "-Xbootclasspath/a:d:\\icedtea-web-image-1.8.4.win\\share/icedtea-web\\javaws.jar;d:\\icedtea-web-image-1.8.4.win\\share/icedtea-web\\plugin.jar;d:\\icedtea-web-image-1.8.4.win\\share/icedtea-web\\jsobject.jar;d:\\icedtea-web-image-1.8.4.win\\win-deps-runtime\\js.jar;d:\\icedtea-web-image-1.8.4.win\\win-deps-runtime\\tagsoup.jar;d:\\icedtea-web-image-1.8.4.win\\win-deps-runtime\\mslinks.jar;d:\\jdk-10-oracle\\lib\\ext\\nashorn.jar;" "-classpath" "d:\\jdk-10-oracle\\lib\\rt.jar;d:\\jdk-10-oracle\\lib\\ext\\jfxrt.jar;" "-Dicedtea-web.bin.name=itweb-settings.exe" "-Dicedtea-web.bin.location=d:\\icedtea-web-image-1.8.4.win\\bin\\itweb-settings.exe" "net.sourceforge.jnlp.controlpanel.CommandLine" "-verbose"
thread 'main' panicked at 'Error spawning JVM process, java executable: [d:\jdk-10-oracle], arguments: [["-splash:d:\\icedtea-web-image-1.8.4.win\\share/icedtea-web\\javaws_splash.png", "@d:\\icedtea-web-image-1.8.4.win\\bin\\itw-modularjdk.args", "--patch-module", "jdk.jsobject=d:\\icedtea-web-image-1.8.4.win\\share/icedtea-web\\jsobject.jar", "-Xbootclasspath/a:d:\\icedtea-web-image-1.8.4.win\\share/icedtea-web\\javaws.jar;d:\\icedtea-web-image-1.8.4.win\\share/icedtea-web\\plugin.jar;d:\\icedtea-web-image-1.8.4.win\\share/icedtea-web\\jsobject.jar;d:\\icedtea-web-image-1.8.4.win\\win-deps-runtime\\js.jar;d:\\icedtea-web-image-1.8.4.win\\win-deps-runtime\\tagsoup.jar;d:\\icedtea-web-image-1.8.4.win\\win-deps-runtime\\mslinks.jar;d:\\jdk-10-oracle\\lib\\ext\\nashorn.jar;", "-classpath", "d:\\jdk-10-oracle\\lib\\rt.jar;d:\\jdk-10-oracle\\lib\\ext\\jfxrt.jar;", "-Dicedtea-web.bin.name=itweb-settings.exe", "-Dicedtea-web.bin.location=d:\\icedtea-web-image-1.8.4.win\\bin\\itweb-settings.exe", "net.sourceforge.jnlp.controlpanel.CommandLine", "-verbose"]]', src\os_access.rs:42:19
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: BaseThreadInitThunk
  15: RtlUserThreadStart

Z:\tmp>rem d:\icedtea-web-image-1.8.4.win\bin\javaws.exe -verbose -jnlp "https://95.180.105.28:3445/llvm-mingw/launch-pp-ispp-3445.jnlp" > z:\tmp\javaws-wine-cross-3445.log 2>&1

**Comment by sclassen** [comment]
So the easiest way to debug this is taking the command which the rust launcher executes and trying this on the console directly.
This should reproduce the issue. Then you can play with this command until you find a working configuration. Once we know what is causing the JVM to panic we can have a look on how to fix the rust launcher.

Here the command:
```
 d:\jdk-10-oracle\bin\java -splash:d:\icedtea-web-image-1.8.4.win\share/icedtea-web\javaws_splash.png @d:\icedtea-web-image-1.8.4.win\bin\itw-modularjdk.args --patch-module jdk.jsobject=d:\icedtea-web-image-1.8.4.win\share/icedtea-web\jsobject.jar -Xbootclasspath/a:d:\icedtea-web-image-1.8.4.win\share/icedtea-web\javaws.jar;d:\icedtea-web-image-1.8.4.win\share/icedtea-web\plugin.jar;d:\icedtea-web-image-1.8.4.win\share/icedtea-web\jsobject.jar;d:\icedtea-web-image-1.8.4.win\win-deps-runtime\js.jar;d:\icedtea-web-image-1.8.4.win\win-deps-runtime\tagsoup.jar;d:\icedtea-web-image-1.8.4.win\win-deps-runtime\mslinks.jar;d:\jdk-10-oracle\lib\ext\nashorn.jar; -classpath d:\jdk-10-oracle\lib\rt.jar;d:\jdk-10-oracle\lib\ext\jfxrt.jar; -Dicedtea-web.bin.name=itweb-settings.exe -Dicedtea-web.bin.location=d:\icedtea-web-image-1.8.4.win\bin\itweb-settings.exe net.sourceforge.jnlp.controlpanel.CommandLine -verbose
```

**Comment by vladimir-kokovic** [comment]
Finally with version of wine-6.4-319-g12cfe882677 there is no longer "Can't recognize ..." but there is something specific in wine-rust env because rust now in the log file reports the following:
```
itw-rust-debug: command "d:\\jdk-10-oracle\\bin\\java" "-version"
itw-rust-debug: unrecognized jdk! Fallback to 8!
itw-rust-debug: non-modular jdk
itw-rust-debug: command "d:\\jdk-10-oracle\\bin\\java" "-splash:d:\\icedtea-web-image-1.8.4.win\\share/icedtea-web\\javaws_splash.png" "-Xbootclasspath/a:d:\\icedtea-web-image-1.8.4.win\\share/icedtea-web\\javaws.jar;d:\\icedtea-web-image-1.8.4.win\\share/icedtea-web\\plugin.jar;d:\\icedtea-web-image-1.8.4.win\\share/icedtea-web\\jsobject.jar;d:\\icedtea-web-image-1.8.4.win\\win-deps-runtime\\js.jar;d:\\icedtea-web-image-1.8.4.win\\win-deps-runtime\\tagsoup.jar;d:\\icedtea-web-image-1.8.4.win\\win-deps-runtime\\mslinks.jar;d:\\jdk-10-oracle\\lib\\ext\\nashorn.jar;" "-classpath" "d:\\jdk-10-oracle\\lib\\rt.jar;d:\\jdk-10-oracle\\lib\\ext\\jfxrt.jar;" "-Dicedtea-web.bin.name=javaws.exe" "-Dicedtea-web.bin.location=d:\\icedtea-web-image-1.8.4.win\\bin\\javaws.exe" "net.sourceforge.jnlp.runtime.Boot" "-verbose" "-jnlp" "https://95.180.105.28:3445/llvm-mingw/launch-pp-ispp-3445.jnlp"
```
For some unknown reason, the Pale Moon browser will not do attach file, so I did not attach a complete log file.

**Comment by sclassen** [comment]
can you try the command from my last reply and see if this works

**Comment by vladimir-kokovic** [comment]
I tried your command and as I said the command now works correctly.
The problem with D:\jdk-10-oracle was that for some reason I added a folder D:\jdk-10-oracle\lib\ext and that folder has caused rust to find that jdk is "non-modular jdk".
Regardless, I think ITW is correct and that it is not a problem until further.
