### ISSUE TITLE
Publish jnlp-api in a publich maven repository

### ISSUE THREAD

**Issue by kaklakariada** [AdoptOpenJDK/IcedTea-Web#789]
I would like to use the [jnlp-api](https://github.com/AdoptOpenJDK/IcedTea-Web/tree/master/jnlp-api) module in my open source application deployed via [OpenWebStart](https://github.com/karakun/OpenWebStart).

A search on Maven Central (https://search.maven.org/search?q=jnlp-api) finds nothing.

* Is the API maybe published to another public maven repository?
* Is there another artifact providing the WebStart API published to a maven repository?
* What is the recommended way to include the jnlp-api in projects that are deployed using WebStart and want to use the WebStart API?

Thank you very much for your help!

**Comment by sclassen** [comment]
Sorry, the JNLP api is licensed by Oracle and we are not allowed to publish this.
You need to talk to Oracle but I see little chance in success.

**Comment by kaklakariada** [comment]
Thank you for the clarification. I had hoped this was possible.
