### ISSUE TITLE
JNLP UserAgent (Java/) is  different from Oracle (JNLP/)

### ISSUE THREAD

**Issue by andreipiv** [AdoptOpenJDK/IcedTea-Web#791]
I have a legacy application and for a long list of reasons, the UserAgent is relied upon for certain requests (and updating the legacy app is a HUGE PITA). 

When JWS requests .JAR files, In Oracle JRE, the User Agent is JNLP/<version>, but ITW sets it to Java/<version>

I didn't find anything specific in the JSR spec, so it's probably a long shot, but it would great if we could be a happy family and be consistent/same.

**Comment by sclassen** [comment]
Yes, but we will not change this as we do not know if other JNLP application depend on the way ITW is implemented now.
You can use OpenWebStart. It contains a patch which allows to set the UserAgent in the JNLP file as a property

**Comment by andreipiv** [comment]
We could set it up as a deployment property as well, but
Alright, sounds good. 

I can use OWS, but my customer can't. I'll try to update the application

**Comment by franferrax** [comment]
Just in case someone comes here and wonders which property is referring @andreipiv, we can use the [`http.agent` system property](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/doc-files/net-properties.html#MiscHTTP).

For example, the following setting will send `User-Agent: JNLP/1.7.0 javaws/11.351.2.10 (<internal>) Java/<version>`:
* _Linux_
  ```sh
  export JAVA_TOOL_OPTIONS='-Dhttp.agent="JNLP/1.7.0 javaws/11.351.2.10 (<internal>)"'
  ```
* _Windows_
  ```batch
  set JAVA_TOOL_OPTIONS=-Dhttp.agent="JNLP/1.7.0 javaws/11.351.2.10 (<internal>)"
  ```
