### ISSUE TITLE
Cisco ASDM is not working 

### ISSUE THREAD

**Issue by calippus** [AdoptOpenJDK/IcedTea-Web#799]
I am using asdm-openjre-7141-48.bin in Cisco 5508. 
icedtea-web-1.7.1-1.el7.x86_64 and java-1.8.0-openjdk-1.8.0.181-7.b13.el7.x86_64 are installed on my CentOS 7

After execution of "javaws https://10.49.10.91/admin/public/asdm.jnlp" the login screen appears and I am entering the username and password then nothing happens.

Here is the log when I execute javaws; 
[asdm-icedtea.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/6433166/asdm-icedtea.log)

**Comment by sclassen** [comment]
See: https://github.com/AdoptOpenJDK/IcedTea-Web/issues/741
