### ISSUE TITLE
Incoherent error messages in the log file

### ISSUE THREAD

**Issue by ansanes** [AdoptOpenJDK/IcedTea-Web#807]
While running my java application via javaws I'm getting these 2 messages:

```
This application does not specify a Codebase in its manifest. Please verify with the applet's vendor. Continuing.
See: http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/security/no_redeploy.html for details.
```

```
Application title was not found in manifest. Check with application vendor
```

I have both title and codebase attributes set correctly in my jnlp file.

**Comment by sclassen** [comment]
Are these values also set in the manifest of the main jar of your application?
Because this is what the warning is suggesting is missing

**Comment by ansanes** [comment]
> 
> 
> Are these values also set in the manifest of the main jar of your application?
> Because this is what the warning is suggesting is missing

No it doesn't. That's probably it. Do you know which specific headear do I have to set?

Thanks.

**Comment by sclassen** [comment]
For the "title" you should use `Application-Name` and for the "codebase" use `Codebase`
