### ISSUE TITLE
IcedTea-Web and basic http authentication: Credentials are required multiple times

### ISSUE THREAD

**Issue by mada0068** [AdoptOpenJDK/IcedTea-Web#811]
Hi. I have an app in my university with authentication. The authentication dialog asks for the user-password multiple times. I am running ver. 1.8.4 on Ubuntu 21.04 and openjdk 11.0.11, and it happens as issue 607 describes 

https://github.com/AdoptOpenJDK/IcedTea-Web/issues/607

but it seems not solved yet, at least in my setup

**Comment by sclassen** [comment]
Yes this is only fixed in the 2.x branch.
So far there is no release of the 2.x branch.
But you can use https://github.com/karakun/OpenWebStart which is based on the 2.x branch of icedtea-web

**Comment by mada0068** [comment]
Thanks a lot! I will try this way until next version
