### ISSUE TITLE
ITW  Certificates - How-To

### ISSUE THREAD

**Issue by csottile** [AdoptOpenJDK/IcedTea-Web#812]
Hi all,

some questions about using certificates in ITW.

Is it possible to constrain ITW to access Windows KeyStore? Windows-ROOT or Windows-MY?
Our customer is a large company and his deployment system periodically update this key-store on user local machines.

Thx

**Comment by csottile** [comment]
Hi all,
any feedback for me?

thanks

**Comment by sclassen** [comment]
Have a look at https://board.karakun.com/viewtopic.php?f=21&t=8290
