### ISSUE TITLE
jre of the properties file does not work under windows

### ISSUE THREAD

**Issue by AndreasEhret** [AdoptOpenJDK/icedtea-web#82]
This issue was imported from bugzilla with bugzilla2github
# Bugzilla Bug Referenze: [3711](https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3711)
Date: 2019-03-22 09:38:00 +0000
From: Lars Herschke &lt;<lhersch>&gt;
To:   JiriVanek &lt;<jvanek>&gt;
CC:   unassigned

Last updated: 2019-03-22 11:57:34 +0000

## Comment 17473
Date: 2019-03-22 09:38:41 +0000
From: Lars Herschke &lt;<lhersch>&gt;

Created attachment 1727
                fix for the problem described

                Enclosed a patch that fixes the following things.

                - Check under windows against java.exe, instead of java, both in rust-launcher and in itweb-settings
                - Unmasking the colon at properties in the rust launcher
            

> Attached file: src_1591_a18f57158e40.patch (text/plain, 5870 bytes)
> Description:   fix for the problem described

## Comment 17474
Date: 2019-03-22 11:57:34 +0000
From: Lars Herschke &lt;<lhersch>&gt;

pull request:
                https://github.com/AdoptOpenJDK/icedtea-web/pull/3

**Comment by lherschi** [comment]
Can be closed. Pull request was merged into master
