### ISSUE TITLE
Question about applet support

### ISSUE THREAD

**Issue by markdbuck** [AdoptOpenJDK/IcedTea-Web#823]
I know that this is not an issue, but I was unable to find anyplace to post a question. Apologies in advance if I am breaking protocol.
I am using v1.8.4 to launch an applet successfully. I thought at one point, I had found a reference that ITW would no longer support applets starting wtih v 2.x. Can someone confirm whether it is still the intention to no longer support applets in the future?

**Comment by sclassen** [comment]
Yes, the applet support has already been removed from the 2.x branch.
There are no up-to-date browser available which support applets. So even if ITW would continue to support applets they could not be launched in any browser.

**Comment by wicalb** [comment]
> I know that this is not an issue, but I was unable to find anyplace to post a question. Apologies in advance if I am breaking protocol.
> I am using v1.8.4 to launch an applet successfully. I thought at one point, I had found a reference that ITW would no longer support applets starting with v 2.x. Can someone confirm whether it is still the intention to no longer support applets in the future?

Which ITW is the most compatible without any know security issues for applet support
