### ISSUE TITLE
Supported values of deployment.properties file

### ISSUE THREAD

**Issue by getvpro** [AdoptOpenJDK/IcedTea-Web#839]
Hello

I'm assisting a client to evaluate using AdoptOpenJDK / Iced Tea Web for JNLP support to replace Oracle Java, the client is on a Citrix VDI setup, Win 10 20H1

For approx 2 years, we've had the following two lines in the c:\windows\sun\deployment\deployment.properties file

deployment.javaws.jre.0.args=-Dsun.java2d.d3d\=false -Dsun.java2d.noddraw\=true
deployment.javaws.jre.1.args=-Dsun.java2d.d3d\=false -Dsun.java2d.noddraw\=true

This is to correct slowness with JNLP apps as per https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/java2d-props002.html

However, we've found with AdoptOpenJDK and Iced Tea web, despite the above value being in place for the user's deployment.properties file, the JNLP UI performance is very slow. It appears the above parameters aren't being read?

is there a way to confirm which deployment.properties parameters are supported with AdoptOpenJDK and Ice tea web? Or is it assumed that ALL values are supported ?

**Comment by sclassen** [comment]
'deployment.javaws.jre' is currently not supported in ITW.
The complete list of supported properties is in this java file
https://github.com/AdoptOpenJDK/IcedTea-Web/blob/master/core/src/main/java/net/sourceforge/jnlp/config/ConfigurationConstants.java
