### ISSUE TITLE
jar files downloaded every run (Not using cache)

### ISSUE THREAD

**Issue by jamespet77** [AdoptOpenJDK/IcedTea-Web#870]
I am trying to run a jnlp file and the javaws command re-downloads the jar files every run.  I have checked the cache the the files exist.  
Expected behavior:  javaws should recognize the cached files exist and use then instead of re-downloading. 

Linux 5.13.0-39-generic #44-Ubuntu SMP Thu Mar 24 15:35:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jamespet77** [comment]
Nevermind.  I was running the old javaws.  I installed the OpenWebStart version and it is working fine.

**Comment by sclassen** [comment]
There can be different reasons for this behavior. Can you create log files and attache them to this issue?

Am 19. April 2022 20:28:50 MESZ schrieb James Peterson ***@***.***>:
