### ISSUE TITLE
Jar signed with Sectigo Code Signing CA is not trusted

### ISSUE THREAD

**Issue by rjaros** [AdoptOpenJDK/IcedTea-Web#871]
When running webstart application signed with Sectigo Code Signing certificate the warning is shown stating the issuer of the certificate is not trusted. The same jar is correctly verified with `jarsigner` tool.
```
     X.509, CN=FINN Sp. z o.o., O=FINN Sp. z o.o., ST=Łódzkie, C=PL
      [certificate is valid from 28.04.22 02:00 to 29.04.23 01:59]
      X.509, CN=Sectigo Public Code Signing CA R36, O=Sectigo Limited, C=GB
      [certificate is valid from 22.03.21 01:00 to 22.03.36 00:59]
      X.509, CN=Sectigo Public Code Signing Root R46, O=Sectigo Limited, C=GB
      [certificate is valid from 25.05.21 02:00 to 01.01.29 00:59]
```
The `Sectigo Public Code Signing Root R46` certificate is cross signed with `C = GB, ST = Greater Manchester, L = Salford, O = Comodo CA Limited, CN = AAA Certificate Services`, which is trusted by JDK. I think the implementation in https://github.com/AdoptOpenJDK/IcedTea-Web/blob/master/core/src/main/java/net/sourceforge/jnlp/tools/JarCertVerifier.java is not working correctly with cross signed certificates.

**Comment by rjaros** [comment]
Adding the root certificate to the signing keystore fixes the problem.

**Comment by aamcurtis** [comment]
@rjaros would you be able to expand on what you did to solve this? I'm facing the same issue with a sectigo cert E46. When signing via a yubikey both certs ( E46 and the AAA services ) are included as part of the keystore.

Infuritating because this setup works for Oracle but not ITW and openJDK

**Comment by rjaros** [comment]
I'm signing my jar with a keystore file containing all **4** certificates (my cert, "Sectigo Public Code Signing CA R36", "Sectigo Public Code Signing Root R46" and "AAA Certificate Services"). I was missing the AAA certificate with my first tries.
