### ISSUE TITLE
javaws.policy file not being read - not supported or bug?

### ISSUE THREAD

**Issue by mibyge** [AdoptOpenJDK/IcedTea-Web#876]
Hello.

I'm trying to make a Java Web Start application work with Eclipse Temurin 8 U332 and IcedTea-Web 1.8.8 on Windows 10 x64 v20H2 so we can get rid of Oracle JRE. 

I can get it working by added the line below to the java.policy file in the general grant section:

`permission java.io.FilePermission "<<ALL FILES>>", "read, write, execute";`

However, when comparing the files in the \lib\security folder for an Oracle JRE and Temurin/IcedTea-Web installation, I can see that Oracle has an additional file named javaws.policy with the following content:

`grant codeBase "file:${jnlpx.home}/javaws.jar" {
    permission java.security.AllPermission;
};`

This file is not a part of the IcedTea-Web installation, and when using ProcMon to see what's going on, I don't see Temurin/IcedTea-Web even attempting to read the javaws.policy file, while it does read the java.policy file.

Is the javaws.policy file not supported in Temurin/IcedTea-Web or is this a bug?

I'm not sure if it's a Eclipse Temurin or IcedTea-Web issue, so I've taken the liberty of creating the issue in both projects.

Thanks in advance :)

**Comment by jiekang** [comment]
I see in ITW source code java.policy file and it being read from https://github.com/AdoptOpenJDK/IcedTea-Web/blob/d61daea558b27cdb34c8db9c860fae5cd96ef94d/core/src/main/java/net/sourceforge/jnlp/config/PathsAndFiles.java#L142 however haven't seen similar for javaws.policy. So likely not supported for ITW. I don't think it's a JDK issue whether that's Temurin or another non Oracle ITW distribution.

**Comment by mibyge** [comment]
OK. Seems like javaws.policy is an Oracle thing then.

Thanks for checking :)
