### ISSUE TITLE
LinkageError duplicate class definition

### ISSUE THREAD

**Issue by nbauma109** [AdoptOpenJDK/IcedTea-Web#910]
Hello,

I'm experiencing a similar issue to #782 fixed by #783.
I use release 1.8.8 and I thought this fix was included.
Issue seems to happen randomly on concurrent class loading from a class name.

After investigating it seems that the JNLPClassLoader class used is an old one from net.sourceforge.jnlp.runtime package instead of net.sourceforge.jnlp.runtime.classloader package.

The class name that appears in the exception log is the one with the old package name.

When is it planned to release 2.x?

Thanks

**Comment by lherschi** [comment]
The backport for the 1.8 branch was comitted after the 1.8.8 release.

https://github.com/AdoptOpenJDK/IcedTea-Web/issues/878

**Comment by nbauma109** [comment]
Ok closed as duplicate of #878
