### ISSUE TITLE
MSI does not register jnlp files

### ISSUE THREAD

**Issue by AndreasEhret** [AdoptOpenJDK/icedtea-web#92]
This issue was imported from bugzilla with bugzilla2github
# Bugzilla Bug Referenze: [3706](https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3706)
Date: 2019-03-11 23:26:00 +0000
From: Mingye Wang &lt;<arthur200126>&gt;
To:   JiriVanek &lt;<jvanek>&gt;
CC:   gnu.andrew

Last updated: 2019-03-20 23:08:52 +0000

## Comment 17451
Date: 2019-03-11 23:26:15 +0000
From: Mingye Wang &lt;<arthur200126>&gt;

The current version of the IcedTea-Web MSI installer adds an association for jnlp:// protocol, but
                not for the file format. That results in some additional setup before it becomes... functional.

                The way JRE8 sets it up is available from
                https://bugs.openjdk.java.net/browse/JDK-7178591#comment-13437718. The Content-Type used there may be
                useful.
            

## Comment 17452
Date: 2019-03-12 15:05:33 +0000
From: JiriVanek &lt;<jvanek>&gt;

The issue, is - that 1.7 have only bat files. AFAIk those can not be set as file asociations. So
                this should fix itself with 1.8, which is being released today.
            

## Comment 17470
Date: 2019-03-20 22:51:14 +0000
From: Mingye Wang &lt;<arthur200126>&gt;

> 1.8

                Ah, that's good to know. Getting a proper executable also helps with the file icon and stuff.

                > AFAIK..

                My windows 10 (build 17763) is remembering the one time I told it to open a .jnlp file with javaws.bat
                though:
                [HKEY_CURRENT_USER\Software\Classes\jnlp_auto_file\shell\open\command]
                @="\"C:\\Program Files\\IcedTeaWeb\\WebStart\\bin\\javaws.bat\" \"%1\""

                Could be a new Windows feature thing.
            

## Comment 17471
Date: 2019-03-20 23:08:52 +0000
From: Mingye Wang &lt;<arthur200126>&gt;

Tried the 1.8. No association yet.

                There are a few new problems with, well, not changing win-installer/installer.json:
                * The Major.Minor.Micro.Patch number is not changed. You might want some sed/cut dance[1] in
                configure.ac just to make those things separate variables available for m4 substitution.
                * It still says javaws.bat.

                [1]: https://github.com/dgoulet/lttng-ust-dev/blob/9f00ce3/configure.ac#L30-L40

**Comment by lherschi** [comment]
see pull request:
https://github.com/AdoptOpenJDK/icedtea-web/pull/151

**Comment by lherschi** [comment]
Can be closed. Pull request was merged into master.

**Comment by douph1** [comment]
Yes, it works.
Jnlp file just missing ITW icon and use default one from Windows but it can be inproved in another issue
