### ISSUE TITLE
Java 21: NoSuchMethodError: 'java.lang.Boolean sun.security.x509.NetscapeCertTypeExtension.get(java.lang.String)'

### ISSUE THREAD

**Issue by tsmock** [AdoptOpenJDK/IcedTea-Web#922]
OWS-Scm-Commit: d37be116
Scm-Commit: 39decdf5

```
java.lang.NoSuchMethodError: 'java.lang.Boolean sun.security.x509.NetscapeCertTypeExtension.get(java.lang.String)'
	at net.sourceforge.jnlp.tools.JarCertVerifier.checkCertUsage(JarCertVerifier.java:612)
	at net.sourceforge.jnlp.tools.JarCertVerifier.verifyJarEntryCerts(JarCertVerifier.java:366)
	at net.sourceforge.jnlp.tools.JarCertVerifier.verifyJar(JarCertVerifier.java:290)
	at net.sourceforge.jnlp.tools.JarCertVerifier.verifyJars(JarCertVerifier.java:251)
	at net.sourceforge.jnlp.tools.JarCertVerifier.add(JarCertVerifier.java:225)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.initializeResources(JNLPClassLoader.java:709)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.<init>(JNLPClassLoader.java:350)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.createInstance(JNLPClassLoader.java:423)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:495)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:468)
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:584)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:373)
	at net.sourceforge.jnlp.Launcher.access$300(Launcher.java:71)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:660)
```

**Comment by tsmock** [comment]
Still present with:
OWS-Scm-Commit: 32e937c9
Scm-Commit: bee22fd5

**Comment by tsmock** [comment]
Steps to reproduce (copied from log files, home directory replaced with `${HOME}`):
`${HOME}/.cache/icedtea-web/jvm-cache/azul_21.0.1_x64/bin/java -Xbootclasspath/a:/Applications/OpenWebStart/openwebstart.jar -Djava.util.Arrays.useLegacyMergeSort=true --add-exports=jdk.deploy/com.sun.deploy.config=ALL-UNNAMED --add-opens=java.desktop/javax.swing.text.html=ALL-UNNAMED --add-reads=java.naming=ALL-UNNAMED,java.desktop --add-exports=java.base/sun.security.action=ALL-UNNAMED,java.desktop --add-reads=java.base=ALL-UNNAMED,java.desktop --add-exports=java.naming/com.sun.jndi.toolkit.url=ALL-UNNAMED,java.desktop --add-opens=java.base/jdk.internal.loader=ALL-UNNAMED --add-exports=java.desktop/com.apple.eawt=ALL-UNNAMED --add-exports=java.desktop/sun.awt=ALL-UNNAMED,java.desktop --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED --add-exports=java.base/sun.security.validator=ALL-UNNAMED,java.desktop --add-exports=java.desktop/com.sun.imageio.plugins.jpeg=ALL-UNNAMED --add-exports=java.base/sun.net.www.protocol.jar=ALL-UNNAMED,java.desktop --add-exports=java.base/jdk.internal.util.jar=ALL-UNNAMED,java.desktop --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED --add-exports=java.base/com.sun.net.ssl.internal.ssl=ALL-UNNAMED,java.desktop --add-exports=javafx.graphics/com.sun.javafx.application=ALL-UNNAMED --add-modules=java.scripting,java.sql,javafx.controls,javafx.media,javafx.swing,javafx.web --add-exports=java.desktop/sun.awt.X11=ALL-UNNAMED,java.desktop --add-exports=java.desktop/sun.applet=ALL-UNNAMED,java.desktop,jdk.jsobject --add-exports=java.base/sun.net.www.protocol.http=ALL-UNNAMED,java.desktop --add-opens=java.base/java.lang=ALL-UNNAMED --add-exports=java.base/sun.security.util=ALL-UNNAMED,java.desktop --add-exports=java.desktop/com.sun.imageio.spi=ALL-UNNAMED --add-reads=java.desktop=ALL-UNNAMED,java.naming --add-opens=java.base/java.nio=ALL-UNNAMED --add-exports=java.base/sun.security.x509=ALL-UNNAMED,java.desktop --add-opens=java.desktop/javax.imageio.spi=ALL-UNNAMED --add-exports=java.desktop/javax.jnlp=ALL-UNNAMED,java.desktop --add-exports=java.base/sun.security.provider=ALL-UNNAMED,java.desktop -Djava.security.manager=allow -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=127.0.0.1:5005 net.sourceforge.jnlp.runtime.Boot -Xnofork ${HOME}/workspace/josm/core/native/josm.jnlp`

josm.jnlp is available at https://josm.openstreetmap.de/browser/josm/trunk/native/josm.jnlp

**Comment by sclassen** [comment]
Signature changed from `public Boolean get(String name)` -> `public boolean get(String name)`

**Comment by tsmock** [comment]
A simple (but probably stupid) workaround would be to compile that class (and its dependencies) twice, copy only this class to `META-INF/versions/21/net/sourceforge/jnlp/tools/` and create a multi-release jar (set `Multi-Release: true` in the `MANIFEST.MF`).

Useful documentation: https://maven.apache.org/plugins/maven-compiler-plugin/multirelease.html

**Comment by nchava1** [comment]
Is  there any fix for this?

**Comment by tsmock** [comment]
@nchava1 : None that people _should_ use.

The project I work on (JOSM) _accidentally_ worked around this problem when we decided to [not renew](https://josm.openstreetmap.de/ticket/23107) the code signing certificate -- we are using a self-signed certificate now due to new requirements by the certificate providers.

**Comment by chrisjansen3380** [comment]
Hi,
will a fix be created for this issue? I'm facing the same problem, and I cannot revert to a self signed certificate.
thx

**Comment by sclassen** [comment]
We plan to release a fixed version before the end of the year.
Until then the only workaround is to install version 1.8.0 and not update to 1.9.0

**Comment by chrisjansen3380** [comment]
great, thx!

**Comment by janakmulani** [comment]
https://github.com/AdoptOpenJDK/IcedTea-Web/pull/929.

Tested with https://spdf.gsfc.nasa.gov/skteditor/skteditor.jnlp

**Comment by nchava1** [comment]
Hi, Any targeted release for this fix ?   Thanks.

**Comment by janakmulani** [comment]
https://github.com/karakun/OpenWebStart/releases
