### ISSUE TITLE
IcedTea encountered an error when using -XX:NativeMemoryTracking=detail: Segmentation fault.

### ISSUE THREAD

**Issue by fe19880924** [AdoptOpenJDK/IcedTea-Web#924]
jdk version:
openjdk version "1.8.0_372"
OpenJDK Runtime Environment (IcedTea 3.27.0) (Alpine 8.372.07-r0)
OpenJDK 64-Bit Server VM (build 25.372-b07, mixed mode)

tomcat runtime: 
Using CATALINA_BASE:   /usr/local/tomcat
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /usr/local/tomcat/temp
Using JRE_HOME:        /usr/lib/jvm/java-1.8-openjdk
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
Using CATALINA_OPTS:   
Server version: Apache Tomcat/9.0.74
Server built:   Apr 13 2023 08:10:39 UTC
Server number:  9.0.74.0
OS Name:        Linux
OS Version:     4.14.273-207.502.amzn2.x86_64
Architecture:   amd64
JVM Version:    1.8.0_372-b07
JVM Vendor:     IcedTea

tomcat command:
440dcb467a8c:/usr/local/tomcat/bin$ JAVA_OPTS=-XX:NativeMemoryTracking=detail
440dcb467a8c:/usr/local/tomcat/bin$ ./catalina.sh run
Using CATALINA_BASE:   /usr/local/tomcat
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /usr/local/tomcat/temp
Using JRE_HOME:        /usr/lib/jvm/java-1.8-openjdk
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
Using CATALINA_OPTS:   
Segmentation fault (core dumped)

last create file core.xxx, download by: https://html.hrhrh.com/temp/core.19

**Comment by lherschi** [comment]
IcedTea is not the same as IcedTea-Web.
This error message is therefore in the completely wrong repository here.

**Comment by lherschi** [comment]
The issue should be closed, as the error message has absolutely nothing to do with IcedTea-Web.
