### ISSUE TITLE
JNLP with querystring in href causes IllegalResourceDescriptorException Location ...?querystring does not specify a resource being tracked

### ISSUE THREAD

**Issue by merkisoft** [AdoptOpenJDK/IcedTea-Web#928]
using Open Webstart 1.9.0

Could not read or parse the JNLP file at 'https://www.kursweb.ch:443/webstart/webstart.selfsigned.jnlp?db=C:\Users\Fabian\merkisoft\ferienplausch-uster\&name=C:\Users\Fabian\merkisoft\ferienplausch-uster\'. (net.adoptopenjdk.icedteaweb.resources.IllegalResourceDescriptorException: Location https://www.kursweb.ch/webstart/webstart.selfsigned.jnlp?db=C:%5CUsers%5CFabian%5Cmerkisoft%5Cferienplausch-uster%5C&name=C:%5CUsers%5CFabian%5Cmerkisoft%5Cferienplausch-uster%5C does not specify a resource being tracked. 

I assume this is the related change, but I did not figure out why (tests would be nice :-)):
https://github.com/AdoptOpenJDK/IcedTea-Web/commit/292a153da52348728a59540234fdd10ae76ea871

it used to work in the previous version (1.8.0):

[ITW-CORE][2023-11-27 20:43:54.571 MEZ][DEBUG][net.adoptopenjdk.icedteaweb.resources.ResourceTracker] Create resource for 'https://www.kursweb.ch/webstart/webstart.selfsigned.jnlp?db=C:%5CUsers%5CFabian%5Cmerkisoft%5Cferienplausch-uster%5C&name=C:%5CUsers%5CFabian%5Cmerkisoft%5Cferienplausch-uster%5C'
[ITW-CORE][2023-11-27 20:43:54.571 MEZ][DEBUG][net.sourceforge.jnlp.JNLPFile] Parsing JNLP file
location: https://www.kursweb.ch/webstart/webstart.selfsigned.jnlp?db=C:%5CUsers%5CFabian%5Cmerkisoft%5Cferienplausch-uster%5C&name=C:%5CUsers%5CFabian%5Cmerkisoft%5Cferienplausch-uster%5C

btw, the url without query string works in both versions: https://kursweb.ch/webstart/webstart.selfsigned.jnlp

**Comment by merkisoft** [comment]
[working-2023-11-27_20_43_53.531-ows-stage1.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/13551275/working-2023-11-27_20_43_53.531-ows-stage1.log)
[broken-2023-12-04_21_57_17.490-ows-stage1.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/13551276/broken-2023-12-04_21_57_17.490-ows-stage1.log)

**Comment by sclassen** [comment]
After running some tests I think it is more likely due to the fact that in the log some of the URL contain the port and some do not.

`JNLP file location: https://www.kursweb.ch:443/webstart/webstart.selfsigned.jnlp?db=...`

vs.

`https://www.kursweb.ch/webstart/webstart.selfsigned.jnlp?db=...`

Is there a way you can start the JNLP file without adding the port?

**Comment by merkisoft** [comment]
perfect! you are right. the port number broke it. thx!

**Comment by sclassen** [comment]
Can we close this or is this still a unusable for you?

**Comment by merkisoft** [comment]
did it myself :-)

**Comment by janakmulani** [comment]
https://github.com/AdoptOpenJDK/IcedTea-Web/pull/930
