### ISSUE TITLE
Bug: Fatal: Read Error: Could not read or parse the JNLP file

### ISSUE THREAD

**Issue by Hani-Arina** [AdoptOpenJDK/IcedTea-Web#950]
Hi IcedTea-Web Support Team. 

One of the users for Rapid Response application is encountering an issue when attempting to open a Rapid Response JNLP file using javaws.exe. It will return a Fatal Read Error: "Could not read or parse the JNLP file"

OpenJDK: Eclipse Adoptium jdk-8.0.332.9-hotspot
IcedTeaWeb version: 1.8.8
OS: Microsoft Windows 11

I have attached the error message and the error log for your reference.
![error parse JNLP file](https://github.com/AdoptOpenJDK/IcedTea-Web/assets/126647503/add1e1c5-927f-47f3-962e-35076dd0a862)
[error parse log.txt](https://github.com/user-attachments/files/15907276/error.parse.log.txt)

We have tried to clear the Java Cache and the temporary cache in the impacted user's computer. We also tried setting up network proxy by using automatic proxy configuration script. But the issue is not fixed. Other users in the same site are able to access the Rapid Response application but not for this user.

Please help to advise what can be done to fix this issue.

**Comment by sclassen** [comment]
This error usually is the consequence of an error further up in the logs.
Most often it is an network or proxy problem which blocks the download of the JNLP or other resource.

Either post the entire log file or search yourself for errors in the downloading phase
