### ISSUE TITLE
DownloadService2 not registered in XServiceManagerStub

### ISSUE THREAD

**Issue by AndreasEhret** [AdoptOpenJDK/IcedTea-Web#99]
This issue was imported from bugzilla with bugzilla2github
# Bugzilla Bug Referenze: [3689](https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3689)
Date: 2019-01-29 13:24:00 +0000
From: jc.garcia.gomez
To:   JiriVanek &lt;<jvanek>&gt;
CC:   jimdouglas, unassigned

Last updated: 2019-02-14 13:57:00 +0000

## Comment 17280
Date: 2019-01-29 13:24:03 +0000
From: jc.garcia.gomez

I am getting a javax.jnlp.UnavailableServiceException when perfoming a lookup of
                javax.jnlp.DownloadService2.

                Possible cause: javax.jnlp.DownloadService2 is not "registered" in the arrays in
                net.sourceforge.jnlp.services.XServiceManagerStub, at least in the source code I have been able to view.
            

## Comment 17298
Date: 2019-02-07 06:17:48 +0000
From: JiriVanek &lt;<jvanek>&gt;

hi!
                Do you have reproducer for this issue?

                Otherwise you seems to be right. The DownloadService2 seems to be implemented, but not registered.
            

## Comment 17300
Date: 2019-02-07 07:12:57 +0000
From: jc.garcia.gomez

Hi!

                I do not have a reproducer, sorry.

                I have detected the issue developing a JWS application for our Intranet enviroment.

                However, you can reproduce it consistently by invoking the method lookup of the class ServiceManager
                with DownloadService2 as parameter:

                ServiceManager.lookup("javax.jnlp.DownloadService2");

                Thank you
            

## Comment 17346
Date: 2019-02-08 12:07:47 +0000
From: JiriVanek &lt;<jvanek>&gt;

Maybe you can prepare reproducer please? It will speed up a fix a lot.
                I had eyballed ITW, and the chage really should be strightforward. Only I'm hesitating with way, how to
                verify the fix.
            

## Comment 17357
Date: 2019-02-11 17:42:26 +0000
From: Jim Douglas &lt;<jimdouglas>&gt;

If someone is going to be in DownloadService2.java, note this typo:

                http://mail.openjdk.java.net/pipermail/distro-pkg-dev/2019-February/041033.html
            

## Comment 17358
Date: 2019-02-12 09:24:57 +0000
From: JiriVanek &lt;<jvanek>&gt;

Hi Jim! Your patch was not missed. I will push it today. Thank you for it!

## Comment 17359
Date: 2019-02-12 14:10:53 +0000
From: jc.garcia.gomez

(In reply to JiriVanek from comment #3)
                > Maybe you can prepare reproducer please? It will speed up a fix a lot.
                > I had eyballed ITW, and the chage really should be strightforward. Only I'm
                > hesitating with way, how to verify the fix.

                I am very sorry, but I can't.

                I don't have access to Internet at work. I have no means to upload even a single JAR or a JNLP file.

                The following code will always fail when executed as a JWS application in current ITW version. Maybe you
                can reproduce it in some reproducer that you already have.

                public class TestDownloadService2Lookup {

                import javax.jnlp.ServiceManager;

                public static void main(String[] args) {

                ServiceManager.lookup("javax.jnlp.DownloadService2");

                }
                }
            

## Comment 17360
Date: 2019-02-13 17:15:53 +0000
From: JiriVanek &lt;<jvanek>&gt;

So the good new is that I made an reproducer and made DownloadService2 registered.
                - http://icedtea.classpath.org/hg/icedtea-web/rev/cb75d5ae33e0

                The bad new is that the DownloadService2 is unimplemented interface in ITW. It should be easy to finish
                the implementation, But there are more urgent bugs before 1.8 release;((
            

## Comment 17366
Date: 2019-02-14 13:57:00 +0000
From: jc.garcia.gomez

(In reply to JiriVanek from comment #7)
                > So the good new is that I made an reproducer and made DownloadService2
                > registered.
                > - http://icedtea.classpath.org/hg/icedtea-web/rev/cb75d5ae33e0
                >
                > The bad new is that the DownloadService2 is unimplemented interface in ITW.
                > It should be easy to finish the implementation, But there are more urgent
                > bugs before 1.8 release;((

                Ok, I understand that this is not the most used service of JNLP.

                But, please, let me know when a fully implemented version of DownloadService2 is released.

                Thank you, Jiri!

**Comment by mayurjaiswal1000** [comment]
Hi all, We have moved to OpenJDK recently, My Application gives Unsupported Exception and my application doesn't launch. Is there any fix added for this ?

**Comment by sclassen** [comment]
We are happy to take PR agains master.
- getCachedResources() should be straight forward to implement. There is net.adoptopenjdk.icedteaweb.resources.cache.Cache which servers as an entry point

- getUpdateAvailableResources is a littel more involved. We are currently refactoring the code responsible for fetching resources. Once this is done this method can be tackeled
